### ISSUE TITLE
Review Ticket for Geospatial Data Analysis

### ISSUE THREAD

**Issue by JMParr** [programminghistorian/ph-submissions#102]
The Programming Historian has received the following proposal for a lesson on 'Geospatial Data Analysis' by @ladew222. The proposed learning outcomes of the lesson are:
     
- To learn how to use geographic data to analyze historical movements
- To learn how to obtain historical census data in R 
- To learn how to merge this public data with other historical data.
- To learn how to visualize the insights you can gain from this merged data
 	
In order to promote speedy publication of this important topic, we have agreed to a submission date of no later than 90 days. The author(s) agree to contact the editor in advance if they need to revise the deadline.
 
If the lesson is not submitted by October 30th, the editor will attempt to contact the author(s). If they do not receive an update, this ticket will be closed. The ticket can be reopened at a future date at the request of the author(s).
 
The main editorial contact for this lesson is @JMParr. If there are any concerns from the authors they can contact the Ombudsperson @ianmilligan1 or @amandavisconti.

---

The Programming Historian has received the following tutorial on 'Geospatial Data Analysis' by @ladew222. This lesson is now under review and can be read at:

https://github.com/programminghistorian/ph-submissions/blob/gh-pages/lessons/geospatial-data-analysis.md

Please feel free to use the line numbers provided on the preview if that helps with anchoring your comments, although you can structure your review as you see fit.

I will act as editor for the review process. My role is to solicit two reviews from the community and to manage the discussions, which should be held here on this forum. I have already read through the lesson and provided feedback, to which the author has responded.

Members of the wider community are also invited to offer constructive feedback which should post to this message thread, but they are asked to first read our Reviewer Guidelines (http://programminghistorian.org/reviewer-guidelines) and to adhere to our anti-harassment policy (below). We ask that all reviews stop after the second formal review has been submitted so that the author can focus on any revisions. I will make an announcement on this thread when that has occurred.

I will endeavor to keep the conversation open here on Github. If anyone feels the need to discuss anything privately, you are welcome to email me. You can always turn to @ianmilligan1 or @amandavisconti if you feel there's a need for an ombudsperson to step in.

## Anti-Harassment Policy

This is a statement of the Programming Historian's principles and sets expectations for the tone and style of all correspondence between reviewers, authors, editors, and contributors to our public forums.

> The Programming Historian is dedicated to providing an open scholarly environment that offers community participants the freedom to thoroughly scrutinize ideas, to ask questions, make suggestions, or to requests for clarification, but also provides a harassment-free space for all contributors to the project, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age or religion, or technical experience. We do not tolerate harassment or ad hominem attacks of community participants in any form. Participants violating these rules may be expelled from the community at the discretion of the editorial board. If anyone witnesses or feels they have been the victim of the above-described activity, please contact our ombudspeople (Ian Milligan and Amanda Visconti - <http://programminghistorian.org/project-team>). Thank you for helping us to create a safe space.

**Comment by acrymble** [comment]
i think you have an extra lesson title in there by mistake: "The Programming Historian has received the following tutorial on 'Editing Audio with Audacity' by @ladew222."

**Comment by JMParr** [comment]
Whoops. Thanks, @acrymble - I've fixed it now.

**Comment by nolauren** [comment]
I am having issues replicating this. The data selection from NHGIS is unclear. @ladew222, can you clarify?  Also, it reads like a tutorial for NHGIS although the initial framing suggests otherwise. @ladew222, which route are you most interested in pursuing? It will help me provide better feedback.

**Comment by JMParr** [comment]
Thanks, @nolauren @ladew222 can you help clarify?

**Comment by ladew222** [comment]
Sure. I will add some more detail and clarity on how to use their service. I will update the tutorial in the next few days.  As a general focus, I do not envision this as a NHGIS tutorial. I included it because the service is particularly(or uniquely) useful for historical research as it contains downloadable files for all US Censuses that are ready for processing.  Most others—or all possibly—contain contemporary data.  But I am open to suggestions. If it would be better to section the discussion on NHGIS off somehow or put it in an appendix, I am open to suggestions.   

Thanks,

—Eric

**Comment by ladew222** [comment]
I added an appendix with a step-by-steps description on how to use NHGIS to download the shapefiles and census data that is utilized in the analysis section of the tutorial.  I thought an appendix might be the best location for this detail so that it does not take away from the analysis section of the tutorial. And I do not want too much focus to be on gathering the datasets even if it is necessary for the analysis portion. But I am open to suggestions. I also uploaded the [project files](https://github.com/programminghistorian/ph-submissions/tree/gh-pages/assets/geospatial-data-analysis) to the assets folder which which will match the data downloads I use in the tutorial. 
And thank you.

**Comment by nolauren** [comment]
Looking over the revisions, my suggestion is that this be broken up into two tutorials: one on how to use NHGIS and the other about GIS data analysis. Since @ladew222 says the data analysis part is the main interest,  I think just focusing on the second one is fine.  I’d outline what kinds of GIS analysis the tutorial will cover and why. The data then needs to be prepackaged, easily accessible,  and easy to read in.

**Comment by nolauren** [comment]
Concerning the skill level of this tutorial: The intro suggests one doesn’t need a lot of experience with R.   I think it reads like it is for an intermediate user at minimum.  I think that is fine. With that said, there still needs to be more explaining why one should pursue these kinds of analysis. Why geocode? What are the visualization methods for spatial data (i.e choropleth, etc)?  What kind of spatial knowledge is possible?

**Comment by nolauren** [comment]
Code:  The code needs to be clearer and cleaned up. For example, sometimes “=“ is used to assign an object and then other times “<-“.  There are plots with no code so either include the code or remove the plot.  There are also a lot of different libraries going on here for how to do analysis - base graphics  (i.e, plot, hist, etc), plotly and tmap. I’d recommend picking one and really deep diving into the analysis that library makes possible or at least explaining why one should switch between each of these.  Like the code, the piece also needs to be proofread.

**Comment by nolauren** [comment]
Happy to expand on anything or to throw ideas around for how to restructure the piece!

**Comment by JMParr** [comment]
Thank you, @nolauren ! So, in sum, it looks like this would work better as a more targeted lesson (with additional context to explain the rational), and there are some problems with the code that need to be fixed?

**Comment by ladew222** [comment]
Thank you @nolauren as well. I will begin looking at the work with your feedback in mind to discern how to restructure with your guidelines and suggestions. And thanks for the help and offer of aid with the restructuring; I will most likely take you up on this as I work on expanding background discussions in some areas. I will also clean up the code as mentioned and re-classify the tutorial as intermediate/advanced (I was a bit uncertain about my classification here). In addition, I will work on packaging the data, which will make separating the NCGIS information work better.

**Comment by nolauren** [comment]
Yes @JMParr . Happy to throw ideas around for how to restructure if I can be of help!

**Comment by ladew222** [comment]
I have done some restructuring and edits based on your recommendations; thank you. First, I broke the tutorial in two. I took out the NHGIS section and put it into a separate tutorial, which I linked.  With this change, I created a direct download link so users can download the files used in this tutorial directly. I created a folder with the necessary files. I could not zip the contents and upload due to size restrictions. 

I added more explanation and background in the introduction, highlighting in more detail both how geographic information can aid historical research and how geospatial data in particular can be of use. I also added more information on how this type of GIS analysis can inform research and provide insight. I also added some clarity and explanation on the two graphic libraries used (TMAP and PLOTLY). Some of this was already in the TMAP section, but more was needed in PLOTLY.  I thought about removing this section. But I left it because it creates a non-mapped means to explore multiple variables in a similar way in which we use TMAP, which can be very useful when exploring multi-causal historical events. We discuss similar means of using chloropleths before using this method. I also added additional discussions on other types of visualizations as well as some links to broader discussions on visualization options. I also cleaned up the code and text, with particular attention to issues to noted.

**Comment by acrymble** [comment]
@JMParr this looks like it's been sitting for some time. Is this in need of further revision?

**Comment by ladew222** [comment]
Thanks @acrymble and let me know if I can help in any way.

**Comment by JMParr** [comment]
Yes, sorry. I think it appears to have addressed some of the feedback, but I'd like to make sure that @nolauren is satisfied with the R-Language programming. I have tagged her in the post, but will follow up with an email.

**Comment by JMParr** [comment]
Just an update - @nolauren has been bogged down with campus visits. She's hoping to take another look at the code this weekend.

**Comment by ladew222** [comment]
Thanks for the update. No problem; I understand completely.

**Comment by JMParr** [comment]
While we're waiting on the reviewers, another reader had some questions for your consideration. He wondered if you had considered Leaflet as a better fit for what you are trying to do, since it would make the process more transparent.

He also suggested removing the section about exploring the data, and focusing the lesson more specifically on tasks like the quickest path to a clorepleth with R.

**Comment by nolauren** [comment]
I appreciate how the NHGIS section is split out and now provides
a direct link to the data. This makes it easier to follow and to replicate.
The added explanations in the tutorial are also very helpful.

However, there are major issues in regards to the structure
of the tutorial. The major issue is the use of so many different approaches. 
When addressing graphics, for example, there is base graphics (i.e, plot, hist, etc),
ggplot, plotly, and tmap. Further, these are mostly presented without any
explanation. How does `plot()` work? Why call `as.character`
and `as.numeric`? Even within a given approach, the code confusingly switches
back and forth between different calling structures, for example the x-y
plotting mechanism:

```
plot(MembersPer10K,ChurchesPer10K)
``` 

And the formula interface:

```
plot(x ~ y,xlab="Per capita income in previous year",ylab="White People Per 10k")
```

In one case, merging two datasets `by.x` and `by.y` is specified. In
another, the columns are renamed to have the same names and then use the `by`
parameter.  If the goal is to show how to merge datasets, then the tutorial should only show one approach. Or, it needs to be explained that these are two different approaches along with the pros/cons. 

I recognize that the code works and is sufficient for a specific project. However, the shift between so many approaches, with so few explanations, makes this very difficult for a tutorial oriented for a broader audience.  Also, the piece needs to be edited for clarity.

**Comment by ladew222** [comment]
Thanks @nolauren. I appreciate the help making the article appeal to a broader audience, which is my goal as well. I have attempted to make the changes you suggested broadly, and addressed the ones you mentioned specifically. I removed the formula notation from the plot function where it existed. I also simplified the usage of libraries.  Ggplot was removed a while back, but the install line for the library which still existed—which is now gone. I also removed plot.ly from the end of the lesson and moved it to a footnote in the section on other models and visualizations. Now the tutorial uses one graphing library (tmap for mapping) and R base graphics.

On the data merging side, I added some explanation to why I am merging using two different notations. Basically, the second notation is different because I am merging on multiple fields. I clarified that the merging notation was different for this reason. In this same section I also explained that I used the as.numeric and as.character so that the two data frame variable types matched ahead of the merge. 

I tried to make some changes to the discussion on visualizing plots using basic regressions as well in response to you question on “How does plot work?”  In this section, I am focused on setting up a scatter plot as a means to visualize possible correlations, but I realized that switching back from a histogram to scatter plots could be difficult, even as the histogram is necessary to assess distribution.  As such, I now followed the discussion on correlations and scatterplots with the example of a basic scatterplot that is linear before looking at distribution.  Then, I moved on to the histogram to illustrate how we assess the data further and why it is often necessary to perform log transformations on the data(count data) ahead of creating a scatterplot of the transformed count data.
I also edited the the piece for clarity with the help from a second set of eyes, but I am not sure where you are having difficulty outside of the points above so hopefully that is cleaned up. Thank you again for the feedback.

**Comment by greebie** [comment]
Hello everyone, I have been enlisted to provide a review as well.  I think this tutorial is pretty ambitious and there are some very good things here.  I agree with @nolauren that the tutorial shifts around some pretty complex analytic techniques that could use some explanation.  

A few simple technical changes would help a great deal:

1. Put the introduction first and pare it down to a succinct explanation about what you are trying to do and how you are going to do it.  At this stage it still seems quite targeted at people already familiar with the material, whereas I tend to think of the PH audience as a grad student who maybe is curious about programming, but really has more passion for more traditional history.  
2. Both the pre-requisites and lesson goals would be better in bullet points.  These are the things that I would want to skim over to see if I'm interested in continuing further.
3. Use fully-worded variables for all your tutorials.  Instead of `cntyDCG <-` write `county_{explain what DCG refers to}`.   
4. Remove the elements that are introductory to the R-Studio interface.   Assume that people understand what it means to download packages and install libraries.  Perhaps use that space to provide some quick details about the packages you are using.
5. Try to remove jargon words as much as possible or explain them.  There are a few moments when you assume that the audience is familiar with United States political geography which may not be the case.

Overall, I think this tutorial can be very valuable, but could benefit from more focus.  Some knowledge of the reader is assumed (eg. "basic plotting") but others are not (the R interface).  There are a number of discussions about religion, race, income, churches, rural/urban populations etc. which are interesting, but it's not clear what we are supposed to draw from the discussions. As @nolauren discussed, you take different approaches to accomplishing similar tasks.

Perhaps focusing on a narrative would help.  For instance, as a Canadian, I know little about the Carolinas and it would be good to understand why a discussion about race and income is important there and/or why you would bring up Assemblies of God churches rather than some other group.

If not a narrative, then more clarity about the process you are bringing us through, with each paragraph building on the previous one, with plenty of reiteration of your objectives, which are, based on how I read your goals section 1) get geo-political-social traits from census data 2) merge it with other public data 3) visualize 1 & 2 in a geographic plot.  Mocking your way through a simple research question would also be nice.

The organization of the tutorial does not follow this in a clear way, yet.  For example, you bring up "geo-coding" half-way through the tutorial, but this seems like an essential component to the merge in #2.  Let the reader know that you are going to introduce them to this helpful process.  

The conclusion is a bit abrupt.  It's nice to see other methods of analysis (and thanks for the link to my correspondence analysis tutorial!) but I think it's more important to explain to your reader what you just brought them through and why you think it was worthwhile reading about it.  In fact, I am not sure it is necessary (though in my self-interest!) to add this section, if you can clearly bring the reader through 1, 2 & 3.

I really appreciate that there is a whole new world of data analysis available to us here and it's pretty cool.  In some ways I think that's one of the problems computational social sciences are suffering from -- too many options.  I think if you were able to guide the reader towards a few useful approaches to geocoding a data set with a census, with few distractions that would provide a world of difference.  It would bound our understanding of geospatial analysis to something bite-size and then we can perhaps go into greater detail if we catch the geospatial bug.

**Comment by JMParr** [comment]
Thank you, Ryan, Adam, and Lauren for your feedback. In sum, the feedback
is as follows:

1.) Some organizational changes, including moving the intro to the
beginning, and making it more clear what the purpose of the tutorial is.
The tutorial as a whole should be more narrative in form, and the narrative
needs to be more focused. The conclusion should be expanded a little bit.
And the tutorial would benefit from some more signposting along the way.

2.) Clarify pre-requisite knowledge, and bullet point them and the lesson
goals.The readers flagged a few other spots that are in need of
clarification.

3.) Address jargon-y language, and use the fully-worded variables.

4.) Some adjustments are needed to the R-Studio section, including removing
the really basic stuff, and making it more clear what you are trying to do
with the R-Studio. Maybe a short explanation as to what the benefits are of
R-Studio versus Leaflet, or another tool.

5.) Another round of proof-reading.

Are you up for another round of revisions, Eric?

**Comment by ladew222** [comment]
Yes. I have been looking through the latest round of comments and they are very helpful.  Thanks everyone.  In order to add a bit more clarity, I am going to follow Ryan's helpful suggestion to add a research question along with some additional signposting so readers can see the bigger picture as they read through the details.  I will also work through the other suggestions as outlined and should have an updated version hopefully by the end of next week.

**Comment by ladew222** [comment]
Thanks everyone for the helpful suggestions and comments. I have worked through the changes and suggestions, and made changes of course. I added a more straight-forward last paragraph to my introduction. I still have the background information on geospatial analysis in the first part since those were added part of earlier revisions, but they can certainly be taken back out. I also added a brief conclusion and moved the introduction as well as bulleted the lesson goals. Within the text, I embedded a historical question to help the narrative; I also added a some signposting to help guide the readers. I used these changes to better clarify the goals of the lesson throughout, alongside the new conclusion. I also clarified the prerequisites and removed the basic R stuff but briefly described the benefits of R. I also tried to simplify the language whenever possible and changed the variable names as specified as well.

**Comment by acrymble** [comment]
I know you're still working on this. I just have a little query about the title. "Geospatial Data Analysis" is a bit vague. We may end up with future lessons that use other approaches to analyse geospatial data. Can this title be made more specific to the type of analysis you use here?

**Comment by ladew222** [comment]
Good point Adam. The thought had gone through my head as well. This lesson is use R in particular and is focused on how to analyze historical data. We could modify the title to something like "Geospatial Data Analysis for Historical data using R” but I am open other suggestions as well.

**Comment by JMParr** [comment]
How about Analyzing Historical Geospatial Data With R?

**Comment by JMParr** [comment]
I'm working on a header image for the lesson, incidentally. I should have
some options to you by mid-week.

**Comment by ladew222** [comment]
Sounds great to me. It is more descriptive and solves the issue. And thanks for the update as well.

**Comment by acrymble** [comment]
I read through the lesson, and I think I'd suggest something like "Visualizing Geospatial Data with R". You've got the cloropleth map (which itself is a valuable lesson), then some other graphs. That's the core skill, I think.

Really interesting stuff in here. Thanks for taking the time to write it.

(Updated after further thought)

Or, if you want to keep the analysis in there, what about "Analysis of Geospatial Data through Visualization using R"

Some of your readers will want to learn how to make a cloropleth map with R, so you wouldn't want them to overlook your lesson by thinking it was just about analysis. I hope that helps.

**Comment by acrymble** [comment]
@JMParr is this ready or are there conversations happening elsewhere? It looks stalled so please make sure we can tell what's happening.

**Comment by JMParr** [comment]
This is ready, and in production.

**Comment by ladew222** [comment]
Great. Thank you everyone, and please let me know if I can provide assistance in the future.

**Comment by acrymble** [comment]
This doesn't seem to be published yet. This ticket should remain open until the lesson is published.
