### ISSUE TITLE
Review Ticket for 'XML and XSL' lesson

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/ph-submissions#11]
_The Programming Historian_ has received the following tutorial on '**Transforming Historical Data for Reuse and Republication: A Guide to XML and XSL Transformations**' by @mhbeals. This lesson is now under review and can be read at:

http://programminghistorian.github.io/ph-submissions/lessons/transforming-xml-with-xsl

I will act as editor for the review process. My role is to solicit two reviews from the community and to manage the discussions, which should be held here on this forum. I have already read through the lesson and provided feedback, to which the author has responded.

Members of the wider community are also invited to offer constructive feedback **which should post to this message thread**, but they are asked to first read our Reviewer Guidelines (http://programminghistorian.org/reviewer-guidelines) and to adhere to our anti-harassment policy (below). We ask that all reviews stop after the second formal review has been submitted so that the author can focus on any revisions. I will make an announcement on this thread when that has occurred.

I will endeavour to keep the conversation open here on Github. If anyone feels the need to discuss anything privately, you are welcome to email me. You can always turn to @ianmilligan1 or @miriamposner if you feel there's a need for an ombudsperson to step in.

**Anti-Harassment Policy**
_

> This is a statement of the Programming Historian's principles and sets expectations for the tone and style of all correspondence between reviewers, authors, editors, and contributors to our public forums.
> 
> The Programming Historian is dedicated to providing an open scholarly environment that offers community participants the freedom to thoroughly scrutize ideas, to ask questions, make suggestions, or to requests for clarification, but also provides a harassment-free space for all contributors to the project, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age or religion, or technical experience. We do not tolerate harassment or ad hominem attacks of community participants in any form. Participants violating these rules may be expelled from the community at the discretion of the editorial board. If anyone witnesses or feels they have been the victim of the above described activity, please contact our ombudspersons (Ian Milligan or Miriam Posner - http://programminghistorian.org/project-team). Thank you for helping us to create a safe space.

_

**Comment by jonathanblaney** [comment]
Hi @mhbeals. I found this a clear and focused introduction to XSLT basics. The example texts are an excellent basis for demonstrating of the power of XSLT and the additional scripts that you provide as part of the download will be particularly useful for beginners after they have finished the tutorial. The exercises are clear and cover the right first transformations that most people will want to do with XSLT.

It's very condensed and therefore asks a lot of the reader. I think it's reasonable to expect the reader to do some work and reading around, but more pointers to useful resources would be beneficial.

The set-up information is just right: very common tools with no config required. I wonder whether a sentence along the lines of "when you're comfortable with XML technologies you might like to explore dedicated XML editors..." might be useful. Although I found the set-up easy you might consider putting the stylesheet declaration on a line on its own for clarity: on my laptop the line break made it unclear that I should type `<?xml-stylesheet type...` rather than `<?xml-stylesheettype...`.

I only have a few suggestions for amplification here and there, which I hope might make the course even more useful for readers coming to XML and XSLT with little or no prior knowledge.
- Word and Excel. Given the scenario outlined at the beginning of the tutorial, I think there should be some mention of transforming Word and Excel, especially that docx and xlsx _are_ XML. The XML underlying a simple Word file is a horrible mess, but this is the beauty of XSLT: you can unzip the docx then use XSLT to blow away the bloat. With Excel there are more ways to transform, but I think Excel's own built-in XML transformation tool is the simplest to use.
- The XML introduction is very brisk. Are there are a couple of online tutorials that you can link to? It's a shame that the Programming Historian doesn't currently have a dedicated XML tutorial. The Wikipedia link to XSLT elements here might be confusing for newcomers.
- You ask the reader to open the base XML file in a text editor. I wonder whether you could additionally ask them to open it with a browser, which will display the file in a tree structure that is perhaps more comprehensible to someone new to XML and this data; it would also set up the first transformation you do, which will drop the elements from this display.
- When you discuss the path to `title`, is it worth mentioning that this is XPath? Half the time when I get stuck with XSLT I do a web search for XPath syntax, because I'm not hitting the right node.
- A brief explanation of why `<xsl:text>` is sometimes necessary but sometimes not (as with the brackets in Exercise B) might be helpful. Also in the solution to Exercise C you could add a note that a literal space instead of the hex code you use would also be correct.

I really enjoyed this tutorial and I think newcomers to XSLT will be encouraged by the speed with which it gets them transforming real historical data. This is going to be a very good addition to the Programming Historian.

**Comment by acrymble** [comment]
Thanks @jonathanblaney. We have one more review due to come in, so I'll suggest we wait before responding to these points.

**Comment by mhbeals** [comment]
Thank you @jonathanblaney for your comments. I am, as @acrymble notes, waiting for the second review, but I think I will be able to integrate most of your suggestions without too much difficulty.  I actually hadn't opened up a docx file recently and was quite surprised at some of the 'helpful' metadata inside!

**Comment by TessaC** [comment]
Hello @mhbeals! I am just n the middle of reading through your tutorial for the review process and I will be posting the proper comments soon. However, I got stuck when working through the different steps. I am using a Mac, and the TextEdit programme, but when I try to save the xsl file, the programme doesn't allow me to save the file with the xsl extension only. I tried to save it differently, but then I always get an unstructured error output when I open the xml file.  Any suggestions what I should do?Many thanks,
Tessa

**Comment by mhbeals** [comment]
@TessaC Sorry to hear that. If TextEdit will not let you save it as a xsl directly, you may need to save as a .txt and then change the extension in Finder.  Does this work?

**Comment by acrymble** [comment]
I suspect TextEdit isn't a text editor; it's more comparable to Wordpad than Notepad on PC. You may need to download something. I use KomodoEdit, but there are others.

**Comment by TessaC** [comment]
Dear both, 
Thanks, @mhbeals! This worked fine. And thanks also @acrymble, I just used the basic TextEdit, because this is what the tutorial suggested, and I wanted to retrace those steps exactly as someone reading the tutorial would do.

**Comment by TessaC** [comment]
Hi @mhbeals, 
This reads as a very useful introduction for anyone who might want to work with large databases and who needs to know how to filter and display the material they need.  It provides useful step by way guidance for working with xml and xsl and the proposed exercises will help students of the tutorial to gain some confidence in working with a transformer.
Here are some minor points/suggestions regarding the specific sections:

The introduction which explains in what context a knowledge of HTML and XSL is useful, I just thought it might make sense to have the learning outcomes more clearly signposted, ( i.e in a separate subheading) so the reader can jump to that section quickly to find out exactly what will be covered. 

Overall, I thought that the learning curve for “What is XML?” and “What is XSL” is fairly steep and it might make sense to note that a basic awareness of XML will help you to succeed in this tutorial. OR as @jonathanblaney suggested, to  include links to online tutorials.  That said, the basic structuring elements of xml are very well explained and make everything a bit clearer.  In comparison, the “What is XSL?” is perhaps a bit short and  an additional sceenshot (as in the previous section) would be helpful here. 

Once you get past this hurdle, the instructions about the software packages and the XSL transformer are clearly spelled out and easy to follow. The same goes for your well prepared dataset, with clear instructions on how to download, and open the files. (Just the link in the tutorial to the Scissors and Paste Database wasn’t working).
In the “Creating and Testing your XSL file” section, it might be useful to point out that using the basic version of TextEdit in Mac won’t allow you to save the stylesheet as an xsl extension directly. Rather, as you advised me, one needs to change the extension in the Finder menu after saving the file. 

I also thought it might be more helpful of including a screenshot of how the xsl stylesheet once all the instructions are inserted.  (Currently the screenshot comes before the code is  <xsl:value-of select="root"/> are inserted, and then students of the tutorial can not see and compare the final version of the stylesheet with their own file.)

I found the section on “Printing Values” and “For Each Loops”, particularly instructive and useful because it provides the students of the tutorial with a deeper understanding of how the elements are structured and what instructions are necessary to get to the right element. Similarly the “Filtering Results” sections, which is probably what many people would want to do with their own databases initially. 
Exercises section: Again, just as an additional signpost for the reader, it might be useful to insert a sentence pointing out that the solutions to the exercises can be found at the bottom of the tutorial if they get stuck. 

Conclusion: You mention the option of further transformation commands to customize output – do you think there might be a follow up tutorial which explains some of them in more depth? Then one could refer to this?  

Finally, just in terms of where this tutorial will be positioned on the Programming Historian, will it be grouped   with other existing lesson directories, or will it form part of a new series just dedicated to xml /xsl?

I have also attached a file where I just corrected a few minor typos and made one or two stylistic changes, should you wish to use them. 

I hope this all makes sense,
Best ,Tessa

**Comment by TessaC** [comment]
[Beals_Review.docx](https://github.com/programminghistorian/ph-submissions/files/221032/Beals_Review.docx)
Attached the review with minor corrections highlighted

**Comment by acrymble** [comment]
Thanks to both of our reviewers, @jonathanblaney and @TessaC. We'll now close the open review so that @mhbeals can focus on revising the lesson based on this feedback.

The main themes seem to me to focus on the opening section, and making sure there's enough signposting for the reader. @jonathanblaney has also made some suggestions about docx and xlsx files, which I'd invite you to respond to.

In addition to these, there are also a number of minor points and wording suggestions, most of which should be fairly easy to address.

With regards to the section where the lesson will appear, we're currently working on rejigging the ordering, so you don't need to worry about that.

@mhbeals I'll turn it over to you to respond and revise. Let me know if you would like to discuss anything, or feel free to respond directly here to the thread.

**Comment by mhbeals** [comment]
My thanks as well to @jonathanblaney and @TessaC (and @acrymble for your initial suggestions). I will be working on these shortly and do not think there will be any difficulties in addressing your suggestions fairly quickly.

Best, MHB

**Comment by mhbeals** [comment]
Dear @acrymble. I believe I have addressed all the concerns. I haven't inserted another screen shot as requested by @TessaC as I think the full version of every stylesheet is written in code, as you suggested previously. Otherwise, I have endeavoured to include them to the best of my ability.

**Comment by acrymble** [comment]
Thanks @mhbeals I have gone through and made a few minor copy edits.

Before we move the files, we need a difficulty rating (either beginner or intermediate I think. Let me know your opinion). I need a 1 sentence bio for your author statement. And we need an icon to go on the lessons page. I suggest this one because it suggests transformation to me. But if you have something else in mind that fits our visual theme let me know:

https://www.flickr.com/photos/britishlibrary/11080045716/

**Comment by mhbeals** [comment]
@acrymble Thank you for these copy edits. 

I had hoped the lesson would be considered beginner-level but I will defer to your judgement as an external reader; I am happy with either.

The image is great and my bio is as follows:
M. H. Beals is a Lecturer in Digital History at Loughborough University.

**Comment by jonathanblaney** [comment]
I'd say they're beginner-level too, as I mentioned in my review. I think @mhbeals has covered the main beginner use cases very well.

**Comment by TessaC** [comment]
Dear@mhbeals, @acrymble and @jonathanblaney
For purposes of comparison, I just had a look again through the other tutorials on Programming Historian which are marked beginner or intermediate and would also think that your tutorial, Melodee, should go under beginner level in terms of difficulty.

**Comment by acrymble** [comment]
Ok we're all ready to go. I just need to move the files.

Can any of my git-competent friends help with that process? @ianmilligan1 or @wcaleb ?

**Comment by ianmilligan1** [comment]
Sure I can migrate it over now @acrymble. No assets, just images right?

**Comment by acrymble** [comment]
shouldn't be any assets other than the images.

**Comment by ianmilligan1** [comment]
Great. it's appearing here: http://programminghistorian.org/lessons/transforming-xml-with-xsl.

I'll leave it to you to update the YAML block (I added in reviewers while I was at it and set it to today's date, but still missing your name and probably other stuff). I see images are in so assume you're good w/ adding it to the lesson index, @acrymble, tho happy to do if not.

**Comment by acrymble** [comment]
Thanks @ianmilligan1, but I think the wrong file got moved. I can cut and
paste the differences, but probably worth checking your workflow to make
sure something hasn't gone wrong.

Note my name is missing in the YAML on the submission site:
https://github.com/programminghistorian/ph-submissions/blob/gh-pages/lessons/transforming-xml-with-xsl.md
https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/transforming-xml-with-xsl.md

Is this a glitch or just a move from an out of date branch?

Thanks for your help by the way.

Adam

**Comment by ianmilligan1** [comment]
Ah I'd missed your most recent commit. I will move it in a few.

**Comment by ianmilligan1** [comment]
Updated – does [this look good](https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/transforming-xml-with-xsl.md)? Sorry about that!

**Comment by acrymble** [comment]
Thanks.

**Comment by acrymble** [comment]
I had to shorten the title a bit, but you're live!

Thanks to @jonathanblaney @TessaC and to @mhbeals for all of your effort on this. We can't do it without you!

http://programminghistorian.org/lessons/transforming-xml-with-xsl

Please let as many people know as you can. And if you're in Poland right now, spread the word.

**Comment by TessaC** [comment]
Hi   @mhbeals, @jonathanblaney , @acrymble!
Great, it looks really good! Unfortunately I am not in Krakow but in depressive post-Brexit Britain, but for those of you who are there, hope you have an interesting conference!
Best, Tessa
