### ISSUE TITLE
Review Ticket for 'Editing Audio with Audacity'

### ISSUE THREAD

**Issue by jerielizabeth** [programminghistorian/ph-submissions#15]
The Programming Historian has received the following tutorial on 'Editing Audio with Audacity' by @bmw9t. This lesson is now under review and can be read at:

http://programminghistorian.github.io/ph-submissions/lessons/editing-audio-with-audacity

I will act as editor for the review process. My role is to solicit two reviews from the community and to manage the discussions, which should be held here on this forum. I have already read through the lesson and provided feedback, to which the author has responded.

Members of the wider community are also invited to offer constructive feedback which should post to this message thread, but they are asked to first read our Reviewer Guidelines (http://programminghistorian.org/reviewer-guidelines) and to adhere to our anti-harassment policy (below). We ask that all reviews stop after the second formal review has been submitted so that the author can focus on any revisions. I will make an announcement on this thread when that has occurred.

I will endeavor to keep the conversation open here on Github. If anyone feels the need to discuss anything privately, you are welcome to email me. You can always turn to @ianmilligan1 or @miriamposner if you feel there's a need for an ombudsperson to step in.

Anti-Harassment Policy
_

> This is a statement of the Programming Historian's principles and sets expectations for the tone and style of all correspondence between reviewers, authors, editors, and contributors to our public forums.
> 
> The Programming Historian is dedicated to providing an open scholarly environment that offers community participants the freedom to thoroughly scrutinize ideas, to ask questions, make suggestions, or to requests for clarification, but also provides a harassment-free space for all contributors to the project, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age or religion, or technical experience. We do not tolerate harassment or ad hominem attacks of community participants in any form. Participants violating these rules may be expelled from the community at the discretion of the editorial board. If anyone witnesses or feels they have been the victim of the above described activity, please contact our ombudspersons (Ian Milligan or Miriam Posner - http://programminghistorian.org/project-team). Thank you for helping us to create a safe space.

**Comment by jswafford** [comment]
This is a great tutorial! It’s fairly easy to follow and nicely organized, and it contains exactly the right amount of explanation. Its objectives are clearly stated, and it has a consistent model reader in mind throughout the lesson. I’d recommend making the payoff clearer, updating the lesson for the new version of Audacity, and possibly rethinking the layout of step-by-step directions:  

 -The opening could be enhanced by adding a sentence explaining why someone might want to make a podcast or an audio file.
-Which version of Audacity is this tutorial using? I’m using 2.1.2 (released January 2016), and it has some different menu options. I’d recommend updating the tutorial to make it current with the newest version of Audacity.
-The introduction to waveforms would benefit from a little more explanation: what are the units for the axes (e.g. the time markers are in seconds, but what’s the y-axis measured in, and what do the negative numbers represent)? Also, would “volume” rather than “loudness” be a better descriptor for the y-axis? 
-The tutorial does a great job of explaining the tool palette, but it might also be nice to have a screenshot of the audio tools (play button, record, stop, fast forward, rewind). 
-In the new version of Audacity, recording a new track plays (and records) the old track in the background. It would be helpful for the tutorial to specify that users should hit mute button on the Bach track to record an audio track without also recording the music.
-The tutorial might be improved by converting the step-by-step directions into bullet points/numbered lists to better demarcate them from the explanation, since currently, they’re all part of the same paragraph: there’s a lot of text there, and it might be difficult for people to follow visually.
-In the new version of Audacity, Fade In & Fade Out are under the “Effects” menu, not the “Tools” menu. 
-For the crossfade section, the instructions say “Delete all but the first seven seconds of the Bach Introduction,” but the image only shows the first 5.5 seconds. It would be clearer if either the directions or the image were changed so they matched up.
-With the new version of Audacity, deleting everything after the 7th second is surprisingly tricky: it won’t seem to let me click and drag through the end of the audio clip to then hit delete. To fix this, it might help to add instructions to create a split at second 7 (“Edit”->”Clip Boundaries” -> “Split”), then click the new sound clip and hit delete?
-Selecting “Crossfade Tracks” in the new version of Audacity brings up a pop-up window with a drop-down menu and other settings. It would be helpful if the tutorial specified what settings users should select.
It was a pleasure to follow along with this tutorial!

**Comment by walshbr** [comment]
Ah geez - I didn't realize that Audacity had come out with a new version since I submitted this. Thanks for the great feedback @jswafford - I'll go through and update things accordingly!

**Comment by walshbr** [comment]
And to answer your question @jswafford - I was using the previous version of Audacity - 2.1.2. Thanks for pointing that out!

**Comment by walshbr** [comment]
Just a quick note to say that I updated the tutorial with @jswafford's comments. The commit got a bit wonky so that it is a bit difficult to read, but that commit is [here](https://github.com/programminghistorian/ph-submissions/commit/b2144521a4a98564c9fd0a9ff9cbd288e187b97e).

**Comment by wcaleb** [comment]
The figure syntax for this lesson needs to be updated to reflect the [new guidelines posted here](http://programminghistorian.org/new-lesson-workflow#figures), and all image files will need to be placed in a subdirectory.

**Comment by walshbr** [comment]
@wcaleb done! Thanks -

**Comment by jerielizabeth** [comment]
thanks @bmw9t and @wcaleb!

**Comment by celestetvs** [comment]
Great tutorial that will be of use to a lot of people! The task accomplished in the lesson is reasonable and the intended audience matches the instruction. I'd recommend adding a few small points of clarification to ease readers through:

-Related to downloading the Bach audio file: I suggest explicitly directing readers to download the file first in the "Working with Audacity" section. 
-When I clicked on the Bach's Goldberg Variations link it took me to a MusOpen sign-in page. It would be helpful to advise readers that they'll need to signup for free to access the file. 
-The explanations of the x and y axis are clear and easy to understand. but I'd suggest breaking out the y-axis section into its own paragraph to increase skimmability. 
-The direction to "click somewhere on the wave" might be confusing since two waves are visible in the Bach track. It doesn't seem to matter for this tutorial whether one clicks on the top or bottom, but it might be useful to quickly explain why there are two wave forms for the Bach track and only one for the track created by the reader. 
-In the crossfade section: it would be helpful to remind the reader to switch back to the selection tool for the first step and, after selecting to the end of the track, to delete.
-More of a question than a suggestion: is it worthwhile to talk very briefly about pros/cons of different file formats in the Export section? Or to provide a link to such explanations?

Looking forward to pointing people to this tutorial in the near future!

**Comment by walshbr** [comment]
Thanks so much for the comments @celestetvs - I'll push up commits over the course of the next few days and let you know when I'm finished.

**Comment by jerielizabeth** [comment]
Thank you @celestetvs! These are really great suggestions!

@bmw9t as you go through these, a couple additional things to consider. Since this will be a "beginner" level tutorial, in addition to noting that they will need to register for an account, it would be useful to change the link to something link this

`[Bach's Goldberg Variations](https://musopen.org/music/download/6270/){:download="bach-goldberg-variations.mp3"}`

so that the file downloads directly, rather than opening in the browser. 

Another thing that I have noticed (and sorry I didn't catch this earlier) is the difference between mono and stereo recording -- I only notice because own recording came on as two waves, where your examples have one. It is worth mention what is going on there and recommending one or the other. 

Otherwise, I think we're in good shape! Once you're set, I'll go through for one more round of copyediting, just to make sure we haven't missed anything.

**Comment by walshbr** [comment]
@jerielizabeth - I just took your advice re: downloading the file automatically. It looks like doing it this way sometimes causes a slight quirk. If you're logged into MusOpen, it downloads as expected. If not logged in, it seems to sometimes download the html for the login page. I assume that is because the login page intervenes before the browser can get to the MP3. What do you think? Still worth doing? I can add some language to the effect of 'if the link doesn't work, make sure you log into MusOpen first' if that helps. The link on the staging server has it download right now, as you suggest. http://programminghistorian.github.io/ph-submissions/lessons/editing-audio-with-audacity.html

**Comment by jerielizabeth** [comment]
Hmm... that is an interesting quirk and counter to the "make it easier"
idea here. Perhaps then what is needed is:
1. instructions to create an account on MusOpen
2. then link to the download file with additional instructions on how to
save that file locally (right click and "Save Link As" on Mac .. not
entirely sure how on Windows.) @celestetvs, what would you recommend for
windows users here?

## 

Jeri E. Wieringa
Digital Publishing Production Lead, George Mason University Libraries
PhD Candidate, Department of History and Art History
George Mason University
www.jeriwieringa.com

**Comment by celestetvs** [comment]
The same instructions to right click and "Save Link As" should also work on Windows.

**Comment by walshbr** [comment]
@jerielizabeth I think I took care of everything now! Let me know next steps. Hopefully I didn't get a little too slaphappy with linking to external resources.

**Comment by jerielizabeth** [comment]
ok great!! Thanks @bmw9t! I will take one last look for copyediting purposes, but I think we nearly there! My week's been crazy, but I'm hoping for Friday!

**Comment by jerielizabeth** [comment]
Hi @bmw9t! I think we're ready to go! I made some copy edit in the latest push -- most are minor, but i did move things around in the "how to download" section. You of course have veto power on the edits, so go ahead and look it over. If you're happy, I'll move this over to the main site today!

**Comment by walshbr** [comment]
@jerielizabeth looks great to me! I made one change to italics. It should be set now. Thanks! Let me know when you send it out and I'll publicize it accordingly.

**Comment by jerielizabeth** [comment]
Soft publication of "editing audio with audacity" is up at http://programminghistorian.org/lessons/editing-audio-with-audacity. Last chance to make changes before the link goes on the lessons page.

**Comment by jerielizabeth** [comment]
Congratulations @bmw9t and thank you again to our reviewers @jswafford and @celestetvs ! This lesson is now live at [http://programminghistorian.org/lessons/editing-audio-with-audacity](http://programminghistorian.org/lessons/editing-audio-with-audacity). This ends the review process for this lesson!
