### ISSUE TITLE
Proposed Lesson: Running a Collaborative Research Website and Blog with Jekyll and GitHub

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/ph-submissions#237]
The Programming Historian has received the following proposal for a lesson on 'Running a Collaborative Research Website and Blog with Jekyll and GitHub' by Amanda Visconti (@amandavisconti). The proposed learning outcomes of the lesson are:

   
    Learn to edit existing and add new blog posts and pages to a Jekyll website
    Set up a Jekyll website to support a submission and feedback process for a community-authored blog

The author has been asked to keep the following in mind:

- The lesson should be integrated with the existing historiography and scholarly conversations on the relevant issues
- The lesson should not be too closely wedded to quickly changing interfaces and should be written with sustainability in mind.

In order to promote speedy publication of this important topic, we have agreed to a submission date of no later than 30 August 2019. The author(s) agree to contact the editor in advance if they need to revise the deadline.

If the lesson is not submitted by 30 August 2019, the editor will attempt to contact the author(s). If they do not receive an update, this ticket will be closed. The ticket can be reopened at a future date at the request of the author(s).

The main editorial contact for this lesson is @acrymble . If there are any concerns from the authors they can contact the French Ombudsperson @fdlaramee as Amanda is our English Ombudsperson and cannot act in this case.

**Comment by acrymble** [comment]
This is a note to say that @alsalin has returned to her position as Managing Editor and will now be the main contact for this lesson.

**Comment by amandavisconti** [comment]
@alsalin Would it be okay to shift our due date to September 15, 2019? @walshbr and I are nearing the finish line on the lesson, but our start of term is packed, so some time to polish things after the first week of class would be helpful.

**Comment by alsalin** [comment]
@amandavisconti sounds good!

**Comment by amandavisconti** [comment]
We've moved the draft to GitHub, and are finishing a few tasks before the lesson is ready for editing:

- [x] move to ph-submissions repo
- [x] skim live website view of draft for formatting/image errors
- [x] _AV currently doing:_ broken link check & make sure anchors work throughout text (e.g. [create a new post](#add-a-new-post))
- [x] _AV:_ look into the p.95 broken image
- [x] The broken links were all things where the () was the same as the [] and I forgot to look up if there’s a way to format links without repeating that twice
- [x] I think there are two places in the lesson that rely on “see Step #x”, but I will look at removing numbering and just putting in HTML anchors (which are better anyway) instead
- [x] get whitespace to format correctly vs. markdown in all code blocks
- [x] e.g. make sure special HTML anchor to #which-branch-is-default isn't broken by GitHub markdown somehow
- [x] notify editor via this lesson ticket
- [ ] Pre-publication tasks
  - [ ] add note to insert names of reviewers into thanks section once reviewers ID'd
  - [ ] note screenshots in images, zip file in assets; do we need to move these for publication?
  - [ ] ask about moving repo (and updating lesson) to use proghist/collabdemo rather than scholarslab/collabdemo

**Comment by amandavisconti** [comment]
@alsalin: @walshbr and I have completed the draft of our lesson, and it is ready for you here: [file](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/lessons/collaborative-blog-with-jekyll-github.md) and [preview](https://programminghistorian.github.io/ph-submissions/lessons/collaborative-blog-with-jekyll-github)

Thank you for editing!

**Comment by alsalin** [comment]
@JMParr will be taking the lead on this lesson!

**Comment by svmelton** [comment]
Hi @JMParr—checking in here. How is the review coming along? Have reviewers been identified?

**Comment by JMParr** [comment]
Hi, Sarah - Not yet, but I have started working on it.

**Comment by JMParr** [comment]
I have Willis Monroe and Jesse Sadler onboard to review. I'm in communication with them and getting them set up with the review ticket. More soon.

**Comment by amandavisconti** [comment]
(For reference: Review ticket is up at https://github.com/programminghistorian/ph-submissions/issues/278!)

**Comment by mariajoafana** [comment]
Since the review ticket is ongoing in #278 I'm going to close this proposal ticket
