### ISSUE TITLE
submissions site to use submissions site css

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/ph-submissions#25]
@wcaleb I'm trying to work on https://github.com/programminghistorian/jekyll/issues/193 which is the new lessons page. I'm trying to do that on this submissions site, and I've made some minor changes to the CSS, but the header of pages on the submissions site is set up to use the CSS from the live site. Can we change this so I can work on our submissions site without risking messing anything up?

**Comment by wcaleb** [comment]
I'm reluctant to make a habit of this, because changes get made on the live CSS that would have to be copied over to the submissions site so that lessons preview correctly for reviewers. 36931bfa0ccbc4b5b32f96ac1e3d8c540442f41b shows where and how to make the change if you want to do it temporarily. 

Another option would be to make copies of `_layouts/directory.html`, `_includes/header.html` and `css/style.css` and give the copies new names like `test-directory.html`. Then you could make a `test-index.md` that uses `test-directory` as its layout, and make that layout include the `test-header` that uses the `test-style.css` (which is the one you could mess around with). If that makes sense ... If it doesn't, you can change the header here temporarily, check your changes, and then change it back.
