### ISSUE TITLE
Proposition de traduction en français: Analyse de documents avec TF-IDF

### ISSUE THREAD

**Issue by fdlaramee** [programminghistorian/ph-submissions#273]
Je propose la traduction de la leçon "Analyzing Documents with TF-IDF", rédigée par Matthew Lavin, sous le titre "Analyse de documents avec TF-IDF".

La traduction est complète et disponible au https://github.com/programminghistorian/ph-submissions/blob/gh-pages/fr/traductions/analyse-de-documents-avec-tfidf.md; une version adaptée (légèrement) des documents de travail de la leçon a aussi été téléversée au https://github.com/programminghistorian/ph-submissions/blob/gh-pages/assets/tf-idf/lecon-fichiers.zip 

Le processus de révision débutera dès qu'un(e) membre de l'équipe sera disponible pour se charger de la rédaction.

**Comment by mariechristineb** [comment]
Cette leçon est maintenant en relecture: #364

**Comment by acrymble** [comment]
@spapastamkou this ticket has been open for several years. Can you please action this either to close it or to take it forward?

**Comment by spapastamkou** [comment]
@acrymble Thank you for your interest. I was looking at this just the day before you react and was not happy either, especially since it is FDL's work. 
That said, these tickets are not forgotten. We had decided as a team to keep tickets open for the lessons we have in stock for editing (mainly translations) as a reminder, even if this could take time. 
The lessons ready to edit were discussed in our last meeting in January, to organize the second round of edited lessons by the new editors. As a result, @InesSalome started editing the Github/Jekyll lesson (which we had received in the very beginning of the FR team). In the meantime, @matgille has been assigned the original FR JISC/TNA lesson (soon to come), @icolab continues work on the second original lesson for which the reviews just came in, and I prepare to edit the third original lesson we received.  
I do not know if @datalogism could have capacity to take up this soon, but otherwise I see no possibility before the other lessons already or soon-to-be under review are done.

**Comment by datalogism** [comment]
Hello  @spapastamkou, @acrymble i could take i charge this lesson but i also have 3 lessons to review and one to translate. How should this be prioritized ?

**Comment by mjlavin80** [comment]
As the lesson's author, I would be happy to help in any way that I can. Je parle un peu français, mais pas bien.

**Comment by spapastamkou** [comment]
@mjlavin80 Thank you for your willingness to help. However, we do not normally sollicitate authors when we review translated lessons, unless of course they are the translator of the lesson themselves. So we won't bother you:-) You can of course follow the process and comment as any member of the community can do in the review ticket. 
@datalogism has just taken this in charge and once he opens a review issue, he or I will post the issue number here so you will be able to easily follow if you wish so. We will then close this ticket.

**Comment by spapastamkou** [comment]
L'évaluation de la traduction se fait maintenant sur #454.
