### ISSUE TITLE
Review Ticket: OCR and Machine Translation

### ISSUE THREAD

**Issue by amsichani** [programminghistorian/ph-submissions#285]
The Programming Historian has received the following tutorial on 'OCR and Machine Translation' by @akhlaghiandrew . This lesson is now under review and can be read at:

http://programminghistorian.github.io/ph-submissions/lessons/OCR_and_Machine_Translation

Please feel free to use the line numbers provided on the preview if that helps with anchoring your comments, although you can structure your review as you see fit.

I will act as editor for the review process. My role is to solicit two reviews from the community and to manage the discussions, which should be held here on this forum.

Members of the wider community are also invited to offer constructive feedback which should post to this message thread, but they are asked to first read our Reviewer Guidelines (http://programminghistorian.org/reviewer-guidelines) and to adhere to our anti-harassment policy (below). We ask that all reviews stop after the second formal review has been submitted so that the author can focus on any revisions. I will make an announcement on this thread when that has occurred.

I will endeavor to keep the conversation open here on Github. If anyone feels the need to discuss anything privately, you are welcome to email me @amsichani . You can always turn to @amandavisconti if you feel there's a need for an ombudsperson to step in.

## Anti-Harassment Policy

This is a statement of the Programming Historian's principles and sets expectations for the tone and style of all correspondence between reviewers, authors, editors, and contributors to our public forums.

> The Programming Historian is dedicated to providing an open scholarly environment that offers community participants the freedom to thoroughly scrutinize ideas, to ask questions, make suggestions, or to requests for clarification, but also provides a harassment-free space for all contributors to the project, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age or religion, or technical experience. We do not tolerate harassment or ad hominem attacks of community participants in any form. Participants violating these rules may be expelled from the community at the discretion of the editorial board. If anyone witnesses or feels they have been the victim of the above described activity, please contact our Ombudsperson (@amandavisconti). Thank you for helping us to create a safe space.

**Comment by amsichani** [comment]
Hi @akhlaghiandrew , thanks or this submission!
I will be reading the lesson over the next week and providing some feedback for you to respond to, and then I will solicit formal reviewers.

One quick request :
Could you please fix some formatting issues on your current submission eg. adding TOC, basic metadata to the md file?

Also please let me know if you have any questions about the process.

**Comment by amsichani** [comment]
Hi @akhlaghiandrew , I 've slightly edit the existing submission in terms of layout and renamed the submitted file in order to follow the lesson's title -- this consistency will help also the overall structure of the lesson  within PH infrastructure later on. I am now going to have a closer look to the actual submission and get back to you with a couple of initial comments/suggestions before moving to the peer review process. Stay tuned.

**Comment by amsichani** [comment]
Hi @akhlaghiandrew - I now had a quick look at the submission . I think its an interesting tutorial overall. I d like to suggest you to have another look esp at the introduction and the conclusion and try to make your points and narrative more clear.

Please find below a list of initial comments from my part (mainly grammar/ syntax/ formatting at this point):

- [x] 22 by : but

- [x] 24 optical character recognition and machine translation : add wikipedia links

- [x] 26 existing language knowledge: please specify

- [x] 28  lesson goals : list format

- [x] 40 if you are comfortable at BASH : syntax

 - [x] BASH comes installed on Linux and Mac operating systems. The tutorial contains instructions for how Windows users can use an emulator to use BASH. : this is a bit unclear , please rephrase.

- [x] 46 please mention the source of the documents you are using 

- [x] 48 & 98 exercize :  exercise 

- [x] 55 compress the data such: compress the data in such a way

- [x] type written :  typewritten

- [x] 78 - 85 Tesseract : provide link of the tool and explain why you are using the tool. I think its better if you introduce the tool at the OCR section but its good to give a small pointer in advance 

- [x] 80  ImageMagick : provide link of the tool  

- [x] 69 instilation: Installation

- [x] 96 Translate Shell:  provide link of the tool 

- [x] 127 the below two lines: amend syntax

- [x] 129 I think this bit of code should be omitted

- [x] 131 text format

- [x] 149 one...two...three.. : I think it d be better if these sentences are in a list format

- [x] 189  if this were a larger work : syntax

Once you make these changes, I will then have a new look at it and try to find two reviewers. 
Please do let me know if there is anything unclear at this stage.

**Comment by akhlaghiandrew** [comment]
Thanks @amsichani! I have made the edits and have tried to incorporate your feedback on the intro and conclusion. Thank you for the help. Please let me know if there's anything else I can do.

**Comment by amsichani** [comment]
HI @akhlaghiandrew, thanks for these edits. I noticed there are a couple of edits still pending - it would be great if you could have another look at these. In the meantime  I'll start soliciting reviewers for the lesson. Please let me know if you have any questions about my suggestions or changes, and thank you for your patience.

**Comment by akhlaghiandrew** [comment]
@amsichani I had made the edits, but I didn't click the boxes consistently. Sorry about that. Won't happen again.

**Comment by amsichani** [comment]
Hi @akhlaghiandrew , I had another closer look to the lesson and there are couple of things I want to discuss with you before sending them to reviewers. 
By doing so, we are aiming to get up to speed, to facilitate reviewers' work (by allowing them to focus on the lesson's contents only) and to minimise the radical edits/changes you might be asked to do at a later point. 
So don't get me wrong here,  I think the lesson is really useful and I am trying to help make  the best version of it in order to meet as much as possible  Programming Historian's guidelines and users' needs.

- [x] it would be great if you could spend more time on the case study and examining the results. Without screenshots or detailed discussion of the outputs as you go, it feels sort of disjointed. Images and screenshots is something that is missing from the lesson, especially a lesson using images as primary data. A good example of this is the noise discussion. Put the screenshots in the text, I'd say, if you're discussing them. Is noise typical of all documents of a certain period? Some more than others?

 - [x] I wonder if you could use another case study from the same dataset to explore other possibilities within the pipeline/workflow you 've set up? Particularly since PH already has a few lessons related to OCR, I think the meat of the lesson here is from paragraphs 16 on. Maybe you can do more and explain more about the options available with translate shell?

- [x] it would be great to add more thoughts on how and why this particular workflow might be useful to others, beyond just serving as an example of the issues . Why might someone want to read it? What are they expected to learn from it? Are there places where it could be easily adapted? Where it couldn't? Perhaps add these thoughts at the conclusion.

 - [x]  the piece needs another proofreading  before we can send it out. Do also have a look at the edits I' ve suggested above -- not all of them have been addressed - eg 69 Windows Instillation: Installation.

Please do let me know if there is anything unclear or anything you want us to discuss further.

**Comment by akhlaghiandrew** [comment]
@amsichani I will do my best to incorporate these edits. I'm a little unclear on point 2 and 3. What do you mean by case study? Do you mean another document from the same collection? And what do you mean by useful to others? When you say "read it", do you mean read these documents or read the article itself?

Obviously these edits will take some time. Can I take a week or so to get back to you?

**Comment by amsichani** [comment]
hi @akhlaghiandrew , thanks for the additional edits. what I had in mind is if you can suggest other uses of translate shell& the workflow your are proposing, not necessary other documents of the collection, but mainly alternative & complementary applications of the tools you 're proposing (eg for a batch of documents, application only for a specific image's sections, post processing options etc). Mainly to show the reader that this is a tutorial that offers a solution to a problem, but its not an end in itself, as it proposes also a methodological approach. Finally, I think that the addition of some visuals will significantly help the lesson  to become more accessible and easy to follow.  

A week from now looks great ! Do let me know if there is anything else unclear.

**Comment by amsichani** [comment]
we are happy to have a number of members from the Portuguese team to shadow the editorial & peer review process  -- @joanacvp , @romulopredes , @tacianasene welcome on board!

**Comment by amsichani** [comment]
Hi @akhlaghiandrew, I noticed you have entered some edits at the lesson  -- could you please inform me here once you finish with the edits at your end so I can have another look at the lesson and move along with the peer review? cheers!

**Comment by akhlaghiandrew** [comment]
@amsichani I had hoped to be done by today, but my end of semester grading is taking longer than I wanted. I should be done by this weekend with all the edits.

**Comment by akhlaghiandrew** [comment]
@amsichani Edits are done! Where do you want me to upload my screenshots?

**Comment by amsichani** [comment]
Great @akhlaghiandrew ! Re the screenshots upload have a look here https://programminghistorian.org/en/author-guidelines  -- step 3. uploading images | data. Do let me know once everything is up. Thanks!

**Comment by akhlaghiandrew** [comment]
@amsichani Everything is now up. Please let me know if there's anything else.

**Comment by amsichani** [comment]
Hi @akhlaghiandrew, great. I ve amended the images' links (its a temporary solution, just to have everything up and running - we 'll fix this before publication). 
I am happy to see that you ve also edited the lesson and it is now a very interesting and useful resource. 
I am now going to  solicit peer reviewers for this lesson. You ll hear more from me in the next couple of days/weeks. Cheers!

**Comment by amsichani** [comment]
Our first editor for this lesson will be @cneud . Looking forward to your review!

**Comment by cneud** [comment]
Thank you @akhlaghiandrew for this submission. It encapsulates the complexity of OCR and MT into a suitable scope for digital humanities use. At first, I thought it may be too much to include OCR and MT in a single tutorial, but the way it is presented works for me and highlights the fact that OCR is often just a first stepping stone for working with digitized texts. I think it is also very helpful that there is good context about image quality and its implications on OCR/MT quality, despite the fact that image processing takes up a lot more space in the tutorial than the actual OCR. 

## Remarks, suggestions

Under **Acquire the data**, maybe mention that OCR is only suitable for detecting and recognizing printed/typewritten letters and not the handwritten annotations also present on the example pages (for which there are other solutions, e.g. Transkribus).

Under **OCR**: Tesseract is **one of the best** (there are other, competitive open source OCR engines, e.g. Calamari, OCRopus). Google no longer maintains Tesseract btw! Ray Smith (employed by Google) started it originally at HP and developed it further at Google, but currently maintenance is being done by community members rather than Ray/Google. Furthermore, even training Tesseract for calligraphy or handwritten text would likely not work, since there are other segmentation methods required too, for non-printed glyphs. Therefore maybe better mention "unique scripts like Blackletter asf.". 

Following on, in L76, one might want to explain that the param ``-l`` is for specifying the language to use for recognition. You might also want to mention that there are additional command line params (https://github.com/tesseract-ocr/tesseract/wiki#running-tesseract) e.g. to output different formats that also include structural tagging in addition to plain text (ALTO, hOCR).

Generally, I would suggest adding a link to the documentation for Tesseract (https://tesseract-ocr.github.io/).

## Spelling, phrasing
L28: learn how **to** make scripts
L34: The linked Programming Historian tutorial contains instructions for ~how~ Windows users, **who** can use an emulator to use BASH.
L36: Open **a** Terminal
L40: I selected these documents for two reason**s**
L40: One, the documents are high quality scans, but have ~errors~ **defects** common to many archival documents
L40: so we will be able to judge the ~fidelity~ **quality/accuracy** of our machine translations.
L45: That is, the **text lines in the** document should appear straight in the picture. 
L50: Mac Inst**a**llation
L53: On MacOS, the inst**a**llation requires two simple commands
L57: Windows Inst**a**llation
L61: OCR programs will only ~take~ **accept** image files (JPG, TIFF, PNG) **as input**
L65: Better use ``ppi`` (pixels-per-inch) as ``dpi`` (dots-per-inch) is only relevant to printing (cf. https://photographylife.com/dpi-vs-ppi)
L65: this ~line of commands~ **command** converts (it is a single command, despite multiple params ;)
L67: For example, they may be ~a~ skew or ~have~ uneven brightness.
L67: For an idea of other ImageMagick options that can ~help~ **improve** OCR **quality**
L70: [Tess~e~eract 4.1](https://github.com/tesseract-ocr/tesseract)
L70: it might be worth training your own OCR ~algorithm~ **model**
L70: "typewritten" instead of "type written"
L70: and ~correclty~ **correctly** identify imperfect letters
L74: Windows inst**a**llation
L76: Our output is a plain text file in ~English~ **Russian**.
L81: is a freeware program that allows you to access **machine translation tools like**
L82: The program allows you to access the API ~to these websites~ **of these tools**.
L82: For example, there is a limit of 5 **,** 000 characters per request
L82: You will need to experiment to find **out** which translation API works best for you and your text.
L95: and ~tranlsate~ **translate** our documents
L97: When wri~t~ting longer programs
L126: The first line creates a new ~variabel~ **variable**
L129: Three, the `sleep 1m` command ~stops~ **halts** the program 
L132: The third and final bloc**k** of code
L140: Add all three bloc**k**s 
L140: Once the file is saved, you need to make it ~an~ executable.
L145: The results for example one demonstrate how important the **quality of the** ~underlying~ **input** image is
L149: your ~first~ **initial** transcription and translation will **still contain** ~have~ errors
L149: Even though **the** OCR program correctly transcribed the period
L155: Another problem with the sentence ~is~ **are** hyphens
L157: it is safe to assume that ~all~ **any** "@"'s **appearing** in the document are **in fact** incorrectly ~identified as~ **recognized** "а"'s. 
L157:  or your text edit**or**'s  [..] function to make the **according** substitutions.
L167: Much like the other commands show**n** above
L167: and ~run them over every~ **apply them to other** document**s** you OCR.
L169: Look at the ~imporvement~ **improvement**
L169: a few edits can ~radically~ **substantially/dramatically** improve  
L177:  so that the lines of text are ~parralel~ **parallel** to the bottom of the document
L179: However those ~smartcropping~ **smart cropping** programs are significantly more complicated 
L179: Fortunately, ~smartcropping~ **smart cropping** ~is also probably unnecessary~ **my not be necessary**
L179:  you will find that **for the given input images**
L193:  will remove the specified amounts of pixels regardless of ~if~ **whether** there is text on them
L193:  on each ~picture~ **image** / it will also save over the original ~picture~ **image** (use consistent terms throughout the tutorial)
L193: To avoid ~saving over~ **overwriting** the 
L195: A final useful script will reduce noise in the image --> Finally, another section will be added to the script for the reduction of noise in the image
L195: This could be the result of problems with the ~copying~ **image capture** device 
L229: to create your own ~work flows~ **workflows**

**Comment by cneud** [comment]
@amsichani Here's my initial review, hope it helps! Let me know if you have any questions or remarks. I did not make any suggestions to the overall structure and scope, since I assume this is already aligned with other PH tutorials and you are probably much more aware than me about how well this blends in with other PH materials.

**Comment by akhlaghiandrew** [comment]
@cneud Thank you so much for the edits and remarks. I really appreciate all the work.

**Comment by amsichani** [comment]
Many thanks for the detailed review @cneud ! Really appreciated!
We are now having our second reviewer on board @hibernator11 -looking forward for your review as well! 
@akhlaghiandrew I would suggest to wait until the second review comes in , in order to update your lesson having a set of comments -- I will also then try to group them together to make things easier for you. I hope it makes sense!

**Comment by hibernator11** [comment]
Thank you @akhlaghiandrew for this submission. I agree with @cneud, this tutorial offers a clear overview regarding OCR and MT based on BASH tools.

Here's my initial review :) Please let me know if you have any question or doubt. I will not go into the structure of the tutorial since it has been already reviewed by a few of you. 

I like the appreciation in conclusions about using other programming languages. I would extend this part a little bit and even mention other tools like Jupyter Notebooks that can be useful to learn for digital humanities researchers since they are reproducible in a cloud environment.

I am not sure if tesseract is the best open-source tool. Instead, you could say that is the most popular tool in the community.

I will just add a few suggestions.

- [x] p1: In the introduction appears the word Bash, then you use BASH. Please, make the word consistent throughout the text.
- [x] p4: I selected these documents for two **reason** -> reasons
- [x] p7: But often we are stuck with images that have **signifcant** noise -> significant
- [x] p7: This is the first time that ImageMagick appears in the text. I would include an introduction to the tool and a link.
- [x] p8: Mac Instillation -> Installation (twice in the paragraph)
- [x] 9: Instillation
- [x] p12: It would be nice to introduce the concept DPI
- [x] 14: This lesson will use the OCR program Tesseract. **Tesseeract** 4.1 -> Tesseract
- [x] p15: Windows **instillation**
- [x] p16: Stop before "Our output is a plain text file in English"?
- [x] p17: Including links to platforms? Google Translate, Bing Translator, Yandex.Translate, and Apertium
- [x] p21: to preprocess, OCR, and **tranlsate**
- [x] p28: The first line creates a new **variabel**
- [x] p36: Could add an additional description to the image "The owl sentece in translated"
- [x] p44: Look at the **imporvement**
- [x] p53: There is a broken link to the image
- [x] p59: Please, rephrase "While the command line tools I have demonstrated here may not be of interest to you, there are likely command line tools that will interest you"

**Comment by amsichani** [comment]
Many thanks @hibernator11 for the prompt and really useful review ! Much appreciated!
@akhlaghiandrew as both reviews are quite detailed, I 'd avoid to rephrase them. Thus, I suggest that you move on and incorporate the reviewers' comments in your lesson (it might be useful to tick the corresponding box once you make a change). Once you are ready do let me know, I will have another look at the final version. Do let me know if there is anything unclear.

**Comment by akhlaghiandrew** [comment]
@amsichani I've made most of the changes. I will explain why I did not make three of them.
L65: Tesseract and Imagemagick specify DPI. While PPI may be more appropriate, I think it would be confusing.
L155: The subject is singular. The verb should be singular. 
P12: There is a link to the DPI wikipedia page. I think a longer explanation would be confusing.

**Comment by akhlaghiandrew** [comment]
@amsichani Any updates?

**Comment by amsichani** [comment]
hI @akhlaghiandrew -- sorry for the delay (summer holidays, sabbatical etc). I will soon have a closer look at the final version of the lesson and let you know about the next steps. Thanks for the collaboration !

**Comment by amsichani** [comment]
Hi @akhlaghiandrew , as I am now editing the lesson for publication I will need from you : 
- an one sentence short bio
- ORCHID number, if available
- an abstract:  a 1-3 sentence description of what you’ll learn in the lesson. Try to avoid technical vocabulary when possible, as these summaries can help scholars without technical knowledge to try out something new.

**Comment by akhlaghiandrew** [comment]
Hello @amsichani 
[intro.txt](https://github.com/programminghistorian/ph-submissions/files/5169338/intro.txt)

**Comment by amsichani** [comment]
thanks a lot @akhlaghiandrew ! A small issue is also about the filename of the lesson - instead of OCR_and_Machine_Translation.md needs to be OCR-and-Machine-Translation.md. For consistency reasons,  all the related files/folders need to follow this  (I checked the lesson's images folder and its OK). Could you please do this small change before we proceed? Thanks!

**Comment by akhlaghiandrew** [comment]
@amsichani I went ahead and changed everything. including the image files. Just for the sake of consistency.

**Comment by amsichani** [comment]
Great @akhlaghiandrew - many thanks!

**Comment by amsichani** [comment]
Fantastic - now we are ready to move to copyediting, and @svmelton will lead this process.

**Comment by akhlaghiandrew** [comment]
@svmelton Anything needed from my end?

**Comment by svmelton** [comment]
Not at this point, @akhlaghiandrew! FYI, I'm waiting to hear back about copyediting.

**Comment by svmelton** [comment]
Hi all! Just a quick update that the copyeditor is working on this lesson.

**Comment by svmelton** [comment]
Hi @akhlaghiandrew and @amsichani—copyedits are in and can be found [at this link](https://www.dropbox.com/scl/fi/3ojb03dvdzst00vskxyo1/lesson_ce.docx?dl=0&rlkey=6179rkpc1q7llh3i9nzl4jaco). When you've had a chance to incorporate edits into your draft, let me know and we'll move to publishing! Let me know if you have any questions.

**Comment by akhlaghiandrew** [comment]
Why is this being done in word? Should I send you an edited ,md file?
Andrew

**Comment by svmelton** [comment]
Yeah, unfortunately there’s not a good way to track changes in markdown (that I know of!), so most copyeditors opt to work in Word. If you could incorporate your changes in a markdown file, that would be great.

**Comment by akhlaghiandrew** [comment]
The copy editor made some content suggestions about the conclusion. I have
not discussed these with Anna-Maria and they run counter to some of the
suggestions of the reviewers.
I also think the suggestions for the first sentence make the sentence
worse. What should i do?
Andrew

**Comment by svmelton** [comment]
Hi Andrew,
You can certainly reject changes. And definitely feel free to reach out to @amsichani if there are proposed changes that you have questions about, especially if they seem to contradict earlier review comments!

**Comment by akhlaghiandrew** [comment]
Sarah,
I've made almost all the edits to the file @
https://github.com/programminghistorian/ph-submissions/blob/gh-pages/lessons/OCR-and-Machine-Translation.md
I did not make all the edits to the intro and conclusion, but did
incorporate some of them. Other than that, I included everything.
Please let me know if there's anything else I can do.
Best,
Andrew

**Comment by amsichani** [comment]
Hi @akhlaghiandrew , many thanks for your work on incorporating the copy editor's suggestions. If thats OK with you, I will have a closer look at the final version you 've submitted on Wednesday/Thursday , and I will get back to you. After this, we are ready for publication, as everything else is now in @svmelton 's hands. Many thanks again for the smooth collaboration!

**Comment by svmelton** [comment]
Thanks @akhlaghiandrew! @amsichani, just let me know once you've had a chance to review everything, and we'll get the piece published!

**Comment by amsichani** [comment]
Hi @akhlaghiandrew, I had a closer look at the edited version of the lesson. I think it now looks really improved. I have a couple of minor comments, mainly discussing several of the copy editor's suggestions, that I think it would be good to reassess and potentially follow 

- [copy editor's comment A1] : Consider again on the opening phrase of the lesson -- actually, I think the word 'article' is quite problematic. I think the proofeader's suggestion “This tutorial will cover the basics of using optical character recognition (OCR), digital technique that can greatly benefit humanities research” is a a good one as it captures the lesson's identity and goal.
-  [copy editor's comment A3] : consider the transition phrase proposed- it makes reading much easier
- "Command line tools, like simple Bash scripts, offer us solutions to these common problems and can make organizing and editing image files much easier": consider suggestion proposed.
- Installing ImageMagick: follow suggestion for as this heading facilitates the structure of the section
- correct Tesseeract to Tessaract (hyperlinked text)
- Tesseract identified two “а” ’s as “@” ’s : consider suggestion proposed , its more accurate from a grammatical & syntactic point of view
- [copy editor's comment A8] sed  In code font : follow suggestion
- (after comment A12 ) "Finally, we can add another section of code to reduce ": consider suggestion 
- [copy editor's comment A13]: Code font : follow suggestion
- (Conclusion) "For example, knowing the importance of image quality will help you chose how to capture images of documents. Further, knowing the limitations of ImageMagick's crop command will emphasize the importance of taking uniform pictures of documents. " : I am not sure whether this paragraph here helps the overall lesson's conclusion. I personally feel you need to conclude on a more general note , so I would omit this bit.

Once you have reviewed the comments above, do let me know so we can proceed with the publication of the lesson. Many thanks for your work and collaboration so far!

**Comment by akhlaghiandrew** [comment]
@amsichani 
I've reviewed and made the changes. 
Thanks for all your help!

**Comment by amsichani** [comment]
Hi all, the lesson is now live https://programminghistorian.org/en/lessons/OCR-and-Machine-Translation ! Many thanks @akhlaghiandrew for the submission and your work on it and also huge thanks to @cneud and @hibernator11 for their useful reviews - they helped to make this lesson even more accessible. Also thanks to @svmelton for her smooth handling of the copyediting and the publication . Great work!

**Comment by akhlaghiandrew** [comment]
Thank you. This has been a really fun and rewarding experience. I'm really proud of the final product and thank all of you for your hard work and help. @cneud , @hibernator11 , @amsichani , @amsichani

**Comment by hibernator11** [comment]
Well done!! It looks really good. It,s been a pleasure for me to contribute to this lesson. @akhlaghiandrew , @cneud , @amsichani

**Comment by cneud** [comment]
Congratulations and well done @akhlaghiandrew, @amsichani, @hibernator11! It was a pleasure to be able to contribute.
