### ISSUE TITLE
Proposta de tradução: Trabalhando com arquivos de texto em Python

### ISSUE THREAD

**Issue by daniellesanchesDH** [programminghistorian/ph-submissions#317]
O Programming Historian em português recebeu a seguinte proposta de tradução da lição 'Trabalhando com arquivos de texto em Python' pela @aracele . 

Para promover uma publicação rápida desta lição traduzida, eu @daniellesanchesDH  irei procurar uma revisão da mesma junto de dois revisores o mais breve possível.

O contato editorial principal desta lição é @daniellesanchesDH . Se houver alguma preocupação dos tradutores, eles podem entrar em contato com o mediador do PH em português (Luís Ferla).

**Comment by rsouza** [comment]
Prezados, apos leitura cuidadosa da licao, nao encontrei nada que a desabonasse. Esta muito bem escrita e informativa. Parabens!
Sugeriria, talvez, que trocassem a referencia ao final que aponta para um tutorial de Python 2.6, para alguma equivalente que apontasse para um tutorial em Python 3.X

**Comment by DanielAlvesLABDH** [comment]
@aracele quando iniciar as alterações sugeridas pelos dois revisores (ainda falta um), por favor, tenha em conta que as lições sobre Python têm estado a ser revistas pelos colegas da equipe inglesa, pelo que vale a pena acompanhar estes issues para perceber se temos de fazer ajustes na versão final: https://github.com/programminghistorian/jekyll/issues/1885 e https://github.com/programminghistorian/jekyll/issues/1777

**Comment by DanielAlvesLABDH** [comment]
@walshbr you mention in another issue that we should pay attention to changes that the team was planning or doing already to the Python lessons. I can't find that note and that issue. Could you link to it here, please? Thanks

**Comment by walshbr** [comment]
https://github.com/programminghistorian/jekyll/pull/1997 - this is the one. It doesn't fully close things out for the Python files. In general, though I think it's fine to move ahead with translating the files as they are. You might just check, for those files at least, that when you get ready to finalize them that you're sure you're up to date with things. There are a number of places in GitHub to see the history of changes. Here are some screenshots. If you are just in a particular folder you can see at the right an indicator of when the most recent change was made to a particular file (see the Python file in question was updated a few days ago here)

![Screen Shot 2021-02-05 at 11 15 37 AM](https://user-images.githubusercontent.com/2334220/107059299-a164cc80-67a3-11eb-85ff-3db8e591eeca.png)

And if you are looking at a particular file you can also click on the "history" button at the right to see what the most recent change was. 
![Screen Shot 2021-02-05 at 11 15 43 AM](https://user-images.githubusercontent.com/2334220/107059307-a32e9000-67a3-11eb-85a9-b0f8ecb6abc5.png)

The history button takes you to a list of the changes (the commits, in github's vocabulary):

![Screen Shot 2021-02-05 at 11 18 03 AM](https://user-images.githubusercontent.com/2334220/107059530-e12bb400-67a3-11eb-9bb4-9bdc8a8c9d88.png)

And clicking on the seven digit/character link in the second to righthand column will show you the individual changes that were made at that time. So for you and for this, I'd say just look when you're finalizing to make sure the files haven't been updated since the translation was undertaken. And, if they were changed, that last step where you click on the commit link can help narrow down what needs to be updated. But feel free to let me know if you have questions.

**Comment by DanielAlvesLABDH** [comment]
Great explanation and help @walshbr! Many thanks!

**Comment by aracele** [comment]
> @aracele quando iniciar as alterações sugeridas pelos dois revisores (ainda falta um), por favor, tenha em conta que as lições sobre Python têm estado a ser revistas pelos colegas da equipe inglesa, pelo que vale a pena acompanhar estes issues para perceber se temos de fazer ajustes na versão final: [programminghistorian/jekyll#1885](https://github.com/programminghistorian/jekyll/issues/1885) e [programminghistorian/jekyll#1777](https://github.com/programminghistorian/jekyll/issues/1777)

Entendido @DanielAlvesLABDH ! Obrigada! :)

**Comment by daniellesanchesDH** [comment]
@bgmartins esta lição também necessita de revisão. Obrigada.

**Comment by bgmartins** [comment]
Olá @daniellesanchesDH 

No caso desta lição, fiz já uma revisão sobre o texto e fiz um commit com as propostas de alteração.
Podes verificar?

**Comment by daniellesanchesDH** [comment]
@bgmartins verificado, obrigada! 

@aracele consegues incorporar as alterações propostas pelo @bgmartins ? Precisa de alguma ajuda com isso?

**Comment by aracele** [comment]
Olá @daniellesanchesDH assim que for possível faço isso. Obrigada!

**Comment by aracele** [comment]
Feito @daniellesanchesDH ! Obrigada pela paciência! Obrigada pela revisão @bgmartins e @rsouza !

**Comment by daniellesanchesDH** [comment]
Obrigada @aracele ! Obrigada a todos pela participação!

**Comment by daniellesanchesDH** [comment]
@DanielAlvesLABDH revisão terminada! Pronta para publicação.

**Comment by DanielAlvesLABDH** [comment]
Obrigado @daniellesanchesDH . Estive a rever e é necessário introduzir ligeiras correcções. Deixo abaixo as indicações.
Para manter a coerência da tradução, o nome do ficheiro deve ser alterado para "manipulando-ficheiros-texto.md"
No cabeçalho YAML do ficheiro (linhas 1 a 26) têm de ser incluídas as linhas relativas à tradução, edição da tradução e revisão da tradução. Veja esta lição para comparação: https://github.com/programminghistorian/jekyll/blob/gh-pages/pt/licoes/preservar-os-seus-dados-de-investigacao.md
linha 25 - O DOI tem de ser apagado. No final da revisão será solicitado um novo DOI
linha 17 - Apagar a vírgula no texto "ler, e gravar".
linha 47 - Os links "[Mac Installation][], [Windows Installation][], ou [Linux Installation][])" devem ser alterados para português e com o link a apontar para as versões em português dessas páginas que já foram traduzidas
linha 105 - Apagar vírgula no texto "(gravar), e `close`"
linha 106 - Apagar vírgula no texto ""fingir de morto," e"
linha 112 - No texto "O *parâmetro wb*" só "wb" deve ficar em itálico
linha 116 - Apagar "em" no texto "consulte a seção em"
linhas 138 e 139 - Eliminar quebra de linha
linhas 143 a 145 - Eliminar quebra de linha
linha 155 - Apagar vírgula no texto "com sabor de carne, e duas vezes"
linha 163 - Apagar vírgula no texto "anteriormente, e anexará"

**Comment by DanielAlvesLABDH** [comment]
Olá @aracele e @daniellesanchesDH! Aracele, você consegue incorporar as sugestões que eu fiz na mensagem anterior? É pouca coisa e é só o que nos falta para concluir esta tradução. Obrigado!

**Comment by aracele** [comment]
> Olá @aracele e @daniellesanchesDH! Aracele, você consegue incorporar as sugestões que eu fiz na mensagem anterior? É pouca coisa e é só o que nos falta para concluir esta tradução. Obrigado!

Feito! Obrigada! :)

**Comment by DanielAlvesLABDH** [comment]
Obrigado @aracele! Vou agora fazer uma última verificação, pedir o DOI e publicar. Abraço

**Comment by DanielAlvesLABDH** [comment]
Publicada @daniellesanchesDH ! Podemos encerrar! Obrigado

**Comment by daniellesanchesDH** [comment]
Obrigada a todos!!
