### ISSUE TITLE
Tradução da lição 'Limpar dados com o OpenRefine'

### ISSUE THREAD

**Issue by joanacvp** [programminghistorian/ph-submissions#410]
O Programming Historian em português recebeu a seguinte proposta de tradução da lição 'Limpar dados com o OpenRefine' por @FranciscoNabais. 

A lição a traduzir está no link: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/esbocos/traducoes/limpar-dados-openrefine.md

Esta lição está agora em revisão e pode ser lida em: http://programminghistorian.github.io/ph-submissions/pt/esbocos/traducoes/limpar-dados-openrefine

As imagens no link: https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/cleaning-data-with-openrefine

A editora para esta tradução será @aracele.

Para promover uma publicação rápida desta lição traduzida, irei procurar uma revisão da mesma junto de dois revisores o mais breve possível.

Se houver alguma preocupação do tradutor, ele pode entrar em contato com o mediador do PH em português (Luís Ferla).

**Comment by aracele** [comment]
Olá @joanacvp! Alterei meu nome aqui e me coloquei também como _assingee_ desta issue. Está correto?

**Comment by joanacvp** [comment]
> Olá @joanacvp! Alterei meu nome aqui e me coloquei também como _assingee_ desta issue. Está correto?

Olá, boa tarde,
Muito obrigada @aracele ! Está correcto

**Comment by anisa-hawes** [comment]
Hello all,

Please note that as part of a reorganisation of the /pt directory, this lesson's .md file has been moved to a new location within our Submissions Repository.

It is now found here: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/esbocos/traducoes/limpar-dados-openrefine.md

A consequence is that this lesson's preview link has changed. It is now: http://programminghistorian.github.io/ph-submissions/pt/esbocos/traducoes/limpar-dados-openrefine

Please let me know if you encounter any difficulties or have any questions.
Very best, Anisa

--

I am confused because I note that there are two Issues with the same title: Tradução da lição 'Limpar dados com o OpenRefine'. [This Issue #410](https://github.com/programminghistorian/ph-submissions/issues/410#top) and also #427.

**Comment by DanielAlvesLABDH** [comment]
This is a duplication. The translation is being revised in https://github.com/programminghistorian/ph-submissions/issues/427. I will close this
