### ISSUE TITLE
Lesson proposal: Interrogating a National Narrative with Recurrent Neural Networks (PH/JISC/TNA)

### ISSUE THREAD

**Issue by tiagosousagarcia** [programminghistorian/ph-submissions#418]
The Programming Historian has received the following proposal for a lesson on 'Interrogating a National Narrative with Recurrent Neural Networks' by @ChantalMB. The proposed learning outcomes of the lesson are:
     
- Understanding how general-purpose neural networks like GPT-2 can be applied to the distant study of large corpora in a way that can help guide further close readings, while also acknowledging the technical and ethical flaws that come with using large-scale language models
- Creating a workflow for performing large scale computational analysis that works for the individual learner through advancing their technical knowledge on topics of machine learning software and hardware required to perform these kinds of tasks
 	
In order to promote speedy publication of this important topic, we have agreed to a submission date of no later than 24/01/2022. The author(s) agree to contact the editor in advance if they need to revise the deadline.
 
If the lesson is not submitted by 24/01/2022, the editor will attempt to contact the author(s). If they do not receive an update, this ticket will be closed. The ticket can be reopened at a future date at the request of the author(s).
 
The main editorial contact for this lesson is @tiagosousagarcia.

Our dedicated Ombudsperson is (Ian Milligan - http://programminghistorian.org/en/project-team). Please feel free to contact him at any time if you have concerns that you would like addressed by an impartial observer. Contacting the ombudsperson will have no impact on the outcome of any peer review.

**Comment by drjwbaker** [comment]
@svmelton and I discussed potential editors for this article. Sarah will seek an editor from the EN team when the article arrives. I note that @ChantalMB has emailed reporting some technical issue completing submission.

**Comment by drjwbaker** [comment]
This lesson has now been submitted and staged here https://programminghistorian.github.io/ph-submissions/en/lessons/interrogating-national-narrative-gpt and is ready for technical review prior to peer review. Many thanks to @ChantalMB for submitting on time!

**Comment by tiagosousagarcia** [comment]
The link for the staged submission has been updated and is now here: https://programminghistorian.github.io/ph-submissions/en/drafts/originals/interrogating-national-narrative-gpt

I'm starting the technical review now, will come back with any comments, corrections and suggestions shortly

**Comment by tiagosousagarcia** [comment]
@ChantalMB, congratulations on an excellent tutorial -- this is a challenging and exciting topic (and something very close to my current work), and you've tackled it beautifully.

Apologies for the delay in moving your article forward -- there were a few personal reasons that kept me away from this for a while.

I've made an initial technical review 757f056, making small changes as I went along. A summary of these are:

# Changes made
- l. 30 -- changed single to double quotation marks (consistency) (and in other places, silently)
- l. 30 -- added wiki link to machine learning
- l. 30 -- added wiki link to artificial intelligence
- l. 30 -- ie -> i.e.
- l. 32 -- changed single to double quotation marks (consistency)
- l. 36 -- "As the first half implies, " -> deleted (clarity)
- l. 36 -- changed single to double quotation marks (consistency)
- l. 38 -- "official" -> "officially"
- l. 60 -- "ex" -> "e.g."
- l. 64 -- added wiki link to multi-core processor
- l. 68 -- "propriety" -> "proprietary"
- l. 85 -- added link to conda enviroment
- l. 183 -- "outline" -> "outlines"
- l. 319 -- capitalised and italicised PH

Additionally, I would also suggest you consider the following before we send your article for peer-review:

# Suggestions

- l. 42 -- add a local copy of the dataset to PH (can be done now, if no further changes to the dataset)
- l. 42 -- add references to other PH tutorials on relevant methods (i.e., web-scraping, data cleaning, for example)
- l. 44 -- explain what is meant by 'prefix functionality'
- l. 46 -- requirements should probably appear earlier in the lesson (after overview?)
- l. 52 -- "you may use an online service that offers cloud-based GPU computing" -- add a note to explain that a few examples will be discussed in more detail in a section below
- ll. 85-95 -- should the virtual environment have a more descriptive name than "gpt2"? I.e., users who dabbled before (or may wish to dabble again), would benefit from a clearer label
- l. 155 -- add link to more documentation on GPT-2's different options
- ll. 185-188 -- add a few notes explaining why you chose those specific default values, more detail on units (i.e., are they all in steps?), and more detail on 'learning_rate'
- l. 197 -- Google Collab took 37 minutes for me; I wonder whether it would be worth it being a little more general here (i.e., execution times will vary), and just offer a minimum time (i.e., at least 20 min)
- l. 258 -- link to example output text is missing
- ll. 252-302 -- really like this section. Presents a good example of how to use a generative language model to interrogate a media narrative. A few more things that I would like to see addressed here would be a rough hit rate for useful generated text (i.e., how many generations until something interesting came along) and your process to determine what makes a particular generation interesting. I understand that this is a thorny and complex issue that falls slightly outside of the scope of the article, but it might be useful to acknowledge some of these complexities here. Another thing that could be addressed here (or elsewhere), is hints at other scholarly uses for AI-generated text.
- ll. 303-322 -- another excellent section. A couple of notes here: 1) it might be useful to point towards other text-gen AIs, some of which attempt to at least address some of the concerns around OpenAIs practices and base model (Eleuther, for example) 2) The last paragraph (l. 321) reads more like a conclusion rather than an ethical discussion. I would probably separate it and expand it slightly with this in mind.

Thank you for all your hard work!

**Comment by drjwbaker** [comment]
@ChantalMB Would you be able to get these small changes done in the next couple of weeks? If so, that'll give us some time to assign an editor (pinging @svmelton) before getting it out to peer review.

**Comment by svmelton** [comment]
Thanks, @drjwbaker! @jrladd will serve as an editor for this piece.

**Comment by ChantalMB** [comment]
Thanks @tiagosousagarcia for the initial technical review! @drjwbaker I should be able to fully review + get these changes done over the course of next week!

**Comment by anisa-hawes** [comment]
(I am co-assigning myself here so that I can shadow the editorial process).

**Comment by drjwbaker** [comment]
@jrladd so pleased to have you as editor on this. Note that this article is part of a [special series](https://programminghistorian.org/posts/articles-selected-ph-jisc-tna) for which we have funding. As a rresult @tiagosousagarcia and I will be offering additional support. For example, in addition to doing the technical edit, Tiago has identified potential peer reviewers. So do write to us https://programminghistorian.org/en/project-team when you are ready!

**Comment by ChantalMB** [comment]
@tiagosousagarcia (or anyone who may have the answer) In adding in references to other PH tutorials, I've discovered that the ["Intro to Beautiful Soup" tutorial](http://programminghistorian.org/en/lessons/retired/intro-to-beautiful-soup) has been retired. Is it acceptable to link a retired tutorial? This is actually the tutorial I used to learn webscraping with python, therefore it is the most accurate in terms of what I'm mentioning in my tutorial!

**Comment by tiagosousagarcia** [comment]
@ChantalMB -- in principle, I would avoid linking to retired tutorials. However, taking into account two things 1) The lesson was retired because the example used was no longer available, rather than because the technology itself has been superseded, and 2) I don't **think** (I may be wrong) we have another entry level beautiful soup tutorial available, it might be ok in this case (as long as the link is contextualised). I may be very wrong though -- @drjwbaker, @jrladd, do we have a strict policy about this?

**Comment by drjwbaker** [comment]
If we are sending people to a retired lesson to do it, we shouldn't do that. If it is merely to reference a point there or to understand a principle, it is fine. Retired articles are retired because they no longer work (and can no longer be made to work) rather than because there is anything terrible about what they were trying to achieve when active.

**Comment by tiagosousagarcia** [comment]
Hi @ChantalMB -- I wonder if we could get a sense of when you expect to have these revisions ready?

**Comment by ChantalMB** [comment]
@tiagosousagarcia Revised tutorial is ready now, actually! Just wrapped up everything today-- apologies for the delay, got knocked out by cold for a week!

I also never got notified by GitHub that you and @drjwbaker had responded to my question, so thank you! I ended up linking the Beautiful Soup tutorial, but then also added a link to the ["Automated Downloading with Wget" tutorial](http://programminghistorian.org/en/lessons/automated-downloading-with-wget) as an alternative resource for specific instruction since wget can also be used to download web pages.

I did quite a large edit re: the suggestions for lines 185-188 because to expand on learning rate meant that I also had to explain gradient descent, so now my tutorial includes diagrams. Should I be sending the revised article + attached images by email or attached to a comment in this ticket?

Similarly, you stated that a local copy of my data could be made; if possible, I'd like to do that for the training data and also the output text (the missing link at line 258). 

Thanks for your help in advance!

**Comment by tiagosousagarcia** [comment]
Great news @ChantalMB! Hope you are feeling better now. The easiest option is probably to send me the corrected md + additional files via email, I'll add them here and link the commit to the discussion. You can also do the changes via a pull request, but still need to send me the additional files separately.

**Comment by ChantalMB** [comment]
@tiagosousagarcia Just sent everything your way via email!

**Comment by tiagosousagarcia** [comment]
@programminghistorian/technical-team or @anisa-hawes, I wonder if anyone could give me a hand here: since the location of the drafts has been changed, it seems that the link for local datasets is broken in the preview -- is there any trick to referencing it that I'm missing? Currently I have it as `/assets/[LESSON-SLUG]/[FILE-NAME].EXT` -- I know other lessons also suffer from this problem (at least #416)

**Comment by anisa-hawes** [comment]
Hello @tiagosousagarcia. Hmmm. This is strange... Let me take a look... When we made changes to the directories where the lesson .md files are saved, we didn't make any changes to the images or assets directories. The URL format should indeed be:

/assets/lesson-slug-here/asset-file-name.ext

**Comment by anisa-hawes** [comment]
Ah, so when the lesson is moved over to Jekyll for publication, we update any /assets or other internal links so that they are 'relative' links. Until then, we need to use full links, i.e., <https://github.com/programminghistorian/ph-submissions/blob/gh-pages/assets/interrogating-national-narrative-gpt/articles.txt>.

**Comment by jrladd** [comment]
Thanks so much for these revisions, @ChantalMB. Just a quick note to officially introduce myself--I'm glad to be working with you all on this! We've reached out to potential reviewers, and once we know more I'll be back in touch about next steps.

**Comment by jrladd** [comment]
Thanks very much for your review, @lorellav! Just so you know, @ChantalMB, our typical policy is to wait for both reviews before starting revisions. So you can check out the review (#473) for now, and I'll be back in touch once there's a second review in.

**Comment by jrladd** [comment]
Hi @lorellav and @ChantalMB! Just to keep everything in one place, I'm copying @lorellav's review here. I'm also closing the other issue, and once we're ready to discuss this and the next review, that can all happen on the same thread. 

> Thanks for the opportunity to review this tutorial, which I found topical and well-explained. Please find here below my comments and very few suggestions for improvement. 
> 
> The author addresses a consistent model reader throughout the lesson, which ranges from absolute beginner to advanced beginner, not just in using GPL but in coding with Python and using the cmd line. While this is certainly helpful, I think in reality it is unlikely that absolute beginners would use this tutorial, for example being able to create a virtual env, or manage comfortably the different parameters, etc. My suggestion would be to choose a more intermediate model user to avoid frustrating beginners and absolute beginners and in general to keep the tutorial more honest.  
> The author does a good job explaining concepts and terms, however, a few notions are taken for granted (e.g., language models) and they are not really explained. Although many people may be more or less familiar with the notion of what a language model is, I believe many of the assumptions that go in the making of these models remain often unclear and they are in fact overshadowed by the idea that because these models are truly huge, they must be very representative and therefore, very reliable. I appreciated the ethical considerations section which indeed highlights the limitations of this methodology and these models, including the biases baked in these models. I think however that the section would greatly benefit from including some further details about implications particularly for historians or researchers working with historical texts/humanities. For example, what was the original intentions behind the creation of these models? What are the risks of using them for humanistic enquiry? 
> The data section could be expanded a bit more, particularly because the author hints at the possibility to use own data by following the tutorial. I did use the tutorial with my own data, and here's what I found:
> - As it is, the model expects one .txt file. This means that those who have data in a different format need to prepare their data to fit this format. This may not necessarily be a problem for a python user who has worked with language data before, but this consideration is somewhat assumed. My suggestion is to include a few lines explaining this clearly, and point to resources (even in PH) that could help users get their data ready as the model expects it.
> - I used both google collab and jupyter as both options are given to the user. Mounting a drive and access data and files in collab is not super intuitive and requires the user to find additional/external resources, including tutorials and forums to find out how to do it. Perhaps a word of warning could be included here.
> -in jupyter I found the process of setting up the env and downloading the packages very lengthy, again a word of warning might help the user allocate enough time to run the tutorial. 
> - I tried to tweak the parameters to achieve better performance. When changing the n_steps and batch_size I ran into an index problem. This is not at all mentioned in the tutorial, as the possibility to change the parameters is described as unproblematic. So perhaps mentioning that each change may run in errors and explain why/how to solve them (like the memory problem) could help.
> - FYI, in Jupyter, even after installing all the packages successfully, I got the error: CUDA is not installed. 
> 
> In terms of payoff, the tutorial uses GPT-2 for language production, but it could be helpful to at least mention all the other tasks it is used for (for instance translation, as GPT-2 is essentially trained on English, a major problem for digital language injustice).
> As per the logical sequence of steps, I think mentioning earlier in the tutorial that GPT-Neo can also be an option would be beneficial to the user, perhaps with a reference to the ethical section.
> 
> Finally, in reference to the environmental impact of training models, it could be helpful to refer the reader to recent work done towards reducing it (see for instance https://aclanthology.org/2021.findings-acl.74/) because currently the impression is that such big cost for the environment is inevitable. 
> 
> Thanks again for your important contribution and I hope you'll find my suggestions helpful.

**Comment by tiagosousagarcia** [comment]
@kmcdono2 agreed to be the second reviewer for this tutorial, we can expect her comments by the 13th of May. Thank you everyone!

**Comment by kmcdono2** [comment]
Hello everyone! Looking forward to reviewing the lesson shortly!

**Comment by kmcdono2** [comment]
Quick update from me: should have this done Tuesday, May 17!

**Comment by tiagosousagarcia** [comment]
Thank you @kmcdono2, and thank you for updating us!

**Comment by jrladd** [comment]
Hi @ChantalMB, @lorellav, and everyone! Just a quick note that I'll be away from email/internet until June 14, but you'll all be in very good hands until then. Feel free to continue to leave comments/questions here in the meantime.

**Comment by kmcdono2** [comment]
Hi all - apologies for the delay. Here is my review!

## Audience
### Does the author address a consistent model reader throughout the lesson?
- Yes

### Are some concepts or steps over-explained while other are under-explained?
 - Worth explaining language bias of the model (e.g. Bender rule) at top of lesson, not just in para 79.
- Explain more concretely in para 9 what it means to ask the model questions. E.g. input is X, output is Y.
- Fix this sentence in para 9: "By doing this, we can use this “computationally creative” technique can be used to uncover potential trends in the media coverage of this historical turning point, and consider further how this may be applied to other forms of historical research based on large-scale text-based data."
- Fix this sentence in para 38: "To calculate the minimum number of steps your model should have divided the number of tokens in your dataset by 1024" (I assume it should be "divide" and not "divided".)
- Fix verb in this sentence in para 75 - "As exemplified in this analysis, when studying the generated text, seek points of repetition among responses to the same prompt– why might these be the points which the model had clung to?"


### Does the audience seem to match at least vaguely with other Programming Historian lessons? How is it new?
- Yes

## Getting Ready
### What software / programming languages are required?
- Python/Jupyter notebooks.

- Para 18: Worth explaining to people that if they already have ```conda```/Anaconda, they don't *also* need to install ```miniconda```.
- Worth also reminding people to update these packages if it has been a while since they used them.

### What prerequisite skills are needed?
- Basic python, notebook skills, understanding virtual environments.

### What familiarity or experience is needed?


### What data are needed? Is the dataset readily available?
- txt data is available via Github as .txt file.


## Skimmability
### Are there clearly defined learning objectives or sets of skills to be learned listed near the top of the lesson?

- I suggest breaking down the first paragraph in the Overview into more digestable text accompanied by a list of basic learning objectives. Some of the sentences are very dense!
- I would say that a basic objective of this lesson is building trust in predicted results among historians. This is not to be underestimated! See my comments below about needing to frame this a bit more, to help the lesson user along in being convinced that generated text is indeed useful.

### Are there useful secondary skills to be gained / practiced from the lesson?
- Using virtual environments, using jupyter notebooks, using kaggle/colab

### Do screenshots and other diagrams illustrate crucial steps / points of the lesson?
- Screenshots/instructions for how to determine if the code can be run locally would be helpful for people new to working with large language models (circa para 14).

### Do sections and section headings provide clear signage to the reader?
- Add subheading for the Gradient Descent Algorithm explanation (beginning para 42)

## Payoff
### Does the tutorial suggest why the explained tools or techniques are useful in a general way?
- It would be a good idea to introduce ```aitextgen```: e.g. who made it, why, and what are alternatives. Basically, tell people about the tool that is the basis of the lesson a bit more. At the very least, include a link to the library (https://github.com/minimaxir/aitextgen).
- More generally, I think there is scope in the beginning of the lesson to define "computationally creative" and provide some references to work that uses methods like these. E.g. at least cite https://computationalcreativity.net/home/ to point people to what the phrase is describing.
- Furthermore, in the "Using Generated Text as an Interrogative Tool" section, I think there needs to be a subsection that sets up *why* generated text is an ethical/meaningful part of a historian's tooklit. In this section there are a lot of fascinating references to how we can examine the data, but it assumes the reader is on board with the idea that "for historical inquiry [it] is not necessarily just how coherent the outputted text is, but its ability to create patterns from the inputted text that we as humans may be incapable of detecting...". So effectively, I'm asking the authors to prepare the lesson user to get on board with the idea that what the model produces is useful for historical research. (I'm not arguing that it isn't, just that it would be really useful for this to not be taken as a given. While there is some discussion of this embedded in para 84, I feel this should be foregrounded and more extensive. The goal of para 84 is to get the reader to think about the perils of the potential for abuse using GPT-2, but there is a broader problem of utility when historians tend to be interested in things people actually said.
- Finally, there are parts of the same section ("Using Generated Text as an Interrogative Tool") that ask the reader to be on board with the idea that the machine is being "convincing", "insightful", etc. I would suggest that the authors explain why they are using verbs like this and what the implications are in terms of how we rely on these results to think about a collection of text.



### Does the tutorial suggest how a reader could apply the concepts (if not concrete steps) of the lesson to their own work?
- Yes, though there could be more detail on the best way to prepare data. Para 8 mentions "it is important to perform some amount of cleaning so that your output is not hindered by stray stylings", and the earlier details in the para point to PH lessons for such tasks, but there isn't actually a clear statement about removing any extraneous tags, html, etc. in structured data. I would be as clear as possible about this and clarify that there should be 1 input file that concatenates text from many documents, not 1 directory with 1 "document" per file.

## Workflow
### Should a long lesson be divided into smaller lessons?
- No, the length is fine.

### Are there logical stopping points throughout the lesson?
- Not really, because the actual code is quite short. It's fine as is.

### If datasets are required, are they available to download at various points throughout the lesson (or different versions of them as the tutorial may require)?
- Yes

## Sustainability
### Are all software versions and dependencies listed in the submission? Are these assets the most recent versions? If the lesson uses older software versions, does the author note why?
- No, this could be improved. In particular, how sustainable is https://github.com/minimaxir/aitextgen?

### If you have expertise in the specific methodology or tool(s) for the lesson, is the methodology generally up-to-date?
- Perhaps worth engaging with/citing https://www.amacad.org/publication/non-human-words-gpt-3-philosophical-laboratory
- The discussion of language models and ethics at the end is great.
- See comment about adding reference in para 85.


### What are the data sources for the submission? Are they included in a way that does not heavily on third-party hosting?
- Input data can continue to be made available on Github (22MB file).

### What kinds of other external links does the submission use?
- Wikidata for definitions, or other explanatory articles such as content from Towards Data Science

### Are these current or are there other, more recent or appropriate, resources that could be linked to?
- Add links/references to "computational creativity" community/scholarship. It's a bit weird that this phrase is in quotations, but there is nothing in the lesson to situate it in the scholarship.
- Add references to scholarship on semantic change and issues with using modern language models on historical text (para 85)


## Integration
### Does the lesson build upon an existing lesson and explain how?
- No, but I imagine it might tie into other JISC lessons that are currently in the review pipeline.

### Does the lesson tie into existing lessons and have appropriate links?
- Yes: the Jupyter Notebook, Python Intro & Install, RegeX, Wget

**Comment by tiagosousagarcia** [comment]
Many thanks for the review @kmcdono2!

@ChantalMB, as you will have seen above, @jrladd will be off grid for a couple of weeks. Our policy is for the managing editor to summarise and guide the author on what the next steps will be, so I would hold off on any major changes until @jrladd is back and has had a chance to digest the reviews.

However, in the meantime, there are a few line-level edits that both reviewers suggested that you could have a look at. Thanks again to all!

**Comment by ChantalMB** [comment]
Thanks for the ping @tiagosousagarcia, will revise those small edits in the meantime. And thanks to all the reviewers for your thoughtful feedback, it will be immensely helpful in the process of improving and finalizing this tutorial 🎉

**Comment by jrladd** [comment]
Thanks everyone for your patience on this, and thanks @lorellav and @kmcdono2 for these excellent and thorough reviews! I appreciate the lively engagement, and feel free to use this thread to engage one another in conversation about any of the points. I'm happy to answer any questions as well. 

A shared concern I see in both reviews has to do with the framing of the piece, specifically w/r/t the relevance of RNNs to historians and historical research—this seems to me a very good thing to expand on. Alongside this, I think the suggestion of clearer signposting and a list of learning objectives/goals would be especially helpful, particularly keeping in mind what a reader who wanted to use their own data might need.

The suggestions for small edits (which you may have already started on), including a few new citations, technical notes, and line edits all seem straightforward, but I'm happy to answer questions about these as well.

We usually give about four weeks for this next round of revisions. @ChantalMB, would roughly July 15 work as a deadline? And feel free to continue the conversation here as you work. Thanks again, all!

**Comment by ChantalMB** [comment]
Thank you for the summary @jrladd -- July 15th should work for me as a deadline!

**Comment by ChantalMB** [comment]
@jrladd Just an update on my edits-- I had to step away from working on this tutorial for about a week due to some family matters which, while fortunately not dire, did require the bulk of my time. Currently playing catch up and am aiming to dedicate a day this weekend or early next week to complete revisions related to the final section of the tutorial!

**Comment by jrladd** [comment]
Thanks for checking in, @ChantalMB! That's perfectly fine, and best wishes to you and your family.

**Comment by ChantalMB** [comment]
> Thanks for checking in, @ChantalMB! That's perfectly fine, and best wishes to you and your family.

Thank you for the well wishes! Looks like it might be closer to the end of the week due to some teaching duties that popped up, but keep your eyes peeled for my submission! I'm assuming that I once again email the revised files when complete?

**Comment by jrladd** [comment]
Sounds great, @ChantalMB --you can upload your updated files directly here to the submissions repo if you'd like (you'll find it under `drafts` in the `en` directory). Or if you'd prefer, you can email them to me to upload: hello@jrladd.com.

**Comment by jrladd** [comment]
All your revisions are now committed, @ChantalMB! I will start my final checks shortly, and I'll let you know if I have any more questions.

[I removed the technical note that was here since whatever deployment problem there was appears to be resolved. Onward!]

**Comment by jrladd** [comment]
Thanks for all your hard work on this, @ChantalMB! I think this looks great, and we're almost ready to move to the next step.

I fixed a couple typos, added links to your files, and took care of a problem with footnote formatting. Those changes can be found in these [two](https://github.com/programminghistorian/ph-submissions/commit/535de6826e33b3d23da4b15a1cfc51380461ece2) [commits](https://github.com/programminghistorian/ph-submissions/commit/51acc08c0efb6558a10cf1c27e36783aff43b279). Here's a complete list of what I changed:

- Added links to the `articles.txt` file in assets in paragraphs 10, 41. (@anisa-hawes These links aren't currently working correctly. Did I put them in wrong?)
- Removed "in the field of" in paragraph 6
- Added "comes from" to "The code used for scraping articles *comes from* this tutorial" in paragraph 11
- Changed "cloud GPU serve" to "cloud GPU service" in paragraph 35
- Added "of" to "composed *of* two parts" in paragraph 63
- Changed "withdrawl" to "withdrawal" in paragraph 68
- Fixed subscript syntax for CO2 in paragraph 92
- Fixed syntax for endnote 18 in paragraph 94
- Fixed all endnote syntax in the endnotes section

Have a look at these when you get a chance, and let me know if it looks good. I also have two quick questions:

- In paragraph 10, you have missing links for [INSERT SCRAPING LINK] and [INSERT SCRAPING ARTICLES]. If you have the links for these, I can add them.
- In paragraph 65, there's a missing link for lesson output. Is this a link to a webpage you can send me, or is it an additional file you want us to add? Either way, I'm happy to add this, too.

Lastly, I'll need a brief author bio from you. This is just your name as you'd like it to appear on the article, your [ORCID](https://orcid.org/) if you have one (completely optional), and a one- or two-sentence bio. [This tutorial](https://programminghistorian.org/en/lessons/exploring-and-analyzing-network-data-with-python) has a few example bios at the bottom (including my own). You can add your bio here or email it to me: whichever you prefer is fine.

Thanks again—excited to be in the home stretch with this!

**Comment by anisa-hawes** [comment]
Thank you, @jrladd! 

I've updated the links at paragraphs 10 and 41. Until the asset files are moved over to our Jekyll repository for publication, we need to provide the full link to the assets folder in ph-submissions (rather than the 'relative' link for internal pages). So, in this case the link required for now is: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/assets/interrogating-national-narrative-gpt/articles.txt. I'll update it again ahead of publication!

Let me know if I can help you with any of the next steps, @jrladd & @ChantalMB.

**Comment by ChantalMB** [comment]
Thanks @jrladd and @anisa-hawes for your quick work!

The missing links were to files that *should* have been in the ZIP I emailed, but alas I guess they were missing! I sorted out the issues I was having with GitHub (note: if you're teaching an "Intro to Git" lesson and generate a lot of PATs in one day during demos, this is apparently "bot-like behaviour" haha) so I was able to create a pull request with the added assets and edited links 👍 

You can use this as my bio:

Chantal Brousseau is an MA candidate in the History and Data Science program at Carleton University. Her research focuses on applications of machine learning and computational creativity to the study of historical data.

And my ORCID is: 

https://orcid.org/0000-0002-4649-059X 

As always, let me know if there's anything else you need me to do!

**Comment by jrladd** [comment]
Thanks again, @ChantalMB and @anisa-hawes! This looks great to me. (By the way, you *did* add those files to the ZIP, and I just misunderstood. Sorry about that, and thanks for uploading them!)

@svmelton @hawc2 This is ready to advance. The list of file locations you'll need is below. Here's a new author bio for this lesson:

```
- name: Chantal Brousseau
  team: false
  orcid: 0000-0002-4649-059X
  bio:
      en: |
          Chantal Brousseau is an MA candidate in the History and Data Science program at Carleton University. Her research focuses on applications of machine learning and computational creativity to the study of historical data.
```

File locations:

- Lesson file: en/drafts/originals/interrogating-national-narrative-gpt.md
- Image files: images/interrogating-national-narrative-gpt
- Asset files: assets/interrogating-national-narrative-gpt
- Original avatar: gallery/originals/interrogating-national-narrative-gpt-original.png
- Modified avatar: gallery/interrogating-national-narrative-gpt.png

Let me know if you need anything else, and when you're ready to merge I can add the tweets to the spreadsheet.

**Comment by svmelton** [comment]
Thank you @jrladd! Excited to see this move forward. @anisa-hawes I think this still needs copyediting. Do you have capacity for that?

**Comment by tiagosousagarcia** [comment]
Hello all -- just a quick note to say that this is my last week working for PH. It's been an absolute pleasure working on this, and I'm only sorry I'm not going to be around for its publication (from this side -- I'll definitely be reading and using it as a regular joe). Big thanks to @ChantalMB for writing it, and @jrladd for taking it forward, as well as @svmelton and @anisa-hawes for all your support. Well done everyone!

**Comment by anisa-hawes** [comment]
Dear @ChantalMB + @jrladd,

I've applied the copyedits + perma.cc links to your lesson. Please let me know if you're happy with the adjustments. See [Update interrogating-national-narrative-gpt.md](https://github.com/programminghistorian/ph-submissions/commit/1739e5af03be5c4c6ea475e4b559b64a4e7686a0).

Note that perma.cc can't capture the URLs that link directly to image files satisfactorily, so you'll see that 2x URLs at lines 216 ([convex function](https://www.researchgate.net/profile/Jesper-Christensen-8/publication/284419329/figure/fig8/AS:669960540004354@1536742448305/example-of-a-continuous-convex-function.jpg)) and 228 ([local minimum](https://upload.wikimedia.org/wikipedia/commons/6/68/Extrema_example_original.svg)) of the Markdown file remain as links to the live web.

I'd like to ask if you could add alt-text to your (very beautiful and expressive!) figure images? The syntax to use is: `{% include figure.html filename="file-name.png" alt="Visual description of figure image" caption="Caption text to display" %}`. One thing to note is that Markdown styling should not be included within your alt, because screen readers read the characters directly (so **bold** is read including asterisks).

Last thing is a new step in our workflow: we are now asking authors and translators to complete [a declaration form](https://programminghistorian.org/assets/forms/Authorial-copyright-and-publishing-rights.pdf) to acknowledge their copyright and grant us permission to publish. I already have your email @ChantalMB, so I'll send you the form in a moment. 

--

@jrladd, I can see that you've already found an image to represent this lesson. Thank you! A next step for you will be to prepare 2 Tweets for our Twitter Bot. Instructions for how to do that are [here](https://github.com/programminghistorian/jekyll/wiki/DRAFT-:-EN-Editorial-Guidelines-v.3#6-publication). Let me know if you have any questions! We can Tweet directly after publication, but the Bot will help us to publicise the lesson in the future. 

Meanwhile, I'm aware that we would like [to resolve the outstanding question](https://github.com/programminghistorian/jekyll/pull/2616) of how to set up a banner logic which will bring enable readers to find lessons published as part of the PH/Jisc/TNA partnership. (cc. @drjwbaker)

Also tagging @hawc2 here, just to keep him up-to-date.

Very best to all,
Anisa

**Comment by jrladd** [comment]
Thanks very much, @anisa-hawes! I just drafted the tweets in the spreadsheet. It looks like all we need now is a stable DOI/link to the lesson. Do we have that already, or does that come after publication?

@ChantalMB do you have a Twitter handle you'd like us to use in the tweets?

**Comment by ChantalMB** [comment]
@anisa-hawes I just made a pull request that adds alt text to the figures, and you should have gotten my email with the signed declaration forms!

@jrladd I just updated my twitter account info so you can tag me @ chntlbrouz-- I tend to only use twitter to lurk haha

**Comment by anisa-hawes** [comment]
Dear @ChantalMB. 

Thank you for preparing the alt text, and thank you to @hawc2 for merging in these edits. 

I've received your Authorial Copyright form by email too – thank you.

@jrladd the DOI is allocated and added to the YAML by Alex (Managing Editor) and the link is live shortly after publication. I can add it onto the Twitter Bot spreadsheet then!

Looks like this lesson is ready for @hawc2's final read-through, and we can move forwards with publication 🙂

**Comment by drjwbaker** [comment]
Amazing job all. So looking forward to seeing this live.

**Comment by hawc2** [comment]
Thanks all, looking forward to publishing this shortly. One minor question: how come the difficulty for this is set to a 2? I would've said this is an Advanced lesson

**Comment by jrladd** [comment]
I think the difficulty was already set when I came on as editor, @hawc2, so I'll let others speak to the original intent. But the way I've thought about this lesson is that though its subject is complex (and very clearly explained!), the code for fine-tuning the model is not as involved as some of our other lessons. I'm fine with changing the difficulty if others think this is better as a 3.

**Comment by ChantalMB** [comment]
I personally aimed this lesson to be for an ambitious beginner with the same reasoning that @jrladd states, but I'm the author so not very objective haha Thank you for your revisions @hawc2 !

**Comment by hawc2** [comment]
I see - thanks for clarifying! It's fine to leave it as a 2, then, but I'll slightly tweak the lesson abstract so it says the lesson 'introduces the basics' or something like that

**Comment by anisa-hawes** [comment]
Hello @jrladd. 

Just a quick note to say that I've removed the two Tweets you've prepared from the Google Sheet for now – I think we need to wait until the lesson is published to add these, otherwise the Bot might go ahead and Tweet them before we're ready! 

When we're set up for publication and have a DOI, I'll add them back in! 🙂

**Comment by hawc2** [comment]
@anisa-hawes with the banner feature updated on the site, is this lesson now ready for me to review and publish?

**Comment by drjwbaker** [comment]
I think so.

**Comment by anisa-hawes** [comment]
Hello @hawc2. [Yes, it's ready](https://github.com/programminghistorian/ph-submissions/issues/418#issuecomment-1234370044).

And I have the two Tweets (prepared by John) to slot into our Bot pipeline as soon as the lesson is published.

**Comment by hawc2** [comment]
Hi everyone, congratulations, this lesson has been published!: 

https://programminghistorian.org/en/lessons/interrogating-national-narrative-gpt

**Comment by lorellav** [comment]
Wonderful thank you and congratulations to us!

L.

Dr Lorella Viola
Research Associate | DHARPA Project
Luxembourg Centre for Contemporary and Digital History (C2DH )

UNIVERSITY OF LUXEMBOURG
BELVAL CAMPUS
Maison des Sciences Humaines
11, Porte des Sciences
L-4366 Esch-sur-Alzette
https://lorellaviola.me.uk / https://dharpa.org<https://dharpa.org/>
+3524666445009

**Comment by anisa-hawes** [comment]
Congratulations to all! 🎉 

@jrladd, I've added the two Tweets you prepared to our Bot pipeline. 

If anyone would like to share in immediate promotion: https://twitter.com/ProgHist/status/1580587171614195712 ✨

**Comment by ChantalMB** [comment]
Yay! Thanks to everyone for all of your help with getting this tutorial edited and published 😊🎉!

**Comment by jrladd** [comment]
Congrats to @ChantalMB and everyone who worked on this, and thanks everybody for all the hard work!
