### ISSUE TITLE
Revisão da tradução da lição Autoria Sustentável em Texto Simples usando Pandoc e Markdown

### ISSUE THREAD

**Issue by JimmyMedeiros82** [programminghistorian/ph-submissions#469]
O Programming Historian em português recebeu a proposta de tradução da lição 'Autoria Sustentável em Texto Simples usando Pandoc e Markdown' feita pela Gabriela Kucuruza. 

A lição traduzida está no link a seguir: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/esbocos/traducoes/autoria-sustentavel-texto-simples-pandoc-markdown.md

Esta lição está agora em revisão e pode ser lida em: http://programminghistorian.github.io/ph-submissions/pt/esbocos/traducoes/autoria-sustentavel-texto-simples-pandoc-markdown

Já a lição original está em: https://programminghistorian.org/en/lessons/sustainable-authorship-in-plain-text-using-pandoc-and-markdown

Agradeço a @GabrielaKucuruza  pela nova contribuição.
Eu serei o editor da tradução. O @Ju-ms será uma das revisoras. Irei convidar o segundo revisor, em breve.

Peço para avaliarem a tradução para o português, assim como se há necessidade de adequação de dados ou algum conteúdo. Por favor, deixem suas sugestões neste ticket. Para cada modificação a ser sugerida, por favor, peço para indicar as linha de maneira que facilite os ajustes do Felipe. O ideal é realizar as modificações após as sugestões dos dois revisores.

Todos os membros da comunidade estão convidados a oferecer feedback construtivo que deve ser publicado neste canal, mas é solicitado que leiam primeiro as diretrizes para revisores (/directrizes-revisor) e sigam a nossa política anti-assédio (abaixo). Pedimos que todas as revisões parem após o envio da segunda revisão formal para que o/a autor/tradutor(a) possa concentrar-se no ajuste da lição. Eu farei um anúncio neste tópico quando isso ocorrer.

Vou me esforçar para manter a conversa aberta aqui no GitHub, mas se alguém sentir a necessidade de discutir algo em particular, pode entrar em contato comigo, ou pode sempre recorrer para o nosso mediador independente se achar necessário.
Se houver alguma preocupação da tradutora, ele pode entrar em contato com o mediador do PH em português (Luís Ferla).

**Comment by DanielAlvesLABDH** [comment]
Alterei a localização do ficheiro da tradução. Actualizei os links no comentário inicial. Obrigado à @GabrielaKucuruza e à @Ju-ms por mais essa contribuição!

**Comment by DanielAlvesLABDH** [comment]
No texto da tradução são indicadas imagens com nomes diferentes da lição original. Essas imagens foram carreagdas no GitHub? Onde estão? Ou são iguais às imagens originais?

**Comment by GabrielaKucuruza** [comment]
@DanielAlvesLABDH criei uma pasta com as imagens https://github.com/programminghistorian/ph-submissions/tree/gh-pages/pt/licoes/traducoes/Autoria%20Sustentavel (mas elas são iguais sim).

**Comment by DanielAlvesLABDH** [comment]
Obrigado @GabrielaKucuruza. Sendo assim vou apagar. No texto da tradução, por favor, coloque o nome dos ficheiros de imagem igual à da lição original.

**Comment by GabrielaKucuruza** [comment]
Feito! Obrigado, @DanielAlvesLABDH

**Comment by JimmyMedeiros82** [comment]
Caro @ilv2006 poderia colaborar conosco fazendo a revisão desta lição?

**Comment by JimmyMedeiros82** [comment]
caro @danielbonattoseco você poderia cooperar conosco em mais esta revisão?

**Comment by danielbonattoseco** [comment]
Olá Jimmy, fico feliz em colaborar com mais esta revisão.

**Comment by danielbonattoseco** [comment]
Primeiramente gostaria de agradecer a @GabrielaKucuruza pela excelente contribuição. Seguem algumas correções e sugestões de melhoria para a lição:

- [x] Linha 4 - Substituir "autoroia" por "autoria" (tanto no título do arquivo quanto no slug);
- [x] Linha 25 - Substituir ". docx" por ".docx";
- [x] Linha 25 - O termo "decks de slides" não costuma ser muito utilizado na lingua portuguesa. Sugiro substituir por algo como "apresentaçõeso de slides" (como foi utilizado na linha 36) ou ".pptx" (substituir na linha 36 caso opte por este);
- [x] Linha 36 - Inserir "você" antes de "aprenderá": 
- [x] Linha 36 - Substituir "formatados de forma bonita" por "belamente formatados";
- [x] Linha 38 - Substituir "no final" por "ao final";
- [x] Linha 40 - Substituir "Em vez de" por "Ao invés de";
- [x] Linha 40 - Substituir o hiperlink "Recursos Úteis" pela versão do artigo traduzido (caso a correção da linha 4 seja realizada, o link deve ser "https://programminghistorian.org/pt/licoes/autoria-sustentavel-texto-simples-pandoc-markdown#recursos-uteis";
- [x] Linha 53 - Substituir "lindos documentos" por "documentos belamente formatados";
- [x] Linha 55 - Incluir o hiperlink para o [Atom](https://atom.io/) e para o [Notepad++](https://notepad-plus-plus.org/);
- [x] Linha 57 - Substituir "Pages, da Apple," por "Apple Pages";
- [x] Linha 57 - Substituir "versões mais recente" por "versões mais recentes";
- [x] Linha 65 - Talvez incluir este hiperlink para o  [WordFuture](https://pt.wikipedia.org/wiki/WordPerfect) para contextualizar a ideia do parágrafo de decadência do software proprietário mencionado e o possível mesmo futuro para o MS Word?
- [x] Linha 65 - Substituir "das versões" por "de versionamento";
- [x] Linha 66 - Substituir "Word" por "MS Word" (para manter a consistência da lição);
- [x] Linha 67 - Substituir "indolor" por "simples";
- [ ] Linha 69 - Adicionar "de estudos" após "programa" (mantendo o padrão de tradução de _syllabus_ da linha 59;
- [x] Linha 71 - Substituir "livre de desordem" por "organizada";
- [x] Linha 78 - Adicionar um hiperlink para o [PowerShell](https://pt.wikipedia.org/wiki/PowerShell)?
- [x] Linha 79,84 - Substituir "e específicas para plataforma" por "e para plataformas específicas";
- [x] Linha 84 - Substituir "foi instalado" por "está instalado";
- [x] Linha 88 - Substituir "documentos de texto semanticamente simples" por "documentos de texto simples semanticamente";
- [x] Linha 90 - Incluir hiperlinks para o [Markdown do Pandoc](http://pandoc.org/README.html#pandocs-markdown) e [bloco “YAML”](http://johnmacfarlane.net/pandoc/README.html#yaml-metadata-block)
- [x] Linha 98 - Não sei se foi proposital a supressão do trecho 'fontfamily: times' da lição original; se não, inserí-la;
- [x] Linhas 102, 174 - Substituir 'O Markdown do "sabor Pandoc"' e 'Markdown com o sabor do Pandoc' por 'O sabor do Markdown usado pelo Pandoc' (mantendo a consistência de tradução da linha 90);
- [x] Linha 102 - Inserir "o documento" entre "quando" e "estiver pronto";
- [x] Linha 102 - Inserir aspas em YAML (mantendo a consistência com o restante da lição);
- [x] Linha 111 - Substituir ", sem identação:" por "Não dê recuo." (mantendo a consistência com a tradução da linha 156);
- [x] Linha 121 - Substituir "texto bobo" por "texto simulado";
- [x] Linhas 128, 168 - Substituir "nota no pé da página" por "nota de rodapé";
- [ ] Linha 133 et. al. - Talvez traduzir o nome do arquivo de "main.md" para "principal.md", de acordo com as [diretrizes para tradutores](https://programminghistorian.org/pt/directrizes-tradutor)? Se sim, manter a consistência com o restante da lição;
- [x] Linha 135 - Remover os espaços entre os elementos do exemplo de markdown;
- [ ] Linha 137 - O ideal é criar um novo arquivo `exemplo.md` que substitua o recurso `sample.md` da lição original utilizando o material traduzido nesta lição, de acordo com as [diretrizes para tradutores](https://programminghistorian.org/pt/directrizes-tradutor). Em seguida, basta subir este arquivo para a pasta do GitHub onde a lição traduzida será hospedada e copiar o link para download, substituindo na lição traduzida. Solicite ajuda ao @JimmyMedeiros82 caso tenha dúvidas;
- [ ] Linha 172 - As capturas de tela precisam ser refeitas utilizando os softwares e recursos na língua em que a lição está sendo traduzida, de acordo com as [diretrizes para tradutores](https://programminghistorian.org/pt/directrizes-tradutor);
- [x] Linha 178 - Substituir "o fluxo" por "no fluxo";
- [x] Linha 180 - Aplicar itálico ao termo "semânticas" (seguindo a ênfase na lição original);
- [x] Linha 182 - Substituir "ao vivo" por "em tempo real";
- [x] Linha 184 - Substituir "contanto" por "contato";
- [x] Linha 186 - Substituir "trabalhar" por "trabalho";
- [x] Linha 186 - Substituir "usado" por "usando";
- [x] Linha 188 - Substituir "pode" por "podem";
- [x] Linha 192 - Inserir espaços entre '$ cd \~' (o comando 'cd\~' retorna um erro, enquanto 'cd ~' realiza a função corretamente);
- [x] Linha 192 - Substituir "sinal de dinheiro" por "cifrão";
- [x] Linha 194 - Inserir espaços entre '$ pwd' (2 ocorrências);
- [x] Linha 194 - Substituir "retorne" por "exibir/apresentar" (de acordo com a tradução de 'print' disponível no [Mini-Glossário](https://docs.google.com/document/d/1o2rw7Rf_bOZkhHzAw18PfQUzBCCGbbq7dKsAjei8tTo/edit));
- [x] Linha 196 - Inserir espaço entre '$ cd>';
- [ ] Linha 197 - Adicionar linha em branco (parágrafo);
- [x] Linha 197 - Substituir "gerenciador de arquivos gráficos" por "gerenciador gráfico de arquivos";
- [x] Linha 201 - Substituir "pwd" por "$ pwd";
- [x] Linha 201 - Inserir "até" entre "navegar" e "a pasta";
- [x] Linhaa 203, 207, 213, 219, 223, 242 - Aplicar formatação markdown de trecho de código (aspas triplas);
- [x] Linha 209 - Substituir "bandeira" por "sinalizador" (de acordo com a tradução de 'flag' disponível no [Mini-Glossário](https://docs.google.com/document/d/1o2rw7Rf_bOZkhHzAw18PfQUzBCCGbbq7dKsAjei8tTo/edit));
- [x] Linha 217 - Substituir "belamente formato" por "belamente formatado";
- [x] Linha 221 - Um trecho da lição original não foi traduzido: "If your document is written in languages other than English, you will likely need to use the XeLaTeX engine instead of plain LaTeX for .pdf conversion: pandoc main.md --pdf-engine=xelatex -o main.pdf"
- [x] Linha 243 - O titulo original "Digital Pedagogy Unplugged" foi por algum motivo taduzido para "Pedagodia Pedagogy Unplugged". Manter o original.
- [x] Linha 255 - Insira "arquivo" entre "do seu" e "`main.md`";
- [x] Linha 258 - Substituir "dentro de citações" por "entre aspas";
- [x] Linha 272 - Substituir "rode" por "execute";
- [x] Linha 282 - Talvez inserir um hiperlink para o [Chicaco Author-date](https://www.chicagomanualofstyle.org/tools_citationguide/citation-guide-2.html)?
- [x] Linha 302 - Inserir "você" entre "Agora" e "deve";
- [x] Linha 302 - Substituir "arquivos origens" por "arquivos de origem";
- [x] Linha 313 - Substituir "espaço-duplo" por "espaçamento duplo" (2 ocorrências);
- [x] Linha 317 - O hiperlink para o site do Pandoc está incorreto. Substituir por [este](http://johnmacfarlane.net/pandoc/);
- [x] Linha 319 - Remover um parênteses do hiperlink "esta postagem do blog" (está causando a ruptura do link);
- [x] Linha 319 - O recurso [Mou](http://mouapp.com/) aparentemente não existe mais;
- [x] Linha 323 - Inserir o hiperlink para [Leanpub](https://leanpub.com/) e [readthedocs.org](https://readthedocs.org/);
- [x] Linha 326 - Inserir o hiperlink para [baixados no GitHub](https://github.com/dh-notes/pandoc-workflow);
- [x] Linha 330 - Eliminar um ponto final extra após "operacional";
- [ ] Linha 330 - Substituir a vírgula por ponto final após "texto";
- [x] Linha 331 - Inserir o hiperlink para [ele escreve](https://github.com/programminghistorian/jekyll/issues/46#issue-45559983).

**Comment by JimmyMedeiros82** [comment]
@danielbonattoseco obrigado pela atenta revisão!
Vamos aguardar a avaliaçãoda da @Ju-ms

**Comment by JimmyMedeiros82** [comment]
Olá @andresalvolns você poderia fazer a segunda revisão?

**Comment by andresalvolns** [comment]
Ótima tradução e revisão feitas pelos colegas!
Aqui vão algumas alterações que eu pensei:

- [x] Linha 36: Se possível, transformar as marcações de por exemplo `"[^1]"` em números sobrescritos como `¹`. Essa observação também serve para o restante do texto.
- [x] Linha 51: Alterar `"os seus arquivos sempre permanecerão compreensíveis"` e adicionar `"(...) compreensíveis **para você**"`
- [x] Linha 55: Adicionar hiperlink em `Atom` e` Notepad++`
- [ ] Linha 79: Alterar `"então tome o seu tempo navegando pelas instruções"` por `"então certifique-se de tomar o seu tempo navegando pelas instruções"`
- [x] Linha 90: Adicionar hiperlink em `bloco “YAML”`
- [ ] Linha 172: Arrumar o screen shot que não foi adicionado
- [x] Linha 186: Alterar `"nós precisamos nos orientar sobre o trabalhar"` por `"nós precisamos nos orientar sobre **como** trabalhar"`
- [x] Linha 188: Adicionar vírgula após `"ser usadas de outra forma"`
- [x] Linha 197: Separar em parágrafo da linha 196
- [x] Linha 201: Colocar o sinal `$` antes de `pwd`
- [x] Linha 207: Alterar "`$ pandoc main.md -o main.odt"` por `"$ pandoc main.md -o project.odt"`
- [ ] Linha 215: Alterar `"O que aconteceu?"` por `"Você sabe dizer o que aconteceu?"`
- [x] Linha 294: Alterar a linha pela frase `"Então repita o comando Pandoc para carregar seu arquivo markdown em seu formato de destino (.pdf ou .docx)"`
- [x] Linha 302: Alterar `"Agora deve (...)"` por `"Agora você deve (...)"`

Qualquer coisa é só me contatar!

**Comment by JimmyMedeiros82** [comment]
@andresalvolns muito obrigado pela revisão.
@GabrielaKucuruza temos a segunda revisão, podemos avançar com os ajustes para fechar a lição?

**Comment by GabrielaKucuruza** [comment]
Obrigado, @danielbonattoseco e @andresalvolns pela revisão! Essa semana avanço com os ajustes, @JimmyMedeiros82!

**Comment by GabrielaKucuruza** [comment]
Bom dia, @JimmyMedeiros82 
A lição está revisada. Gerei novamente as imagens em português (uma estava em inglês), elas estão na pasta do Drive https://drive.google.com/drive/u/0/folders/1T4s9xxHg8IS_ebiIE85RlNUwNHhOFYnD, fiquei na dúvida se deveria criar uma nova pasta de imagens. De resto, entendo que tudo foi finalizado. 
Obrigado novamente @danielbonattoseco e @andresalvolns pelas cuidadosas revisões!
Abraços

**Comment by JimmyMedeiros82** [comment]
@GabrielaKucuruza agradeço pelos ajustes realizados e a todos os colegas que contribuíram para os ajustes e melhorias. 

@DanielAlvesLABDH temos mais uma lição pronta para publicação.

**Comment by andresalvolns** [comment]
Claro!

Em ter., 9 de ago. de 2022 às 15:00, Jimmy Medeiros <
***@***.***> escreveu:

**Comment by DanielAlvesLABDH** [comment]
Vou fazer uma última revisão da tradução. Alterei o link para o ficheiro md no comentário inicial.

**Comment by DanielAlvesLABDH** [comment]
Conclui a revisão. Como já tenho o DOI vou passar à fase de publicação

**Comment by JimmyMedeiros82** [comment]
Maravilha! Boas notícias.

**Comment by anisa-hawes** [comment]
Hello all,

Please note that as part of a reorganisation of the /pt directory, this lesson's .md file has been moved to a new location within our Submissions Repository. 

It is now found here: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/esbocos/traducoes/autoria-sustentavel-texto-simples-pandoc-markdown.md

A consequence is that this lesson's preview link has changed. It is now: http://programminghistorian.github.io/ph-submissions/pt/esbocos/traducoes/autoria-sustentavel-texto-simples-pandoc-markdown

Please let me know if you encounter any difficulties or have any questions.
Very best, Anisa

--

@DanielAlvesLABDH when this lesson has been published, please move the file to [/pt/publicadas/traducoes](https://github.com/programminghistorian/ph-submissions/tree/gh-pages/pt/publicadas/traducoes)

**Comment by DanielAlvesLABDH** [comment]
Olá @JimmyMedeiros82, esta lição também já está publicada, com o DOI https://doi.org/10.46430/phpt0036. Pode actualizar o bot do Twitter e fechar o ticket, por favor. Agradeço Uma vez mais a colaboração e todo o trabalho da @GabrielaKucuruza, do @danielbonattoseco e do @andresalvolns 🥳

**Comment by anisa-hawes** [comment]
Olá @JimmyMedeiros82. 

I hope you are well? 

I note that this Issue remains open and we do not have the promotional Tweets. How about:

**1**. @dennistenen e @gwijthoff ensinam como Markdown e pandoc podem assegurar que o seu trabalho seja o mais sustentável possível

**2**. Aprenda a usar o pandoc e o markdown para transformar os seus documentos para qualquer situação com a lição de @dennisten e @gwijthoff 

If the Portuguese is correct, I can slot these into the Google Sheet.

Thank you!

**Comment by DanielAlvesLABDH** [comment]
Hi @anisa-hawes. I have edited the Google Sheet for this lesson. We can now close this.
