### ISSUE TITLE
Sentiment Analysis with 'syuzhet' using R

### ISSUE THREAD

**Issue by RolRodr** [programminghistorian/ph-submissions#478]
The Programming Historian has received the following tutorial on 'Sentiment Analysis with 'syuzhet' using R' translated by @acrymble. This lesson is now under review and can be read at:

http://programminghistorian.github.io/ph-submissions/en/drafts/translations/sentiment-analysis-syuzhet

Please feel free to use the line numbers provided on the preview if that helps with anchoring your comments, although you can structure your review as you see fit.

I will act as editor for the review process. My role is to solicit two reviews from the community and to manage the discussions, which will be held here on this forum.

Members of the wider community are also invited to offer constructive feedback which should post to this message thread, but they are asked to first read our Reviewer Guidelines (http://programminghistorian.org/reviewer-guidelines) and to adhere to our anti-harassment policy (below). We ask that all reviews stop after the second formal review has been submitted so that the author can focus on any revisions. I will make an announcement on this thread when that has occurred.

I will endeavor to keep the conversation open here on Github. If anyone feels the need to discuss anything privately, you are welcome to email me. 

Our dedicated Ombudsperson is (Ian Milligan - http://programminghistorian.org/en/project-team). Please feel free to contact him at any time if you have concerns that you would like addressed by an impartial observer. Contacting the ombudsperson will have no impact on the outcome of any peer review.

## Anti-Harassment Policy

This is a statement of the Programming Historian's principles and sets expectations for the tone and style of all correspondence between reviewers, authors, editors, and contributors to our public forums.

> The Programming Historian is dedicated to providing an open scholarly environment that offers community participants the freedom to thoroughly scrutinize ideas, to ask questions, make suggestions, or to requests for clarification, but also provides a harassment-free space for all contributors to the project, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age or religion, or technical experience. We do not tolerate harassment or ad hominem attacks of community participants in any form. Participants violating these rules may be expelled from the community at the discretion of the editorial board. Thank you for helping us to create a safe space.

---

**Comment by RolRodr** [comment]
Update: @JoshuaGOB and I will be meeting on Friday (May 13th) regarding this tutorial

**Comment by anisa-hawes** [comment]
Hello @RolRodr,

I hope you're well?

~~I noticed yesterday that the images aren't displaying correctly in the Preview. I've been trying to find out what is causing the problem, but I haven't resolved it yet... I have triple-checked the liquid syntax, the file names and the directory folders, and everything is perfect so it is a mystery! I will update you & Joshua here ASAP.~~

Thank you for your patience.

Anisa

**Update**

Done! In turns out that translation images are to be located in the 'original' images folder, in this case: images/analisis-de-sentimientos-r. I have moved them there, and the Lesson Preview now displays correctly!

Let's catch up again soon. A.

**Comment by anisa-hawes** [comment]
Hello @RolRodr. [I've added](https://github.com/programminghistorian/ph-submissions/commit/82f93c7b6a9f9c792b660cca663c31240ddf7711) html syntax for link within the Alert Warning box following para.89.

**Comment by RolRodr** [comment]
Hi @acrymble & @anisa-hawes, 
Below are my initial notes. Please, let me know if you have any questions or concerns!

## General Notes:
-	I really appreciated your translation of Jen’s original tutorial and found that the additions that you made were particularly helpful for our English audience. The first paragraph in the in the ‘Lesson Objectives’ section was a helpful framing device for why the particular package syzuhet is used instead of other sentiment analysis packages in R, as it is made to specifically allow for temporal sentimental analysis which is part of its namesake. I believe this introduction alone can help readers reflect on why they might choose one package over another when looking for future tools. 
-	The choice to not change the text that is being analyzed and maintaining the Spanish vocabulary, with their English translations, makes this lesson quite useful for folks who are interested in multilingual digital humanities projects. It shows how the package can be used in an English-speaking context to study a text in another language while pointing out where the limitations lie when doing sentiment analysis. This makes the tutorial rather stand out in a different way if an English text was used instead, as it is the case that there is still much research into texts in different languages that get published or presented in English, and tutorials for those projects are very limited. 
-	Overall, I do not think there is much change needed in the original tutorial apart from some minor grammatical and translation issues. The only structural thing I’ll point out here is the need for styling ‘syuzhet’ consistently throughout the tutorial. It’s a fantastic translation, and I’ve really appreciated the chance to do the initial edit. 

## Minor Changes
### Lesson Objectives

#### P 1 
- [x] Line 2: add comma after ‘algorithm’
- [ ] 	Line 3: ‘term’ to ‘noun’
- [x] 	Line 4: ‘to’ to ‘as’
- [x] 	Line 5: change hyphen to a comma
- [ ] 	Line 6: change ‘the’ to ‘a’

#### P 2
- [x] 	Line 1: change ‘on’ to ‘with
- [x]  Line 5: cut comma after ‘characters’

#### P4 
- [x] Links don’t work to intro R lessons or other sentiment analysis lessons, but I think that will change when the tutorial gets pushed to the actual site. 

### Background Information

#### P8

- [x] Line 4: add comma after ‘Galdós’

#### P9
- [x] Lines 3-4: change ‘text’s language’ to ‘text’
- [x] Line 7: add ‘of’ before ‘yet’

#### P 10:
- [x] Line 2: cut comma after ‘English’

#### P 11:
- [x] Line 2: ‘biologically-rooted’ should be ‘biologically rooted’
- [x] Line 6: change hyphen to en dash (–)

#### P12: 
- [x] Line 2: would change ‘by comparison’ to ‘on the other hand’
- [x] Line 3: change ‘causes joy’ to ‘brings us joy’
- [x] Line 4: would change ‘end in’ to ‘lead to’ / evoke / stimulate / promotes

#### P14:
- [x] Line 2: add ‘sentiment’ before ‘scores’
- [ ] Line 3: cut comma after patterns
- [ ] Line 6: Should there be a link for Stanford?
- [x] Line 7:Replace ‘NRC’ with ‘the NRC lexicon’

#### P15:
- [x] Lines 3-4: ‘National Research Council of Canada’ should be ‘National Research Council Canada’ ([Source](https://en.wikipedia.org/wiki/National_Research_Council_Canada))
- [x] Line 7: replace hyphen with en dash
- [x] Lines 12-13: cut parenthesis around “which may lack linguistic nuance in unpredictable ways” and add a comma after ‘translation

#### P18: 
- [x] The R Package, syuzhet, is presented in three distinct formats: in quotations in title (in the Spanish article, Jen maintains the code markdown), as a link (which erases the grey background behind syuzhet), and the standard code formatting. Perhaps, it should be presented in one way, at least throughout the paragraph content, by presenting the link in a parenthetical statement after the package name.
- [x] Line 3: the parenthetical statement looks a little awkward, perhaps it could be written as “We use version 1.0.6, the November 2016 release, in this lesson.”

#### P19:
- [x] Line 1: add comma after ‘texts’
- [x] Line 3: add ‘it’ before ‘has not’
- [x] Line 5: change ‘using’ to ‘the use of’

#### P20a:
- [x] Line 1: add colon or break-line after “Some Research Warnings”
- [x] Line 5: cut comma after ‘America’

#### P20b:
- [x] Line 4: ‘very good’ might be ambiguous to the reader. Would something like ‘reliable’ or ‘trusted’ work instead?
- [x] Line 5: cut comma after ‘Spanish’

#### P20d:
- [x] Line 2: replace hyphen with a period after ‘negation’ ; add comma after ‘example’

#### P20e:
- [ ] In the original article, this paragraph is not in the unordered list following the previous points, would it be beneficial to change that?

#### P21:
- [ ] Are P21-22 and Table 1 needed for the English translation?

### A Brief Example
#### P23:
- [x] Line 1: might add ‘our text,’ before ‘Miau’ because the reader may have already forgotten the name of the text
- [x] Lines 4-6: “The analysis takes place using R, in which you will [tokenise](https://en.wikipedia.org/wiki/Lexical_analysis#Tokenization) the text into a list of [strings](https://en.wikipedia.org/wiki/String_(computer_science)) (words/unigrams) that are then analysed one at a time.” might be better understood as “This analysis uses R and prompts you to tokenise the text into a list of single-word [strings](https://en.wikipedia.org/wiki/String_(computer_science)) (unigrams) that are then analysed one at a time.”

#### P24-27: 
- [x] ‘Spanish Original’ and ‘Rough English Translation’ might benefit from being non-italic and perhaps bolded
- [x] P26 Line 2: ‘solutude’ should be ‘solitude’

#### P28:
- [x] “by the code (not yet shown)” does not seem to be needed in the sentence.

#### P29:
- [x] Lines 3-4: “The result for the first few words in this short passage looks like the following” may be clearer if rewritten as “The following is the result for the first few words in this short passage:”
- [x] I think it might be helpful to mention the result of the sentiment analysis function is returned in a data frame, as Jen does in the original. A link to the Wikipedia page for the dataframe object might also be helpful, as is done with strings.

#### P30:
- [x] Line 5: would change ‘any score’ to ‘a score’
- [x] Line 6: cut comma after ‘lexicon’
- [x] Line 7: ‘to indicate’ should be ‘indicating’

#### P31:
- [x] Line 3-4: ‘second last’ should be ‘second-to-last’
- [x] Line 4: ‘bowed’ should be ‘taking’ ; add ‘as’ before ‘a positive word’

### Appropriate Research Questions:
#### P34:
- [x] Line 3: ‘contemporary’ as genre does not translate well into English; I would just cut it out.
- [x] Line 5: cut comma after ‘century’
- [x] Line 7: “tras quedar desempleado,” was not translated. It could be added as “the employed Ramón Villaamil” or “Ramón Villamil after becoming unemployed while his family…”
- [x] Line 9: “Villaamil enters a spiral of misfortune” might be better translated as “Villaamil’s spiral of misfortune’ for cohesion with the rest of the sentence

#### P35:
- [x] Line 1: capitalize ‘can’
- [x] Line 5: ‘with’ isn’t needed

### Obtaining Sentiment and Emotion Scores
#### P36:
- [x] The last step of conducting and analyzing the results might be more helpful as two separate steps for readers who are attempting to thinking of the most basic units of this workflow. This would make it a four-step process

### Install and Load Relevant R Packages
#### P37:
- [ ] Here we again find package names with links whereas syuzhet is not linked in an earlier entry. 
- [x] Line 3: ‘employ’ might be better put as ‘require’
- [x] Line 5: ‘package’ is not required because it is mentioned in the introduction to the package titles

#### P38:
- [x] Lines 1-2: change ‘code example’ to ‘sample code’
- [x] Lines 5-6: ‘This installing step’ could be ‘The installation of these packages’ 

### Load and Prepare the Text
#### P39:
- [x] Since previous paragraphs have linked technical concepts such as “strings” — ‘plain text format’ might be helpful to link to the ‘plain text file’ Wikipedia (https://en.wikipedia.org/wiki/Plain_text)

#### P40:
- [x] Line 5: should ‘Mac’ be ‘Mac/Linux’ ?

#### P41:
- [x] Line 1: should ‘Mac’ be ‘Mac/Linux machine’?
- [x] Line 1: Should it be mentioned that the ‘get_text_as_string’ function is a function from syuzhet, as mentioned in the original Spanish?

#### P44:
- [x] Line 5: I would cut the last sentence of this paragraph because it is repeated in the beginning of the next paragraph more clearly.


#### P46:
- [x] Line 1: ‘built in’ should be ‘built-in’ or might be replaced with ‘the package’s built-in’

#### P47:
- [x] Line 2: change ‘were’ to ‘are’
- [x] In the original article, Jen also shows how to get the sentence count from the novel. Would it be worth adding that in here since sentence-level analysis is also pretty common when doing sentiment analysis?

### Extracting Data with the NRC Sentiment Lexicon
#### P48:
- [x] Lines 10-11: “and assigns each a number as in the example above” is a little confusing because the example is at the beginning of the lesson and not right before. In the Spanish, “y asigna un número mayor a 0 en caso de existir” is used, which could be translated to “and assigns a number greater than 0 if the word is found within NRC’s lexicon.” This might be a more clear way to finish the sentence.


### Summary of the Text
#### P50:
- [x] Lines 7-8: I believe there was a translation error on this sentence. The Spanish reads: “Por ejemplo, podemos ver que la novela Miau es, de [media](https://es.wikipedia.org/wiki/Media_(matem%C3%A1ticas)) (mean), más positiva (0.05153) que negativa (0.04658)” which can be translated to “For example, we can see that the novel Miau is, on average (mean), more positive (0.05153) than negative (0.04658)” or to match your (Adam) voice: “For example, we can see that the novel Miau, on average (mean), uses more positive (0.05153) language than negative (0.04658), according to the algorithm.”

#### P51:
- [x] Lines 6-7: This sentence is a little confusing. Could the second clause (“it is not surprising that no one emotion or sentiment has very high values over all”) read something like “it is not surprising that no one emotion or sentiment has distinctively high statistical values” ? 


### Interpreting the Results
#### P52:
- [x] Line 3: ‘Two’ should be ‘Three’ since three distinct visualizations are mentioned and used in the lesson

### Bar Chart By Emotion
#### P53:
- [x] Lines 3-4: ‘built in’ should be ‘built-in’

#### P54: 
- [ ] Line 4: I don’t think the ‘0.4’ has to be in the code markdown format unless the entire line ‘space=0.2’ is copied

### Counting Words by Emotion
#### P59:
- [x] Line 2: cut comma after ‘text’
- [x] Line 5: replace hyphen with en dash (–)
- [x] Line 9: I think having ‘sadness’ within the code markdown format might confuse readers. Perhaps, it could be written in italics or the entire code could be specified “sentiment_scores$sadness”

#### Code Example Box: 
- [x] ‘words_sadness’ is a literal translation of the Spanish variable ‘palabras_tristeza’ but for English readers, perhaps ‘sad_words’ might be a more meaningful variable name

#### P60:
- [ ] Line 1: if the variable name is changed, then it should be changed in this first line. Further, sometimes variables are written in quotations or using the code markdown format; such renditions should be consistent

#### Code Example Box:
- [x] if the variable name is changed, then it should be changed in this example too

#### P62:
- [x] There was a translation error in lines 2-3. The Spanish reads “sobre el objeto que ahora agrupa las palabras en orden” and was translated to “which will group the words in order”, but it should be translated to “the object which now groups the words in order” (this is referring to the words_sadness_order variable). To match your (Adam)’s language,  the second half of the sentence could be tweaked to “you can use the length function on the newly created words_sadness_order variable.”

#### P69:
- [ ] Line 4: It might be helpful to explain why the user is changing the term-document matrix into a matrix 

#### P77:
- [x] Line 7: cut comma after ‘sense’ 

#### P83:
- [x] Line 2: ‘values’ is misspelled

### Loading your own Sentiment Lexicon
#### P86: 
- [x] Line 8: I’d change ‘dataset’ to ‘lexicon dataset’ 

#### P87:
- [x] Line 3: ‘score’ should be scores’
- [x] Line 4: ‘words’ should be words’

#### Warning Box after P89:
- [x] The link at the end of the box is not formatted correctly. ([Done](https://github.com/programminghistorian/ph-submissions/commit/82f93c7b6a9f9c792b660cca663c31240ddf7711)!, Anisa)

**Comment by RolRodr** [comment]
I have also begun reaching out to potential reviewers. In this regard, I am hoping that one reviewer is fluent or at least familiar with Spanish and another without knowledge of Spanish, as the perspectives from those two kinds of reviewers would be rather beneficial for this and future translations—I think.

**Comment by acrymble** [comment]
Thanks @RolRodr did you want me to make these changes after you've had peer reviewers read it and comment?

**Comment by RolRodr** [comment]
@acrymble Hi, Adam! I think you could make them before the peer reviewers' feedback—if time allows—as I haven't heard back from folks yet. Thanks for checking!

**Comment by acrymble** [comment]
@RolRodr thanks, I've fixed the ones I could find. There were a few I wasn't able to locate given the context.

> Are P21-22 and Table 1 needed for the English translation?

On this suggestion, I think I'd be inclined to leave the translation table in to highlight the fact that Jenn had to do so in the original for Spanish readers and that we all need to keep in mind those higher barriers to coding in languages other than English.

**Comment by RolRodr** [comment]
Hi @acrymble , 

Thank you so much for your quick edits. I deeply apologize for the time it has taken me to continue on this thread – I went away and have been dealing with some health issues along other matters that all seemed to collide. 

Since the remaining edits were all minor, I went ahead and made them to save you time. [Here is the link to the commit](https://github.com/programminghistorian/ph-submissions/commit/97910ebfb18555860fa58b4f6f6dcae26809d07d), if you want to see the changes. 

As another point of update: I've been reaching out to folks to be reviewers but have had little luck of receiving acceptances. I'll be reaching out to other folks on the English editor teams for recommendations and contacting some other folks in my network. 

Thank you!

**Comment by acrymble** [comment]
Thank you for the update @RolRodr 

I hope you are feeling better.

**Comment by acrymble** [comment]
Hi @RolRodr is there any update on this?

**Comment by acrymble** [comment]
@hawc2 I'm not able to reach the editor. Can you please let me know the status of this submission? It was submitted 16 months ago and still hasn't had a review.

**Comment by hawc2** [comment]
@acrymble we're coincidentally meeting today and you should hear back shortly after that

**Comment by hawc2** [comment]
@acrymble just to clarify, you said 16 months ago? I see the first issue posted in April of this year.

**Comment by acrymble** [comment]
@hawc2 yes I submitted this in June 2021. No ticket was opened until April 2022.

**Comment by RolRodr** [comment]
@acrymble I apologize for my lack of response; finding reviewers has been rather difficult. Fortunately, we now have two reviewers for this article! Shuang Du (@ReneeDu320) and Andrew Janco (@apjanco) have agreed to review this article. Thank you to @hawc2 for recommending that I reach out to @apjanco.

**Comment by ReneeDu320** [comment]
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Avenir Next'; color: #000000">Hello all,</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Avenir Next'; color: #000000">I think the tutorial is precise and very helpful. I don't know Spanish at all but I found the tutorial is easy to follow and understand. The simple example for 'sentiment analysis using syuzhet' in the first section is a good start for audience who're not familiar with the 'sentiment analysis' concept. The following step by step case study on ‘Miau’ provides a clear pipeline for users.&nbsp;&nbsp;I also found the visualization plots and their explanations helpful for understanding the quantitative results from `summary of the text`. Overall I think the tutorial has a clear framing and provides necessary information for first-time users to follow the lesson.</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Avenir Next'; color: #000000">I have a few suggestions for minor changes:</p>
- [ ] In section `Interpreting the Results`, I think it would be helpful to link some functions with its Rdocumentations.

<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Avenir Next'; color: #000000; min-height: 19.0px"><br></p>


barplot() | paragraph 54 | https://www.rdocumentation.org/packages/graphics/versions/3.6.2/topics/barplot
-- | -- | --
comparison.cloud | paragraph 75 | https://www.rdocumentation.org/packages/wordcloud/versions/2.6/topics/comparison.cloud


- [x] When users applying the sample code in the tutorial, they may also want to change the parameters in the function to customize their plots. A quick link for the above functions in the tutorial would be especially helpful for R beginners.

I hope these feedback would be helpful, also thanks @RolRodr for inviting me to be the reviewer!

**Comment by apjanco** [comment]
Thank you for the opportunity to review this submission and translation. I have been a fan of PH's efforts to promote original content in Spanish, and it's great to see that content in translation for an Anglophone audience. The translator's notes do an excellent job of addressing context that readers may need. 

Overall, this looks ready to publish in English. I have included my notes and thoughts below. They may be helpful when preparing the text and are related to the Spanish original and the English translation.   

- [x] Line 94 - This section gives some history on Jocker's work and Annie Swafford's critique. Beyond noting the debate, a concise summary of the positions and points of contention would be helpful. As written, the reader needs to leave the tutorial to learn more or to assess the significance of this critique for their use of syuzhet.

- [x] Line 106 - Mentions that syuzhet is not able to handle negation properly which is a significant limitation that has been addressed by NLP research. Richard Socher's 2013 dissertation offers a solution to the problem of contrastive conjunctions and negation. Since 2017, transformer models can account for context in sentiment prediction tasks. I am glad that this limitation is listed and will help readers. Syuzhet's approach is still a common method of detecting sentiment, but I would give those readers for whom this would be a serious problem a path forward.

- [ ] Line 276 - The section "Load and Prepare the Text" has separate instructions for Mac and Windows. It's not a bad practice to declare a text's encoding. I'd consider consolidating the Mac/Linux versus Windows sections with both having the fileEncoding argument.

- [x] Line 275 - Discusses how syuzhet tokenizes the text. Syuzhet's `get_tokens()` function uses regex. A footnote on what regex considers a "word" character (`"\\W"`) would be helpful here. This seems to have the effect of dropping spaces and punctuation, which is a common tokenization method for some languages but is problematic for others. 

- [x] Line 303 - Notes that the `get_nrc_sentiment` function requires a `lang` argument for languages other than English. It would be helpful to know which languages are supported and what format is required (seems lower-case name? `lang="spanish"`) The 2020 syuzhet version (1.0.4) documentation lists:

Arabic, Basque, Bengali, Catalan, Chinese_simplified, Chinese_traditional, Danish, Dutch, English, Esperanto, Finnish, French, German, Greek, Gujarati, Hebrew, Hindi, Irish, Italian, Japanese, Latin, Marathi, Persian, Portuguese, Romanian, Russian, Somali, Spanish, Sudanese, Swahili, Swedish, Tamil, Telugu, Thai, Turkish, Ukrainian, Urdu, Vietnamese, Welsh, Yiddish, Zulu.

- [x] This text also seems important to share with readers: 
"At the time of this release, Syuzhet will only work with languages that use Latin character sets. This effectively means that “Arabic”, “Bengali”, “Chinese_simplified”, “Chinese_traditional”, “Greek”, “Gujarati”, “Hebrew”, “Hindi”, “Japanese”, “Marathi”, “Persian”, “Russian”, “Tamil”, “Telugu”, “Thai”, “Ukranian”, “Urdu”, “Yiddish” are not supported even though these languages are part of the extended NRC dictionary."

https://cran.r-project.org/web/packages/syuzhet/vignettes/syuzhet-vignette.html

**Comment by acrymble** [comment]
@RolRodr I see we now have both reviewers responses. Is there anything you'd like me to take into consideration before I revise the text?

**Comment by acrymble** [comment]
Happy new year @RolRodr. Can you please provide some guidance on how you'd like me to proceed?

**Comment by RolRodr** [comment]
@acrymble Happy New Year, Adam. I apologize for missing your previous comment. I have looked over both of the reviewer's comments, and you should be all set to revise the text based on the reviewer's responses. I'll go over the text again once that has been done, and the tutorial should be able to move on to the next step after that. Thank you for your patience!

**Comment by acrymble** [comment]
@RolRodr thank you I will begin revising it soon. I have to teach a class using this tutorial in 3 weeks time so I don't want to change it while the students are using it. But I'll do that as soon as possible thereafter.

**Comment by acrymble** [comment]
In addition to the above comments, I've re-tried the lesson (as my students are using it later this week) and note the following issues to address:

- [x] Tested on R 4.2.x now, so I can update that.
- [x] p 34 'family family' repeated
- [ ] p 48 the length of sentence_vector on a mac when using the code for Windows (which is to signify UTF-8) gives a result of 13136 sentences instead of 6022. I'm not yet sure why but if I take the advice above and make that uniform across platforms, it needs to work properly.
- [x] Fig 1 caption reads 6 emotion but there are 8 categories (two of which are 'secondary emotions').
- [x] The code to calculate sentiment scores now gives a deprecation warning that's linked to the syuzhet package itself. The code still works for now but it is throwing a warning: "Warning message:
`spread_()` was deprecated in tidyr 1.2.0.
ℹ Please use `spread()` instead.
ℹ The deprecated feature was likely used in the syuzhet package.
  Please report the issue to the authors.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated. "
- [x] In the word cloud section the sentiment 'joy' is mislabelled in p72 code block as 'trust' and this also means Figure 2 is incorrect, so I have to replace this.
- [x] Most of the students didn't know how to find their FILEPATH so I've added links to where they can find this out, as well as an example of the format required.

**Comment by acrymble** [comment]
> Line 94 - This section gives some history on Jocker's work and Annie Swafford's critique. Beyond noting the debate, a concise summary of the positions and points of contention would be helpful. As written, the reader needs to leave the tutorial to learn more or to assess the significance of this critique for their use of syuzhet.

I've beefed the examples up a bit, without going into all the detail because the links are there to the original texts: "This included concerns about incorrectly splitting sentences involving quotation marks, and problems with using a sentiment lexicon designed for modern English on a historic text that uses the same words in slightly different ways. Assigning concrete values of measurement to literary texts, which are by their nature quite subjective, is always challenging and potentially problematic. A series of archived blog entries by Jockers outline [his thoughts on the method and address some of the criticisms](https://web.archive.org/web/20190708100723/http://www.matthewjockers.net/page/2/) about the degree to which sentiment can accurately be measured when sometimes even humans disagree on a passage of text's effects on the reader."


>  Line 106 - Mentions that syuzhet is not able to handle negation properly which is a significant limitation that has been addressed by NLP research. Richard Socher's 2013 dissertation offers a solution to the problem of contrastive conjunctions and negation. Since 2017, transformer models can account for context in sentiment prediction tasks. I am glad that this limitation is listed and will help readers. Syuzhet's approach is still a common method of detecting sentiment, but I would give those readers for whom this would be a serious problem a path forward.

I've added a reference to Socher's PhD. The transformer models won't work with this particular solution as far as I can tell, as they're machine-learning based, and this is lexicon based.

> Line 275 - Discusses how syuzhet tokenizes the text. Syuzhet's get_tokens() function uses regex. A footnote on what regex considers a "word" character ("\\W") would be helpful here. This seems to have the effect of dropping spaces and punctuation, which is a common tokenization method for some languages but is problematic for others.

I've added a couple of sentences and a link to Wikipedia to help explain the implications of this approach: "This approach to tokenisation uses [regular expressions](https://en.wikipedia.org/wiki/Regular_expression) and is not always appropriate in all use cases. It will, for example, split hyphenated words into two. Depending on your text, you should consider the implications of your chosen method of tokenisation as you can use any method you like as long as the output is in the same format as in the example below."

> The code to calculate sentiment scores now gives a deprecation warning that's linked to the syuzhet package itself. The code still works for now but it is throwing a warning: "Warning message:
spread_() was deprecated in tidyr 1.2.0.

I've added a note in the text that this shouldn't affect the running of the code, and that fixing this error is out of the hands of all but Matthew Jockers.

**Comment by acrymble** [comment]
@RolRodr 

I've now revised the text as best I can. The changes are listed in the above comments, including fixing a few issues that came up during my workshop with my students. The one I can't fix is the suggestion to make the Mac/Windows loading instructions consistent. This isn't my code and I'm not really a heavy Windows user so I wouldn't know how to fix it.

I'd like to note that I think there's an error in that original code:

`text_string <- scan(file = "FILEPATH", fileEncoding = "UTF-8", what = character(), sep = "\n", allowEscapes = T)`

When checked for number of sentences it returns this:

`sentence_vector <- get_sentences(text_string)
length(sentence_vector)
[1] 13136`

The result should be 6022 according to the code. When I use that same line on Mac it also returns 13136. The rest of the code runs fine, so I'm not sure of the impact of this. @jenniferisasi wrote the original (which has also been translated into PT) so she may be best placed to update that issue as a bug rather than a translation problem.

@jenniferisasi there is also now a code warning in the syuzhet package itself, which Matthew Jockers would have to fix (I don't know if you're in contact):

> "Warning message:
spread_() was deprecated in tidyr 1.2.0.
ℹ Please use spread() instead.
ℹ The deprecated feature was likely used in the syuzhet package.
Please report the issue to the authors.
This warning is displayed once every 8 hours.
Call lifecycle::last_lifecycle_warnings() to see where this warning was generated. "

Apart from that bug in the original, I believe I've addressed all of the review comments and I pass it back to you @RolRodr

**Comment by RolRodr** [comment]
Thank you for the update, @acrymble. I will review the all the changes and give the lesson another close read-through before continuing. I will follow up soon!

**Comment by jenniferisasi** [comment]
Dear @acrymble and @RolRodr! Just a note to say that I've read your messages and will try to look at the code late next week or early the following one. And, yes, I can contact Jockers and see what that message is about.

**Comment by acrymble** [comment]
Hi @RolRodr do you need anything else from me on this translation? I'm going on leave soon so won't be able to do any more work for some time unless I get notice soon.

Thanks.

**Comment by RolRodr** [comment]
Hi @acrymble The updated lesson is looking good! I'll move it forward to the next steps. Thank you!

**Comment by anisa-hawes** [comment]
Thank you, @RolRodr!

We only copyedit original lessons, so I will move on to typesetting + generating perma.cc links.

**Comment by anisa-hawes** [comment]
Hello @hawc2 ,

This lesson is ready for your final review.

- Preview: <http://programminghistorian.github.io/ph-submissions/en/drafts/translations/sentiment-analysis-syuzhet>
- .md file: [/drafts/translations/sentiment-analysis-syuzhet.md](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/en/drafts/translations/sentiment-analysis-syuzhet.md)
- images: [/images/analisis-de-sentimientos-r](https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/analisis-de-sentimientos-r) **Important note:** The image directory for translations is named with the original lesson slug – and the folder to upload the images to on Jekyll is [/images/analisis-de-sentimientos-r](https://github.com/programminghistorian/jekyll/tree/gh-pages/images/analisis-de-sentimientos-r)
- assets: [/assets/sentiment-analysis-syuzhet](https://github.com/programminghistorian/ph-submissions/tree/gh-pages/assets/sentiment-analysis-syuzhet)

Sustainability + accessibility actions status:
- [x] Typesetting
- [x] Addition of Perma.cc links
- [x] Resizing and renaming images
- [x] @acrymble has provided alt-text for all figures
- [x] @acrymble has completed his translator's copyright declaration

@RolRodr :
- [x] Adam has already prepared a translation of the `avatar_alt:`
- [x] Adam has already prepared a translation of the `abstract:`
- [ ] @RolRodr could you prepare x2 posts for our Twitter/Mastodon Bot (please email them to me and I'll slot them into the Google Sheet upon publication)
- [x] The original author's bio is already included in our `ph_authors.yml` so we don't need to make any additions 🙂

**Comment by hawc2** [comment]
@acrymble congrats, your translation is now published!: https://programminghistorian.org/en/lessons/sentiment-analysis-syuzhet

Note the DOI may not be live for a few days, as our contact is out of the office this week, and they gave me another address to contact. 

Congrats to @jenniferisasi for having your lesson translated into English! And big thanks to @RolRodr for editing this lesson (his first lesson as a PH Editor no less!)! And gratitude to @apjanco and @ReneeDu320 for reviewing this translation!

**Comment by anisa-hawes** [comment]
Congratulations to all! ✨ 
                                    
I'll set myself a reminder to celebrate/promote via our social media channels next week.

**Comment by acrymble** [comment]
Thanks @RolRodr @hawc2 !
And thanks to @jenniferisasi for writing the great tutorial.
