### ISSUE TITLE
Proposition de traduction en français: Clustering and Visualising Documents using Word Embeddings (PH/JISC/TNA)

### ISSUE THREAD

**Issue by tiagosousagarcia** [programminghistorian/ph-submissions#487]
> This ticket was opened in advance of submission in order to allow editors to adequately allocate resources for the translations coming out of the PH/TNA/JISC partnership

Le Programming Historian en français a reçu la proposition de traduction de la leçon intitulée [Clustering and Visualising Documents using Word Embeddings (PH/JISC/TNA)](https://github.com/programminghistorian/ph-submissions/issues/485). La traduction sera déposée prochainement dans le répertoire des traductions françaises et un membre de l'équipe sera désigné pour en organiser la relecture.

**Comment by spapastamkou** [comment]
FYI @datalogism @InesSalome @icolab @matgille - une leçon à venir.

**Comment by datalogism** [comment]
Hello @tiagosousagarcia, @spapastamkou i would be happy to manage the review of it :)

**Comment by spapastamkou** [comment]
Merci, @datalogism ! On se tient au courant à propos.

**Comment by spapastamkou** [comment]
Hi there, not sure to whom I should ask now that Tiago is not working with us anymore, but I ping @anisa-hawes and @drjwbaker in case you can help. We were wondering in the FR team (@datalogism) when we should expect the arrival of the translation so that we organize accordingly our activities. Thanks a lot if you can give us a clue!

**Comment by anisa-hawes** [comment]
Dear @spapastamkou and @datalogism.

[I gather from the original Issue](https://github.com/programminghistorian/ph-submissions/issues/415#issuecomment-1266293642) that the authors have received two thorough reviews, and are now beginning work on their revised draft. I understand that their aim is to return it by early-mid November. Working on this timeline, I estimate that the piece could be copyedited and finalised by late November and ready for you to begin translation. Does that sound reasonable?

**Comment by spapastamkou** [comment]
@anisa-hawes thanks a lot for the update. But I have the impression that this issue is for a paid translation that the FR team will afterwards edit. Perhaps we should gather more information by James? In any case, this means that if Célian remains the assigned editor, the translation will not be in before January or February at best, so I can see with him for other tasks in the meantime. Thanks a lot.

**Comment by anisa-hawes** [comment]
Ah, apologies for my confusion @spapastamkou. That makes sense. Perhaps it is worth closing this Issue for now, and re-opening it in the new year when it is actively being worked on?

**Comment by spapastamkou** [comment]
Marvellous idea, I am very much in the mood for closing tickets right now:-)

On va donc fermer ce ticket pour le moment, le temps que la traduction avance, et ouvrir un ticket de relecture lorsqu'elle nous sera livrée. Si @datalogism est disponible d'ici là et souhaite en être le rédacteur assigné, il sera bien sûr en charge.

**Comment by hawc2** [comment]
Just chiming in here, I'm with @spapastamkou on closing tickets, and only starting lesson tickets for tutorials ready for the review stage. This particular lesson in the original English probably won't be published for a few months as it is.

@anisa-hawes a similar ticket #490 was created for a JISC lesson to be translated into English, even though translation has not yet started. I'd be in favor of closing it. Once we receive the translation draft, I can assign an editor, who can begin a new issue ticket once we are at that stage of the pubilishing process
