### ISSUE TITLE
Web archiving with Browsertrix

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/ph-submissions#540]
I'm very excited to say that _Programming Historian_ has received a tutorial on **Web archiving with Browsertrix** written by Helena Jaskov (@yaslena), Valérie Schafer, Frédéric Clavert (@inactinique), and Quinn Dombrowski (@quinnanya).

A live preview of the lesson is now available: http://programminghistorian.github.io/ph-submissions/en/drafts/originals/web-archiving-with-browsertrix

My first step will be to read through the lesson and provide feedback, so that the authors can respond. I'll work through the steps and also think specifically about usability, sustainability, accessibility and inclusivity.

Next, I'll identify and contact two peer-reviewers from our community. I will act as editor throughout the review process, and manage the discussions we have within this Issue.

When it comes to peer discussion, members of the wider community will also be invited to offer constructive feedback which they may post to this thread, but they are asked to first read [our Reviewer Guidelines](http://programminghistorian.org/reviewer-guidelines) and must adhere to our anti-harassment policy (below).  I will ask that all reviews stop after the second formal peer review has been submitted, so that the authors can focus on any revisions. I will make an announcement here in the thread when that has occurred.

I endeavour to keep the conversation open here on Github, but if anyone feels the need to discuss anything privately, you are welcome to email me (admin [@] programminghistorian.org).

Remember that our dedicated Ombudsperson for the English journal is [Ian Milligan](https://programminghistorian.org/en/project-team). Please contact him at any time if you have concerns which you would like addressed by an impartial observer – this will have no impact on the outcome of the peer review.

## Anti-Harassment Policy

This is a statement of the _Programming Historian_'s principles and sets expectations for the tone and style of all correspondence between reviewers, authors, editors, and contributors to our public forums.

> The Programming Historian is dedicated to providing an open scholarly environment that offers community participants the freedom to thoroughly scrutinise ideas, to ask questions, make suggestions, or to requests for clarification, but also provides a harassment-free space for all contributors to the project, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age or religion, or technical experience. We do not tolerate harassment or ad hominem attacks of community participants in any form. Participants violating these rules may be expelled from the community at the discretion of the editorial board. Thank you for helping us to create a safe space.

**Comment by hawc2** [comment]
@anisa-hawes since this lesson has not moved forward in the publishing pipeline, I'm going to close this ticket. @yaslena, @inactinique, and @quinnanya, I apologize the Programming Historian wasn't able to edit and review this lesson this year. Please don't take this as a rejection, but rather a kind request for a revise and resubmit. 

The English Programming Historian team is currently working to change how we solicit and edit submissions. We are going to post a CFP in the coming weeks for proposals to be submitted and accepted into the 2024 publishing window. This will ensure we have sufficient capacity to edit new lessons we receive and take on. I would encourage you all to take some time now to make revisions to this lesson, and to submit an updated version for consideration before the end of the year.

I believe there were some concerns with this lesson replicating instructional material contained on SUCHO's websites, and one thing to consider as you revise this lesson is how could it be better geared towards a research question/project that could be broadly applied for readers of ProgHist. It's important ProgHist lessons aspire to be more than tutorials about tools, becoming lessons in research methods that can be used in different contexts and disciplines. This lesson should probably focus less on Docker, which can be outsourced to Docker documentation, and focus more on the methods of webarchiving and their use for researchers. Giving that context and purpose to the use of Browsertrix will help ensure its acceptance for next year. I also know the software (Browsertrix, Webrecorder, etc.) undergirding this lesson has changed alot over time, so the sustainability of this lesson is also something to consider closely and explain in your submission.

Please reach out to me as Managing Editor at english@programminghistorian.org with any questions or concerns you have. I'll be happy to correspond with you via email, provide feedback, and give you more information about next year's publication process. Thank you again for your interest in publishing with the Programming Historian, and I hope you're work can be showcased in our journal in the future.
