### ISSUE TITLE
Traducción: Lectura escalable de datos estructurados

### ISSUE THREAD

**Issue by jamotilla** [programminghistorian/ph-submissions#541]
The Programming Historian en español ha recibido la siguiente propuesta de traducción Lectura escalable de datos estructurados de la lección [Scalable Reading of Structured Data](https://programminghistorian.org/en/lessons/scalable-reading-of-structured-data) por parte de @nllano. Esta traducción se encuentra en estos momentos en fase de revisión y puede leerse en:

Texto
[https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/borradores/traducciones/lectura-escalable-de-datos-estructurados.md](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/borradores/traducciones/lectura-escalable-de-datos-estructurados.md)

Imágenes
[https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/scalable-reading-of-structured-data](https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/scalable-reading-of-structured-data)

Por favor, utiliza los números de línea proporcionados en la vista previa, si eso ayuda a señalar mejor tus comentarios. Pero puedes estructurar tu revisión como mejor te parezca.

En adelante, intervendré como editor durante el proceso de revisión. Tras haber leído la lección y haber enviado mis comentarios al traductor, mi rol consistirá en solicitar otra revisión por parte de uno de los miembros de nuestro comité editorial y gestionar las conversaciones que se produzcan en este foro.

Otros miembros de nuestra comunidad también están invitados a ofrecer sus comentarios de una manera constructiva; los comentarios deberán publicarse en este hilo de conversación, por lo que se recomienda haber leído nuestra [guía para revisores](http://programminghistorian.org/es/guia-para-revisores) y tener en cuenta nuestra política contra el acoso (ver más abajo). No se aceptarán más comentarios por parte de la comunidad tras la publicación de la segunda revisión formal a fin de que el traductor pueda empezar a trabajar en los cambios solicitados. Cuando esto ocurra, publicaré un anuncio aquí.

Asimismo, me comprometo a mantener la conversación abierta a todo el mundo en GitHub. Pero si alguno de los participantes quiere ponerse en contacto en privado conmigo, puede escribirme un correo electrónico. También es posible contactar con nuestros ombudpersons.

Política contra el acoso
Esta es una declaración de los principios de Programming Historian en español y establece las expectativas para el tono y el estilo de toda la correspondencia entre los revisores, autores, editores y colaboradores de nuestros foros públicos.

El objetivo de The Programming Historian en español es ofrecer un entorno abierto en el que la comunidad de participantes sean libres para analizar ideas, realizar preguntas, sugerir cambios, y pedir aclaraciones; también queremos que sea un espacio libre de acoso y hostigamento para todo el mundo con independencia de su género, identidad, orientación sexual, diversidad funcional, apariencia física, tamaño corporal, raza, edad, religión o conocimientos informáticos. No se tolerará ningún tipo de acoso o ataque ad hominem. Los participantes que violen esta regla podrán ser expulsados del proceso editorial a discreción del equipo editorial. Si presencias o sientes que has sido víctima de algún tipo de acoso, por favor, contacta con nuestros ombudsperson [Silvia Gutiérrez De la Torre](http://programminghistorian.org/es/equipo-de-proyecto).

**Comment by jamotilla** [comment]
Hola @nllano, realizaré la lectura de tu traducción y a la brevedad te compartiré mis comentarios. Saludos, J A

**Comment by nllano** [comment]
¡Hola, @jamotilla! Genial, quedo pendiente de cualquier duda/comentario/sugerencia. 
Saludos, 
Nico

**Comment by jamotilla** [comment]
Hola @nllano te pido una disculpa por haber tardado tanto en responder. He revisado la lección y tengo las siguientes observaciones o sugerencias: 
43. Cambiar por la lección traducida al castellano: Datos tabulares en R
https://programminghistorian.org/es/lecciones/datos-tabulares-en-r
52. Com relación / con relación 
52. en una manera sistemática / de una manera...
56. Estamos creamos un puente / creando un puente
194. “Las relaciones binarias pueden formar…Paso 3” / eliminar el hipervínculo
329. “En la esquina superior derecha de Rstudio…”/ Hasta el momento no has señalado que utilizarás la herramienta…requiere un señalamiento o pequeña introducción. 
331. Mismo caso para R Markdown
368. Bmucho/ mucho 

Saludos, J A

**Comment by nllano** [comment]
Hola @jamotilla, ¿cómo estás? No te preocupes, yo también ando con muchos compromisos. Muchas gracias por los comentarios y la revisión. Voy a realizar los ajustes así llegue de viaje a final de Abril. 

¡Gracias y un abrazo!
Nico

**Comment by nllano** [comment]
Hola @jamotilla y @jenniferisasi 

¿Cómo van? Ya hice casi todos los ajustes. Solo me quedan pendientes los señalamientos a R Studio e R Markdown. 

Pensé en incluir un link para la documentación oficial de R e escribir una linea breve sobre cada elemento para que no quede el hipervínculo unicamente. ¿Les parece bien?

Abrazoz y gracias, 
Nico

**Comment by jamotilla** [comment]
Hola @nllano me parece muy bien! Saludos

**Comment by nllano** [comment]
Hola @jamotilla,

Hice los dos ajustes faltantes. 
- [x] 329. Incluí la frase "un entorno de desarrollo de código abierto para escribir y ejecutar programas en R", retirada de la lección [Procesamiento básico de textos en R](https://programminghistorian.org/es/lecciones/procesamiento-basico-de-textos-en-r).
- [x] 331. Ajusté la frase e incluí la siguiente definición "Regresa a tu **archivo** de R Markdown, **un tipo de lenguaje de marcado que permite crear documentos dinámicos en R**,"

¿Qué te parece? ¿Alguna sugerencia de redacción? ¿Crees que hace falta algún hiperlink para expandir la información sobre los dos objetos?

¡Gracias!
Abrazo, 
Nico

**Comment by jamotilla** [comment]
Hola @nllano muchas gracias por los ajustes. Esta semana leeré de nuevo la lección y te doy mis comentarios. 

Saludos, J A

**Comment by jamotilla** [comment]
Hola @nllano creo que la lección funciona muy bien. Sólo es necesario realizar algunos ajustes de redacción, es decir, considero que está lista para el proceso de copyedit. ¿Cómo procedemos @jenniferisasi? ¿Comienzo con ese proceso?

Saludos, J A

**Comment by jenniferisasi** [comment]
¡Hola @jamotilla! Veo que la lección no ha pasado por fase de revisión por pares como es común y creo que, al menos, una persona más debería revisar la traducción antes del copyediting. ¿Qué te parece?

**Comment by jamotilla** [comment]
Cierto! Ahora mismo me daré a la tarea de buscar a un revisor. Tengo en mente a un colega que puede ser el indicado. Saludos

**Comment by jenniferisasi** [comment]
Y se me había pasado por alto al fijarme más que nada en el salto del paso de revisión: No hay copyediting para las traducciones :)

**Comment by nllano** [comment]
¡Hola!

Genial, entonces seguimos con revisión por pares.
Seguimos :)

Saludos

**Comment by jamotilla** [comment]
Cierto!!!! Que buena onda, así la publicamos más rápido :)

**Comment by jamotilla** [comment]
Hola a todas y todos, @martinzh va a fungir como revisor de la traducción.

**Comment by rivaquiroga** [comment]
@jamotilla, @jenniferisasi, hasta donde tengo entendido, luego del cambio en los planes de acceso a la API de Twitter el paquete rtweet ya no permite hacer búsqueda de tuits. El plan gratuito de la nueva versión de la API no tiene opción de extracción de datos. 
Así que la lección original y sus traducciones quedaron obsoletas 💔

**Comment by nllano** [comment]
@rivaquiroga ahhh 💔

**Comment by jenniferisasi** [comment]
Ay, cierto @rivaquiroga, no sé dónde tengo la cabeza. Después de la labor que se ha tomado @nllano me da pena desecharla como si nada, ¿qué os parece entonces si me la leo yo como revisora y la publicamos aunque haya que dejar un mensaje y retirarla casi al instante? Por lo menos quedará como publicación para Nicolás. 

@anisa-hawes what do you think?

**Comment by rivaquiroga** [comment]
Estoy de acuerdo. Me parece que hay que publicarla igual, aunque tengamos que retirarla, porque permite reconocer el trabajo de todas las personas involucradas y visibilizar el impacto del cambio en Twitter. 
En el mensaje de advertencia al inicio habría que señalar que el Free Tier de la API ya no permite la búsqueda de tweets, por lo que la lección solo sigue siendo vigente para quienes tengan algún tipo de plan

**Comment by jamotilla** [comment]
Hola, estoy de acuerdo

**Comment by jenniferisasi** [comment]
@anisa-hawes is there any plan beyond [#2848](https://github.com/programminghistorian/jekyll/issues/2848) to add a warning message at the beginning of the original EN lesson, following @rivaquiroga's idea above: 

> Twitter's Free Tier API access pass doesn't allow for the search (and download) of tweets, so the lesson is only useful to those who are paying for an upgraded plan. 

Something along those lines.

**Comment by nllano** [comment]
Hola,

De acuerdo con la solución propuesta. 

Muchas gracias!

**Comment by martinzh** [comment]
Hola, acá los comentarios y observaciones del artículo:

- línea 43: Falta cerrar paréntesis
- línea 49: Cambiar "grande conjunto de datos" por "gran conjunto de datos" o por "una gran cantidad de datos"
- línea 56: cambiar "estamos creando" por "creamos"
- 79: frase redundante "cada uno de los cuales añade numerosas funcionalidades a sus funciones básicas."
- 188: Corregir frase: "Ahora vamos a continuaremos"
- 264: ¿Por qué la distribución de cuentas verificadas y no verificadas muestra que es un tópico politizado? 
- 268: ¿Cómo sabemos que: "las personas interactúan mucho más con los tweets de usuarios verificados que con los tweets de cuentas no verificadas"?
- 282: Ser consistente con el formato para mostrar texto relacionado con código, hay lugares donde se usas "comillas" y otros donde se usan `code_blocks` o no se usa formato como en el caso de TRUE y FALSE
- 321: "haciendo una lectura atenta **de** ... "
- 333: agregar formato de code block a "dplyr"
- 339: línea no traducida
- 343: Igual, ser consistente con el formato elegido para mostrar texto relacionado con código, en este caso "favorite_count" 
- 347: Igual, hay una mezcla de formatos
- 358: Mezcla de formatos
- 366: Mezcla de formatos
- 370: Typo
- 372: Mezcla de formatos
- 398: línea no traducida
- 400: Mezcla de formatos
- 404: Mezcla de formatos
- 425: línea no traducida
- 438: Explicar que es un tweet-id
- 442: No es claro a que se refiere con "utilizar de forma combinatoria"

En general las observaciones son de redacción y formato, hay un par sobre el contenido y algunas conclusiones que están en el texto pero, como este caso es una traducción, puede que no sean relevantes para este proceso de revisión en particular.

Saludos y disculpa por la tardanza

**Comment by anisa-hawes** [comment]
Hello @jenniferisasi, @rivaquiroga and @nllano,

I've made a suggestion for how we could word the warning box in [Issue 2848 on Jekyll](https://github.com/programminghistorian/jekyll/issues/2848). I would be grateful if you could let me know your thoughts, and help me to make sure the Spanish is correct 🙂 . When the words are agreed we can add the information box to your new translation. 

Thank you, 
Anisa

**Comment by nllano** [comment]
Hola @martinzh,

Muchas gracias por la revisión atenta. Voy a ajustar el archivo con tus comentarios. 

Saludos y gracias.

**Comment by jenniferisasi** [comment]
Hola @nllano ¿cómo va esto?

@anisa-hawes I think we forgot to respond to you here; I just re-checked the comment and it looks good to me.

**Comment by nllano** [comment]
Hola @jenniferisasi, 

No lo he revisado aún, disculpas. Esta semana hago los ajustes sin falta.

**Comment by anisa-hawes** [comment]
Thank you, @jenniferisasi and @nllano. [You did respond](https://github.com/programminghistorian/jekyll/issues/2848#issuecomment-1624237140)! 

I added the warning box to this Markdown file already https://github.com/programminghistorian/ph-submissions/commit/8d9938cde3a754270936dec4cbe3e8e596b2a52d, but of course welcome your corrections if it isn't exactly how you'd like it. There are no ES lessons already published that are affected, and this is the only lesson in draft which requires the warning box at the moment.

```
<div class="alert alert-warning">
El acceso a la API de Twitter ha cambiado recientemente. El nivel gratuito ya no permite a los usuarios buscar y descargar datos de Twitter. Lamentablemente, esto significa que algunos elementos de esta lección sólo funcionarán <b>para quienes paguen un plan de acceso a la API</b>. [2023]
```
</div>

**Comment by jenniferisasi** [comment]
Estimado @nllano, ¿cómo sigues? Tengo buenas noticias. Como puedes ver en nuestros últimos comentarios hemos decidido publicar esta lección a pesar de que no es muy útil ahora mismo. La publicaremos sin anunciar porque la buena noticia es que el equipo en francés está trabajando en la actualización de la lección en #622 - esto quiere decir que podremos editar la lección publicada para reflejar dichos cambios en un futuro cercano, hacerla útil de nuevo, por parte de @nllano u otro voluntario. 

Pasaba pare preguntar si podrías aplicar los cambios sugeridos por la revisión por pares en el plazo de un mes para que el Publishing Team pueda publicarla en septiembre. 

¡Gracias!

**Comment by nllano** [comment]
Hola @jenniferisasi!

¿Cómo estás? Yo saliendo de un semestre intenso, pero todo bien. Me alegra recibir esa noticia de la decisión de publicar y de la actualización por parte del equipo francés (y posteriores ajustes a la versión traducida).

Sobre la aplicación de los cambios sugeridos por la revisión: Sí, lo puedo hacer en ese plazo de un mes.

¡Abrazo y gracias por la paciencia!

**Comment by jenniferisasi** [comment]
¡Súper @nllano! Me alegro de que te parezca acertada la decisión y que puedas editarla pronto 😄 mil gracias

Yo estoy ya a más de la mitad de la época menos ajetreada y, sin embargo, sin parar para empezar fuerte el semestre 😅

**Comment by jamotilla** [comment]
Hola @nllano dime si hay algo en lo que te pueda ayudar con los cambios sugeridos. 

Saludos, JA

**Comment by nllano** [comment]
Hola @jamotilla,
Muchas gracias por la generosidad y colaboración!
Este fin de semana voy a realizar los ajustes sugeridos y cualquier duda te aviso

Saludos y gracias!

**Comment by nllano** [comment]
Hola @jamotilla,

¿Cómo estás? ¡Espero que todo bien!

Hice (casi) todos los ajustes que faltaban. Los que están sin el check del task list son aquellos sobre los cuales no estoy muy seguro o tengo preguntas. El número de las líneas correspondiente a los comentarios de Martín está actualizado en esta lista.

Gracias por la paciencia.  

¡Un abrazo!

- [x] 50: Falta cerrar paréntesis
- [x] 56: Cambiar "grande conjunto de datos" por "gran conjunto de datos" o por "una gran cantidad de datos"
- [x] 63: cambiar "estamos creando" por "creamos"
- [x] 86: frase redundante "cada uno de los cuales añade numerosas funcionalidades a sus funciones básicas." **Lo cambié por “elementos básicos”**
- [x] 195: Corregir frase: "Ahora vamos a continuaremos"	
- [ ] 264: ¿Por qué la distribución de cuentas verificadas y no verificadas muestra que es un tópico politizado? **Esta pregunta tendría que ser respondida por las autoras y autores, y aún así, me parece que la lección no es el lugar más adecuado para entrar en profundidad en esta discusión. Martin ya lo había señalado en sus comentarios.**
- [ ] 268: ¿Cómo sabemos que: "las personas interactúan mucho más con los tweets de usuarios verificados que con los tweets de cuentas no verificadas"? **Mismo punto que el anterior.**
- [ ] 289: Ser consistente con el formato para mostrar texto relacionado con código, hay lugares donde se usas "comillas" y otros donde se usan code_blocks o no se usa formato como en el caso de TRUE y FALSE. **TRUE y FALSE lo dejé sin formato, actualicé las comillas para las variables, los paquetes los dejé sin formato (los habíamos introducido con negrita) y el _like_ lo actualicé con cursiva como lo tenemos a lo largo de la lección. La única duda que me queda es si todos los TRUE y FALSE deberían estar formateados como código.**
- [x] 328: "haciendo una lectura atenta de ... "
- [x] 340: agregar formato de code block a "dplyr". **Lo dejé sin formatear para estandarizar.**
- [ ] 346: línea no traducida. **Creo que Martín se refiere al mensaje "Output removed because of privacy reasons". ¿Lo debo traducir también?**
- [x] 354: Igual, ser consistente con el formato elegido para mostrar texto relacionado con código, en este caso "favorite_count"
- [x] 365: Igual, hay una mezcla de formatos
- [x] 375: Mezcla de formatos
- [x] 366: Mezcla de formatos
- [x] 377: Typo
- [x] 379: Mezcla de formatos
- [ ] 405: línea no traducida. **Misma pregunta sobre "Output removed because of privacy reasons".**
- [x] 407: Mezcla de formatos
- [x] 404: Mezcla de formatos
- [ ] 425: línea no traducida. **Misma pregunta sobre "Output removed because of privacy reasons".**
- [ ] 445: Explicar que es un tweet-id. **¿Creen que deberíamos incluir una nota? La [documentación](https://developer.x.com/en/docs/twitter-ids ) actual de Twitter/X no es muy precisa sobre qué es un Twitter-ID.**
- [x] 449: No es claro a que se refiere con "utilizar de forma combinatoria". **Lo cambié a "utilizar de forma combinada".**

**Comment by jamotilla** [comment]
Hola @nllano, todo muy bien gracias, espero que tu también te encuentres muy bien. En efecto, no es necesario que atiendas los comentarios que señalas ya que como bien observas son de origen de la lección en inglés. Si @jenniferisasi y tú están de acuerdo, podemos continuar con el proceso. Saludos

**Comment by nllano** [comment]
Hola @jamotilla. 
Gracias por la revisión y la respuesta. Sobre las preguntas de fondo (264, 268), de acuerdo con tu opinión de seguir adelante.
Con relación a las dudas/preguntas de formato (289, 436 y 445), quedo pendiente de sugerencias y recomendaciones.
¡Saludos y gracias!

**Comment by jamotilla** [comment]
Hola @nllano, respecto a las dudas y preguntas, considero lo siguiente:
289: considero que debemos dejarlo tal cual aparece en la versión original
346: Lo mismo, dejarlo tal cual la lección en inglés 
445: omitir la sugerencia de la nota aclaratoria

Saludos, JA

**Comment by nllano** [comment]
Hola @jamotilla, 
Muchas gracias por la respuesta. 
Genial, entonces creo que podemos seguir con el proceso (los tres puntos están ajustados de acuerdo a la lección en inglés)

Saludos, 
Nico

**Comment by jamotilla** [comment]
Perfecto, hago una última lectura y estamos listos para publicarla. 

Saludos,

**Comment by jenniferisasi** [comment]
Hola @jamotilla ¿tuviste la oportunidad de realizar una última lectura para proceder a la publicación de la lección? ¡Gracias!

**Comment by jamotilla** [comment]
Hola, si @jenniferisasi en un ratito procedo. Una disculpa por la demora. Saludos

**Comment by jamotilla** [comment]
Hola @jenniferisasi creo que el texto está listo para publicarse. Saludos, J A

**Comment by nllano** [comment]
Gracias por la lectura detallada, @jamotilla, y a todo el equipo por la colaboración y paciencia.
Saludos

**Comment by anisa-hawes** [comment]
Thank you, @nllano and @jamotilla.

Our next steps will be to typeset this translation + carry out our accessibility checks. As [discussed](https://github.com/programminghistorian/ph-submissions/issues/541#issuecomment-1598953713) and [agreed](https://github.com/programminghistorian/ph-submissions/issues/541#issuecomment-1598965738), @jenniferisasi has taken the decision to move forward towards publication with the [warning box you translated in place](https://github.com/programminghistorian/ph-submissions/issues/541#issuecomment-1671897453). 

Thanks to all for the energy you've given to this. I understand that it is not an ideal outcome.

**Comment by jenniferisasi** [comment]
Thank you @jamotilla for the last reading, @nllano for all your work and patience and @anisa-hawes for moving us forward all the way to publication. Please, let me know when the checks will be ready and we will do the silent publishing. 

¡Gracias!

**Comment by charlottejmc** [comment]
Hello @jenniferisasi,

This lesson's sustainability + accessibility checks are in progress.

- Preview: 
  
**ES:** <http://programminghistorian.github.io/ph-submissions/es/borradores/traducciones/lectura-escalable-de-datos-estructurados>    

Publisher's sustainability + accessibility actions:
- [x] Typesetting
- [x] Addition of Perma.cc links
- [x] Addition of alt-text for all figures
- [x] Check/resize images
- [x] Check/adjust image filenames
- [x] Receipt of translator's copyright agreement (Hola @nllano, nuestro formulario de declaración es para reconocer sus derechos de autor y concedernos permiso para publicar esta lección. Por favor, ¿podría descargar y rellenar [este formulario](https://programminghistorian.org/assets/forms/Derechos-de-autor-y-de-publicacion.pdf)? Envíelo por e-mail a publishing.assistant [@] programminghistorian.org. Muchas gracias.)
- [x] Request DOI
- [ ] Remove outside contributors from ph-submissions  

Editorial input to YAML:
- [x] Translation of `avatar_alt:`
- [x] Translation of `abstract:`
- [x] Translation of author(s) bio for `ph_authors.yml`
- [x] Provide the translation-reviewer's full name


Files we are preparing for transfer to Jekyll:

**ES:**  
- .md file: [/es/borradores/traducciones/lectura-escalable-de-datos-estructurados.md](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/borradores/traducciones/lectura-escalable-de-datos-estructurados.md)
- images: [/images/scalable-reading-of-structured-data](https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/scalable-reading-of-structured-data)
- assets: [none]

Promotion: (N/A as we have decided to publish this translation silently)
- ~[ ] Prepare announcement post (using template)~
- ~[ ] Prepare evergreen posts~

Publisher's post-publication tasks:
- [x] Add lesson slug to the Annual Count of Published Lessons
- [x] Update the ph_data folder in the ph-contributors repository 

---- 

Hola @nllano, thank you so much for all your work so far. Just a few things I wanted to ask/note before we can finalise the publication:
- [x] I noticed that at lines 358 + 373 + 407 + 434, it still says in English “(Output removed because of privacy reasons)”. Could you please either translate this short sentence, or confirm whether we can simply delete it? Thank you!
- [x] I may be wrong, but shouldn't the code at lines 363 and 369 say `plazasesamo_datos_mas_de_50_favoritos`, rather than `sesamestreet_datos_mas_de_50_favoritos`?
- [x] I think it may be useful to provide the translations of the following words, which are only present in English in the translation:
      - Essential (l.83)
      - output (l.84)
      - dataframe (l.116)
      - hard-code (l.195)
      - favorite (l.291)
      - outlier (l.449)

Thank you for your patience as we work through these final steps together! ✨

**Comment by anisa-hawes** [comment]
Hola @nllano,

The EN avatar alt is: _Drawing of honeycomb_ 🐝

**Comment by nllano** [comment]
Hi @charlottejmc,

Thank you for flagging those details that were missing/wrong!
I'll make the adjustments tomorrow :)

@anisa-hawes thank you for sharing the avatar alt 🐝. 

Thank you both for the fantastic work and collaboration during the process!

**Comment by nllano** [comment]
Hi @charlottejmc and team, 
I did the following adjustments:

- [x] Translation of "(Output removed because of privacy reasons)" to "(El resultado fue suprimido por motivos de privacidad)"
- [x] Adjustment of code at lines 363 and 369 to `plazasesamo_datos_mas_de_50_favoritos?`
- [x] Signed form sent to publishing.assistant [@] programminghistorian.org

Regarding the translation of the word you listed:
- [x] Essential (l.83). I left it in English, because, If I am not mistaken, Twitter kept the English name to this API service across different languages. 
- [x] output (l.84). I am not sure if the TweetSets service (not working currently) that is referenced in the `/en/lessons/beginners-guide-to-twitter-data` had a Spanish version, which means you had to choose the English "output" to download the data. 
- [x] dataframe (l.116). If I am not mistaken, there is not standardized translation for dataframe in Spanish. It is common to use both dataframe and data frame. 
- [x] hard-code (l.195). Not sure how to translate this. Any ideas?
- [x] favorite (l.291). We kept all the variables (e.g., user.verified, full_text) from the Twitter data in its original language. If we decided to translate "Favorite" to "Favorito" we would have to do it across the board and change some of the code blocks.
- [x] outlier (l.449). I kept the word in English, but added the following explantion: "un dato individual que se desvía significativamente del resto en un conjunto"

Any comment or suggestion to further adjust these items is welcome!
Thank you.
Nicolás

**Comment by charlottejmc** [comment]
Dear @nllano,

Thank you very much for all your adjustments, and for sending the copyright form to my email. 

I apologise for being unclear about the translations: I was rather thinking of keeping the English words as you have used them currently, but simply adding the Spanish translation next to them in brackets, like this: English (Español). This would help our readers who have very little knowledge of English to grasp the context a little better. What do you think?

**Comment by nllano** [comment]
Dear @charlottejmc, 

No problem at all. Thank you for the explanation! I think that would work nicely. I'll make the adjustments on Friday —I am traveling tomorrow. 

Thank you!

**Comment by nllano** [comment]
Dear @charlottejmc, 

I added the Spanish translation of the following words:
- [x] "Essential" (Esencial)
- [x] "output" (salida). That part of the sentence now looks like this: "como formato de "output" (salida)"
- [x] "hard-coded". I substituted the word for "modificar directamente" 

I didn't add a translation to these two:
- [x] "Favorite". The same sentence already explains what Favorite means in this context: "Favorite" es el nombre dado para un like en nuestro conjunto de datos."
- [x] "dataframe". As I mentioned before, this is also commonly used in Spanish.

Let me know if this works and/or if you have any suggestions to improve it.
Thank you!

**Comment by charlottejmc** [comment]
Dear @nllano, thank you very much for your translations, and for your explanations! This all seems perfect to me.

One last thing – I noticed that the avatar description is not yet translated. In the English version, it is _Drawing of honeycomb_. Would _Dibujo de un panal de abejas_ work in Spanish?

¡Muchas gracias! I think this lesson is now ready for publication, @anisa-hawes and @jenniferisasi.

**Comment by nllano** [comment]
Dear @charlottejmc, 

Oh, I had missed the avatar translation, my bad. 
Your suggested translation is perfect, thank you!

Here we go! Thank you team.

**Comment by anisa-hawes** [comment]
[Lectura Escalable de Datos Estructurados](https://programminghistorian.org/es/lecciones/lectura-escalable-de-datos-estructurados) is published.

Congratulations @nllano, and thanks to **all** who have contributed.

@jenniferisasi and the Publishing Team realise that (due to API access restrictions) this is a very imperfect ending to a long process, but that the translation represents a lot of work from a lot of people. 

---

Our suggested citation for this lesson is:

>Max Odsbjerg Pedersen, Josephine Møller Jensen, Victor Harbo Johnston, Alexander Ulrich Thygesen, y Helle Strandgaard Jensen, "Lectura Escalable de Datos Estructurados", traducido por Nicolás Llano Linares, Programming Historian en español 8 (2024), https://doi.org/10.46430/phes0066.

---


Sincere thanks.

**Comment by jenniferisasi** [comment]
Thank you @anisa-hawes for taking these files to publication!
