### ISSUE TITLE
Revisão da tradução da licção "La reconnaissance automatique d'écriture à l'épreuve des langues peu dotées (PH/TNA/JISC)"

### ISSUE THREAD

**Issue by DanielAlvesLABDH** [programminghistorian/ph-submissions#559]
O Programming Historian em português recebeu a proposta de tradução da lição 'AI for automated transcription of Historical Documents (PH/TNA/JISC)' por @joanacvp.

A lição traduzida está [aqui](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/esbocos/traducoes/transcricao-automatica-grafias-nao-latinas.md).
A lição original está [aqui](https://programminghistorian.org/fr/lecons/transcription-automatisee-graphies-non-latines).

Agradeço à @joanacvp pela tradução.
Eu serei o editor da tradução. Irei procurar dois revisores.

Irei pedir para avaliarem a tradução para o português, assim como se há necessidade de adequação de dados ou algum conteúdo. As sugestões devem ser incluídas neste ticket, na forma de comentários. Para cada modificação a ser sugerida, por favor, peço para indicar as linhas de maneira que facilite os ajustes. O ideal é realizar as modificações após as sugestões dos dois revisores.

Todos os membros da comunidade estão convidados a oferecer feedback construtivo que deve ser publicado neste canal, mas é solicitado que leiam primeiro as diretrizes para revisores (/directrizes-revisor) e sigam a nossa política anti-assédio. Pedimos que todas as revisões parem após o envio da segunda revisão formal para que a tradutora possa concentrar-se no ajuste da lição. Eu farei um anúncio neste tópico quando isso ocorrer.

Vou me esforçar para manter a conversa aberta aqui no GitHub, mas se alguém sentir a necessidade de discutir algo em particular, pode entrar em contato comigo, ou pode sempre recorrer para o nosso mediador independente se achar necessário.
Se houver alguma preocupação da tradutora, ele pode entrar em contato com o mediador do PH em português (Luís Ferla).

---

[**Permissão para publicação**]

Peço à Joana Paulino que deixe aqui nos comentários a seguinte declaração sobre direitos de autor/tradutor.
 
> I the translator hereby grant a non-exclusive license to ProgHist Ltd to allow The Programming Historian em português to publish the tutorial in this ticket (including abstract, tables, figures, data, and supplemental material) under a [CC-BY](https://creativecommons.org/licenses/by/4.0/deed.en) license.

**Comment by joanacvp** [comment]
I the translator hereby grant a non-exclusive license to ProgHist Ltd to allow The Programming Historian em português to publish the tutorial in this ticket (including abstract, tables, figures, data, and supplemental material) under a [CC-BY](https://creativecommons.org/licenses/by/4.0/deed.en) license.

**Comment by anisa-hawes** [comment]
Olá, @DanielAlvesLABDH ,

The key files are here:
- .md file: [/esbocos/traducoes/transcricao-automatica-grafias-nao-latinas.md](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/esbocos/traducoes/transcricao-automatica-grafias-nao-latinas.md)
- original images: [/images/transcription-automatisee-graphies-non-latines](https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/transcription-automatisee-graphies-non-latines)
- assets: [none] 

The lesson preview is available here.
- Preview: <http://programminghistorian.github.io/ph-submissions/pt/esbocos/traducoes/transcricao-automatica-grafias-nao-latinas>

--

Olá @joanacvp,

You will be aware that the figure images which accompany this lesson are extremely complex, and contain a vast amount of text (which is in the original language).

This of course, raises an accessibility problem, which we are aware of (I know that the alt-text is detailed, and that is very necessary).  But it also creates a translation challenge.

Do you plan to recreate the images? 

One option raised for consideration has been that we request the original author facilitates future translation by providing a "mute" version of each diagram or figure.

Let me know what you think?

With many thanks, 
Anisa

**Comment by joanacvp** [comment]
Hi @anisa-hawes!

Indeed, I can create the figures which are now in french (translating them into Portuguese). It would be great if the original author provide a "mute" version. Do you think it is possible for this case?

Thank you very much.

**Comment by anisa-hawes** [comment]
Hello @joanacvp. Yes, I think this should be possible. I will write to the original author, and ask them if they can provide this for us. I will let you know as soon as I hear back so that you can move this forwards. Thank you.

Another option we could consider is to create the diagrams in [Mermaid](https://mermaid.live/), or similar. (Have you worked with Mermaid before? I'm new to it, but was able to create various forms of flow chart and timeline diagrams after some experimentation). This may actually provide a more robust solution to the accessibility issues as well as the translation challenge?  – I will still go ahead and ask the author, but would be interested to hear your thoughts.

**Comment by joanacvp** [comment]
Thank you very much @anisa-hawes. I haven't worked with Mermaid yet, but I will try for sure.

**Comment by anisa-hawes** [comment]
Dear @joanacvp. I hope you're well?

The original author has kindly provided us with a "mute" version of all figures that contain text (i.e., the diagram element only, without any annotations / labels) upon which I hope you will be able to overlay your translated text. Please let me know if you think this will be workable for you, or if I can help in any way?

- [x] I'll upload them to the original images directory now https://github.com/programminghistorian/ph-submissions/commit/17bd7033aadb27668c859afedca97c2dc7cb3c51 : [/images/transcription-automatisee-graphies-non-latines](https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/transcription-automatisee-graphies-non-latines). You will find them named following this convention: `tr-pt-transcricao-automatica-grafias-nao-latinas-01.png`. In case it is easier for you, I will also send them to you by email. Either way, you can download the "mute" versions, then re-work and upload each one.

Please note that this set does not include Figure 18 (the author cannot find this file) or Figure 21 (the author does not have the source – this image was generated with Python). Do you think you can create your own alternative versions for these two?

**Comment by anisa-hawes** [comment]
Hello @joanacvp ,

Thank you for sending me your annotated versions of these figures! I've resized and uploaded them: https://github.com/programminghistorian/ph-submissions/commit/5d73be91a31c8761a8e08d1e4f0d199160f2f40c. You will notice that I have allowed us slight flexibility with the scale here, re-sizing them to 1000px on the longest edge (rather than 840px on the longest edge) because I found that the text was becoming pixelated when I made them any smaller. Please let me know what the loading time is like from your side? If it is acceptable, I feel this might be a reasonable compromise. 

I think the .zip file you shared with me is missing figure 4, which remains in the "mute" form [in the directory](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/images/transcription-automatisee-graphies-non-latines/tr-pt-transcricao-automatica-grafias-nao-latinas-04.png).

**Comment by anisa-hawes** [comment]
N.B. I am aware that I need to re-size the remaining (untranslated) images ahead of publication too, as these are much larger than is our convention. I will make myself a note to do this.

**Comment by joanacvp** [comment]
Dear @anisa-hawes. Thank you very much for all the support in the files. Figure 4 is the same as Figure 1. Do you want me to make a copy and upload it with the the reference to fig 4?

Thank you!

**Comment by anisa-hawes** [comment]
Oh! I didn't realise this @joanacvp. Is figure 4 an exact duplicate of figure 1? (With exactly the same annotation?)

**Comment by joanacvp** [comment]
No problem. Indeed, it is the same :)

**Comment by anisa-hawes** [comment]
Okay. I’ll adjust the filename in the liquid syntax so that it refers to Figure 1 again, although the caption is for Figure 4.

I’m a little bit confused, but I will translate a few paragraphs and I’m sure it will make sense 🙃

**Comment by joanacvp** [comment]
If it is easier for you I can do it :)

**Comment by anisa-hawes** [comment]
Just seeing this, @joanacvp. Done: https://github.com/programminghistorian/ph-submissions/commit/185e594a6da0f3baa67024e773fd66a200122a7f

**Comment by joanacvp** [comment]
Perfect!

**Comment by DanielAlvesLABDH** [comment]
Dear @anisa-hawes and @joanacvp, is this ready for move forward? Can I start looking for reviewers? Thanks

**Comment by joanacvp** [comment]
Hello! Yes, we can move forward 👍

**Comment by DanielAlvesLABDH** [comment]
Thank you @joanacvp

**Comment by DanielAlvesLABDH** [comment]
Enviei convites a dois colegas para serem revisores desta tradução. Estou a aguardar.

**Comment by DanielAlvesLABDH** [comment]
O Hervé Baudry @herreveb aceitou ser um dos revisores desta tradução. O ficheiro com a tradução está disponível aqui: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/esbocos/traducoes/transcricao-automatica-grafias-nao-latinas.md
Depois da revisão feita, peço ao Hervé que coloque num comentário aqui as suas sugestões e correcções, indicando as linhas onde seja necessário fazer alterações. No final a @joanacvp incorpora essas alterações no ficheiro.
Uma ajuda para a revisão está disponível aqui: https://programminghistorian.org/pt/directrizes-revisor
Tendo em conta que o nosso público é tanto brasileiro, como português, procuramos compatibilizar as duas formas de escrita. Para orientação sobre as opções de tradução pode ser útil ler esta página: https://github.com/programminghistorian/jekyll/wiki/Agreed-Terminology-for-PH-em-portugu%C3%AAs
Uma vez mais, obrigado Hervé

**Comment by DanielAlvesLABDH** [comment]
O Oldimar Cardoso @oldimar aceitou ser outro dos revisores desta tradução. O ficheiro com a tradução está disponível aqui: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/esbocos/traducoes/transcricao-automatica-grafias-nao-latinas.md
Depois da revisão feita, peço ao Oldimar que coloque num comentário aqui as suas sugestões e correcções, indicando as linhas onde seja necessário fazer alterações. No final a @joanacvp incorpora essas alterações no ficheiro.
Uma ajuda para a revisão está disponível aqui: https://programminghistorian.org/pt/directrizes-revisor
Tendo em conta que o nosso público é tanto brasileiro, como português, procuramos compatibilizar as duas formas de escrita. Para orientação sobre as opções de tradução pode ser útil ler esta página: https://github.com/programminghistorian/jekyll/wiki/Agreed-Terminology-for-PH-em-portugu%C3%AAs
Muito obrigado, Oldimar!

**Comment by oldimar** [comment]
Boa tarde, seguem minhas sugestões de alteração à tradução do texto "La reconnaissance automatique d'écriture à l'épreuve des langues peu dotées":

Acredito que valeria acrescentar uma nota da tradutora explicando a tradução de “peu dotées” como “não-latinas” e o significado literal de “peu dotées”.

linha 41:
substituir "– longe disso -" por "– longe disso –" (está abrindo com meia-risca e fechando com hífen, mas precisa abrir e fechar com meia-risca)
Se possível, substituir “colmatar” por “preencher”

linha 83:
“monitorizar” não existe no português brasileiro, sugiro “observar” ou “acompanhar”

linha 121:
Substituir “4. Abordagem quantitativa ou qualitativa .” por “4. Abordagem quantitativa ou qualitativa.” (há um espaço sobrando antes do ponto final).

linha 138:
A expressão _fine-tuning_ não foi renderizada em itálico por estar dentro de uma div, que também impediu a quebra de linha deste parágrafo.

linha 478:
Na expressão “mas uma _bouding-box da _baseline_” faltou fechar o underline de “bouding-box” pra que ele renderize como itálico.

linha 563:
Substituir “e a à ground-truth” por “e à ground-truth” (eliminar um “a”).

linha 647:
No parágrafo que começa com “A plataforma Calfa Vision oferece gratuitamente” há dois itálicos desconfigurados por estarem dentro de div: _layout_ e _corpus_.

**Comment by joanacvp** [comment]
Muito obrigada @oldimar. De facto, a tradução de “peu dotées” foi algo com que me debati, pois no seu sentido literal tem uma conotação pejorativa em português. Estou aberta a outras sugestões e/ou opções se considerarem que considerem mais adequadas.
Fico a aguardar o feedback do @herreveb para incorporar as mudanças.
Muito obrigada mais uma vez.

**Comment by oldimar** [comment]
Sim, acho importante informar ao leitor que o texto traduzido contém esse
sentido pejorativo, pois o etnocentrismo fica impregnado nas entrelinhas do
texto mesmo que a tradução o corrija no título. Se o leitor tiver acesso ao
título original, pode imaginar que a ideia de "pouco dotadas" se refere a
alguma questão propriamente linguística (o que na prática é exatamente o
contrário, as línguas latinas é que são menos sofisticadas e "pouco
dotadas" nesse sentido). Mesmo assim, a ideia de "pouco dotadas" do ponto
de vista dos recursos tecnológicos de tradução não deixa de ser
etnocêntrica.

Abraço,

Em seg., 18 de dez. de 2023 às 07:38, joanacvp ***@***.***>
escreveu:

**Comment by herreveb** [comment]
Proponho: com pouco Ground Truth

**Comment by herreveb** [comment]
Concordo com as sugestões de Oldimar.
+ linha 647  corrigir : A Calfa também está comprometido = comprometida

**Comment by DanielAlvesLABDH** [comment]
Caro @herreveb, pergunto se não tens mais comentários ou sugestões sobre a tradução feita pela @joanacvp?

**Comment by herreveb** [comment]
Sobre a tradução em si, não.
Sobre a lição, sim, mas é outro assunto, não é?

**Comment by DanielAlvesLABDH** [comment]
Caro @herreveb, a lição original já foi revista e publicada. Podemos fazer ligeiras adaptações quando se procede à tradução para português. Em princípio a @joanacvp já fez as que considerou necessárias. Mas também isso deve ser revisto. Para além da verificação da tradução, se os revisores (tu e o @oldimar) considerarem que há algo mais a esclarecer, alterar ou comentar na versão em português para que fique mais fácil de ser aplicada pelos futuros utilizadores, era bom que dessem essas indicações à Joana aqui nos comentários. Obrigado a ambos!

**Comment by joanacvp** [comment]
Bom dia. Se considerarem que não existem mais alterações ou elementos a esclarecer posso introduzir as mudanças indicadas. Muito obrigada!

**Comment by DanielAlvesLABDH** [comment]
Bom dia @joanacvp. Falei com o Hervé e podemos avançar com as correcções da tradução. Obrigado

**Comment by joanacvp** [comment]
Bom dia. Agradeço, mais uma vez, as sugestões de revisão. As mesmas já foram introduzidas no ficheiro @DanielAlvesLABDH. Muito obrigada

**Comment by DanielAlvesLABDH** [comment]
Fiz uma revisão geral da tradução. Agradeço à @joanacvp pela excelente contribuição. Agradeço ainda ao @oldimar e ao @herreveb pelas revisões. Está pronta a publicar @ericbrasiln e @anisa-hawes, faltando apenas o DOI.

**Comment by joanacvp** [comment]
Óptimo! Muito obrigada!

**Comment by anisa-hawes** [comment]
Thank you, @DanielAlvesLABDH and @joanacvp! We're very excited that another translation from the Jisc/TNA special series is nearing publication! ✨ 

The Publishing team will now begin **Phase 6. Sustainability + Accessibility**. This is a series of checks and actions which include reviewing the lesson's typesetting + generating archival links.

--

Hello @ericbrasiln,

This lesson's sustainability + accessibility checks are in progress. @charlottejmc and I will update you here in the Issue thread when these are complete so that you can read through the lesson one final time before we stage it for publication. We'll aim to finish this work by the end of next week **Friday 8th March**.

- Preview: 

<http://programminghistorian.github.io/ph-submissions/pt/esbocos/traducoes/transcricao-automatica-grafias-nao-latinas>  

Publisher's sustainability + accessibility actions:
- [x] Typesetting
- [x] Addition of Perma.cc links
- [x] Check alt-text for all figures
- [x] Check/resize images
- [x] Check/adjust image filenames
- [x] Receipt of translator's copyright agreement
- [x] Add doi
- [x] Add all contributor names to our list of Unique Contributors

Editorial input to YAML:
- [x] Translation of `avatar_alt:`
- [x] Translation of `abstract:`
- [x] Translation of author(s) bio for `ph_authors.yml`

Files we'll prepare for transfer to Jekyll:

**PT:**  
- .md file: [/esbocos/traducoes/transcricao-automatica-grafias-nao-latinas.md](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/esbocos/traducoes/transcricao-automatica-grafias-nao-latinas.md)
- images: [/images/transcription-automatisee-graphies-non-latines](https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/transcription-automatisee-graphies-non-latines) **Note:** We have uploaded the `pt-tr` image set to Jekyll in advance https://github.com/programminghistorian/jekyll/pull/3189
- assets: [none] 

Promotion:
- [x] Prepare announcement post (using template)
- [ ] Prepare evergreen posts – @ericbrasiln, could you help us by providing x2 posts for future promotion via our social media channels? You can add these directly to the `ph-evergreens-twitter-x` spreadsheet that has been shared with you, reply in a comment below, or email them to Charlotte at publishing.assistant[@]programminghistorian.org.

**Comment by joanacvp** [comment]
Hi @anisa-hawes.  Is there a place where I can find the translator's copyright agreement? Thank you very much in advance

**Comment by anisa-hawes** [comment]
Hello @joanacvp. Yes! It is here: <[formulário de declaração](https://programminghistorian.org/assets/forms/Direitos-autorais-e-permissao-para-publicar.pdf)>.

**Comment by joanacvp** [comment]
Thank you @anisa-hawes. I just sent it to you by email :)

**Comment by ericbrasiln** [comment]
Hello, 

This week and next I'm at an academic event in Rio de Janeiro.  I won't be able to work on the proghist until next Friday.  I apologize for the inconvenience.

**Comment by anisa-hawes** [comment]
Thank you, @ericbrasiln. No pressure from our side. 

We'll work through the Sustainability + Accessibility steps between now and then 🙂

**Comment by anisa-hawes** [comment]
Noting here that we have uploaded the `pt-tr` image set to Jekyll in advance https://github.com/programminghistorian/jekyll/pull/3189.

**Comment by charlottejmc** [comment]
Hello @joanacvp, I just have a couple questions to run by you which came up while I was typesetting.

- [x] In paragraph 21 of [the preview](https://programminghistorian.github.io/ph-submissions/pt/esbocos/traducoes/transcricao-automatica-grafias-nao-latinas), the words  “massivamente”, “dados”, and “arquitetura” were italicised, but I wasn't sure why. Could you explain what the emphasis was supposed to show on these words, so that I can find the best way to typeset them? 
- [x] In paragraph 98, the lesson talks about “scripta não latina". I saw that this was the word used in the original French version as well, but I wasn't confident that's it not a typo, because everywhere else the lesson says "scripts" instead. Could you confirm whether we want "scripts" or "scripta" here? 

Thank you very much! We're really close to publication now ✨

**Comment by joanacvp** [comment]
Hi @charlottejmc!
In paragraph 21 I followed the same formatting as on the original lesson. On the original lesson they are italicised, so I choose to do the same.
In paragraph 98 it is ok as "scripta", meaning, written in non-latin languages.

Thank you very much :)

**Comment by anisa-hawes** [comment]
Hello @ericbrasiln,

This lesson's sustainability + accessibility checks for this lesson are now complete.

- [x] translation of original author(s) bio for `ph_authors.yml`
- .md file: [/esbocos/traducoes/transcricao-automatica-grafias-nao-latinas.md](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/esbocos/traducoes/transcricao-automatica-grafias-nao-latinas.md)
- images: [/images/transcription-automatisee-graphies-non-latines](https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/transcription-automatisee-graphies-non-latines) **Note:** We have uploaded the `pt-tr` image set to Jekyll in advance https://github.com/programminghistorian/jekyll/pull/3189
- assets: [none] 

Promotion:
- [x] Prepare announcement post (using template)
- [x] Prepare evergreen posts – @ericbrasiln, could you help us by providing x2 posts for future promotion via our social media channels? You can add these directly to the `ph-evergreens-twitter-x` spreadsheet that has been shared with you, reply in a comment below, or email them to Charlotte at publishing.assistant[@]programminghistorian.org.

**Comment by ericbrasiln** [comment]
@anisa-hawes

I've just included the 2 posts in the spreadsheet.

We can move the files to the jekyll repository for publishing.

**Comment by ericbrasiln** [comment]
Congratulations to @joanacvp for the translation and thank you for your partnership and constant contribution to the project.

Thanks to @DanielAlvesLABDH for editing and @oldimar and @herreveb for the review, @anisa-hawes and @charlottejmc for their support!

Another high-quality lesson published in Portuguese!

**Comment by DanielAlvesLABDH** [comment]
Great! Thanks to all!

**Comment by anisa-hawes** [comment]
[Reconhecimento automático de manuscritos para o teste de idiomas não latinos](https://programminghistorian.org/pt/licoes/transcricao-automatica-grafias-nao-latinas) is published!

Congratulations on this translation @joanacvp!
Thank you **all** for your contributions 

---

Our suggested citation for this lesson is:

>Chahan Vidal-Gorène, "Reconhecimento automático de manuscritos para o teste de idiomas não latinos", traduzido por Joana Vieira Paulino, Programming Historian em português 4 (2024), https://doi.org/10.46430/phpt0046.

We appreciate your help to circulate our social media announcements about this lesson among your networks:
Twitter/X: https://twitter.com/ProgHist/status/1768621793458139177
Mastodon: https://hcommons.social/@proghist/112099808383129390

---


Sincere thanks.
