### ISSUE TITLE
Review Ticket for "Dealing with Big Data and Network Analysis"

### ISSUE THREAD

**Issue by ianmilligan1** [programminghistorian/ph-submissions#87]
The Programming Historian has received the following tutorial on 'Dealing with Big Data and Network Analysis' by @jgmjgm. This lesson is now under review and can be read at:

http://programminghistorian.github.io/ph-submissions/lessons/dealing-with-big-data-and-network-analysis-using-neo4j-and-python

Please feel free to use the line numbers provided on the preview if that helps with anchoring your comments, although you can structure your review as you see fit.

I will act as editor for the review process. My role is to solicit two reviews from the community and to manage the discussions, which should be held here on this forum. I have already read through the lesson and provided feedback, to which the author has responded.

Members of the wider community are also invited to offer constructive feedback which should post to this message thread, but they are asked to first read our Reviewer Guidelines (http://programminghistorian.org/reviewer-guidelines) and to adhere to our anti-harassment policy (below). We ask that all reviews stop after the second formal review has been submitted so that the author can focus on any revisions. I will make an announcement on this thread when that has occurred.

I will endeavor to keep the conversation open here on Github. If anyone feels the need to discuss anything privately, you are welcome to email me. You can always turn to @amandavisconti if you feel there's a need for an ombudsperson to step in.

## Anti-Harassment Policy

This is a statement of the Programming Historian's principles and sets expectations for the tone and style of all correspondence between reviewers, authors, editors, and contributors to our public forums.

> The Programming Historian is dedicated to providing an open scholarly environment that offers community participants the freedom to thoroughly scrutinize ideas, to ask questions, make suggestions, or to requests for clarification, but also provides a harassment-free space for all contributors to the project, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age or religion, or technical experience. We do not tolerate harassment or ad hominem attacks of community participants in any form. Participants violating these rules may be expelled from the community at the discretion of the editorial board. If anyone witnesses or feels they have been the victim of the above described activity, please contact our ombudspeople (Ian Milligan and Amanda Visconti - <http://programminghistorian.org/project-team>). Thank you for helping us to create a safe space.

**Comment by ianmilligan1** [comment]
We are resolving some page build errors – once they're fixed, I'll let folks know here.

**Comment by ianmilligan1** [comment]
Overall, I really enjoyed this tutorial and had fun working through it. I've pushed up a pull request with some minor edits, but also have these comments here:

* **Difficulty Level**: I think this is probably an intermediate, maybe an advanced, lesson. Thoughts?
* **Platforms**: This is clearly developed for OS X, but should also work on Windows. Can you put some cautionary notes throughout?  When running commands like `bin/neo4j-import`, how would that work on Windows?
* **Line endings**: Great cautionary note around line 166. Can you give a bit more detail on how they should do this, or what they should be looking for?
* **Command Line**: Perhaps give a link to our Programming Historian lesson on the command line. Also, where can they find the Neo4J directory in a standard installation? (i.e. on OS X `/Applications/Neo4j Community Edition 3.2.1.app/Contents/Resources/app`?)
* **Data**: Can you provide the CSVs up front? I know you want people to read it through, but it would be great to have those CSV files ready for donwload. I wanted to play with it but I'd like to download a dummy `companies.csv`, etc.
* **Pip**: Can you provide a link to the Programming Historian lesson on pip?

Once you do this, esp. uploading the dummy data, I'd love to try to do a full comprehensive run through. Thanks!

**Comment by jgmjgm** [comment]
Went through and added these. Thanks for the suggestions.

There really isn't much difference between platforms besides the fact that
the scripts end in .bat on Windows.
Because I added the example data, I added a brief section to encourage the
user to quickly visualize it as well. I want to emphasize that (a) this is
fake and (b) that visualization will help to see problems in data (i.e.
that the ties in a network are randomly generated.)

**Comment by ianmilligan1** [comment]
Line 35: I think average user might have trouble finding this directory. Can you give the path? i.e. `/Applications/Neo4j Community Edition 3.2.1.app/Contents/Resources/app/` holds `bin` for me. Also should they give full path to the CSV files in the command?

When running

```
bin/neo4j-import --into OurNewDatabase.db --id-type string     --nodes:Company companies.csv --relationships:CONTAINS director_details.csv
```

I then got:

```
Error: Could not find or load main class org.neo4j.tooling.ImportTool
```

Seems to be an error: https://github.com/neo4j/neo4j/issues/8347.

Is this what I should be doing, or is there a better workaround? I'd worry that our users might get stuck if they have to do this workaround.

**Note the workaround does work..**

**Comment by ianmilligan1** [comment]
A few more thoughts:

- Cypher: Make explicit what this is. Is it bundled with Neo4j? A separate download?
- Should they try to do any of the Cypher examples or just read the section?
- Cypher: I went to the localhost:7474/browser/ - but I don't know my password for this? Can you walk people through screenshot by screenshot? By default password is Neo4j. But then how do I find my graph. I am sure I could look at docs but we try to keep people in the lesson.

**Comment by jgmjgm** [comment]
Thanks for catching this. I had to change the classpath in my script. I
simply added

export CLASSPATH=neo4j-desktop-3.1.3.jar:$CLASSPATH

just before the command. I also tend to run it from the ./bin directory.
You may prefer to add the complete path before the command. It seems that
java is just not finding the neo4j jar file. I have no idea why there's a
big discussion about it on the link you provided. On the face of it, this
seems like a simple problem to fix in the bash script.

I can add text giving an overview of this process (hacky but allows users
to get around bug in procedure) or we can simply remove it altogether from
the lesson (could confuse users). There are pros and cons to each decision.
Do you have a preference?

**Comment by ianmilligan1** [comment]
I think we should give an overview of the process, but that could be something we ask the reviewers...

**Comment by jgmjgm** [comment]
Thanks for the suggestions. I've updated some of the images and text.

Was the password issue really confusing? On the web interface it is written
that the default user and password is neo4j/neo4j. Regardless, I've updated
the text anyway and included how to disable the password prompting.

**Comment by ianmilligan1** [comment]
OK sounds good. The goal with a lot of this is to make it fairly user friendly, so I'm just going through this and trying to follow the instructions without too much thinking.

And to confirm, the command

```
bin/neo4j-import --into OurNewDatabase.graphdb
    --nodes:Company companies.csv 
    --relationships:CONTAINS director_details.csv 
```

Should `OurNewDatabase.graphdb` point to the `test.graphdb` that you suggested setting up in the initial one? Or no, it should create a new one, which you then stop the neo4j instance and point it at it?

**Comment by jgmjgm** [comment]
An (overly long) aside on the OurNewDatabase.graphdb comment.

Personally, I prefer not to make tutorials too geared towards a single
example. Instead, I prefer descriptive variable names like the one I
provided that explain what something is or does. Similarly, I'm leery about
adding too many "helpful" digressions into the main body of the lesson
(such as the password discussion, dos2unix aside, etc.). I am concerned
that these diversions may make the lesson overly complex to read and more
difficult to use later as a reference.

That being said, I understand the PH has it's own explicit and implicit
standards for explaining things. I'm willing to take your advice to conform
to those standards.

One solution that comes to mind is to put items like the password
digression or even the dos2unix discussion as brief discussions in an
appendix. Ideally, the user could click an in-document anchor, go to the
desired section for more information and then click back to the main body.
I don't know if this is feasible given the PH template or desirable given
the established style of the lessons. Just a thought. I don't feel overly
strongly about it right now but if the reviewers ask for more explanatory
asides then perhaps we could revisit this.

**Comment by ianmilligan1** [comment]
The approach I tend to take is that we like to have a nice, worked out example – and then people can change things once they want to add their own data, etc. As it stands, just following the instructions, I get to the Neo4j front end and don't have any data. I think we basically want to have a fairly idiot-proof walkthrough with your data, that people could then do again with their own data, and learn that way.

**Comment by jgmjgm** [comment]
"As it stands, just following the instructions, I get to the Neo4j front
end and don't have any data."

Totally confused by this. Data has been added from the beginning. Users can
follow through with every step. Am I missing something?

**Comment by ianmilligan1** [comment]
Now that you've changed the command, it might work. When I ran it last night it wasn't clear to me whether I should change the `neo4j-import` command to point to the database previously created or not. And if I'm getting confused, I suspect our readers will as well. I will try to run this through later today, but am on the road soon so there may be a delay.

**Comment by jgmjgm** [comment]
That's helpful. Okay, there was a section on loading the database that
should have been moved down a little. When you asked for example data I
added it a little off where it should have been. I think the order is more
sensible now.

Thanks for taking the time to step through it.

**Comment by ianmilligan1** [comment]
Just a heads up @jgmjgm – I've been on the road since we last chatted. I am hoping to finish my read through pretty soon.

**Comment by ianmilligan1** [comment]
OK great - I've gone through and I think we're ready to send to review. What I'll do over the next few days, @jgmjgm, is reach out to two peer reviewers to take a look though the lesson as well and provide detailed feedback. We'll also invite community contributions. Once we have the reviews, you'll have a chance to review and respond, and we'll be off to the races.

Be in touch soon.

**Comment by jgmjgm** [comment]
Sounds good. Thanks for following through the lesson.

**Comment by ianmilligan1** [comment]
An update. We have one peer reviewer who's agreed to take on the task, and he will have his comments in by the end of the month. Just lining up another one right now. Many thanks!

**Comment by ianmilligan1** [comment]
And next update. I've lined up a second peer reviewer, who needs a bit more time – but we'll have comments in 6-7 weeks or so. Given the summer and conference season, I think that's perfectly reasonable. Thanks so much for your patience @jgmjgm and I'll really look forward to receiving these comments in due course.

**Comment by fdlaramee** [comment]
Greetings Jon!

Here is my peer review report.

First of all, thank you for taking on this project. Production pipelines rarely receive the attention that they deserve considering how much time and effort goes into setting them up. I have no doubt that this lesson will prove quite useful.

Second, although I have written down many (many) suggestions, by no means do I expect all of them to be implemented. Please treat them as food for thought and decide, along with Ian, which need to taken into account and which need not.

For convenience, I have split the report into three parts: structure, text, and technical. « Structure » contains a handful of general suggestions. « Text » contains notes that I wrote down as I read the lesson without running the code or using the tools; basic understanding and flow issues, that sort of thing. « Technical » discusses the issues I experienced while running the pipeline on a (relatively) clean machine where I had to install everything from scratch, including a JDK to run java scripts from the command line.


**PART 1 — STRUCTURE**

First, this is both an advanced lesson and a long one. It covers a lot of ground, several tools, and numerous topics. Therefore, I believe that it should not expand beyond what is strictly necessary. 

I recommend taking out the sections on early databases and on SQL, and tightening up the « What is a database » and « NoSQL » sections into a single one — that doesn’t mention SQL or NoSQL but simply says that you have chosen a graph database for this project. Readers who are familiar with SQL do not need this extraneous material; those who are not will be confused as to why you choose to introduce a technology that you abandon immediately afterwards and won’t get enough of a « feel » for what SQL does to understand the difference between SQL and Neo4J. 

Second, there are two major topics in this lesson: various ways to populate a Neo4J database, and the pipeline between Neo4J and Gephi. It may be more effective to keep them separate, either in major sections or maybe even in two separate tutorials. Therefore, I would consider taking the code that creates a set of Cypher commands from a GEXF file, starting around Paragraph 117, and joining it with the other database population methods introduced earlier. It may not be possible (there are a lot of cross-references between tools and technologies that may be hard to disentangle) but it might make things cleaner.


**PART 2 — TEXT**

I will now run through all of the notes that I took as I read the tutorial. Each is attached to a specific paragraph of text or a bit of code.

Paragraph 2 contains a very good setup of what is needed in terms of tools. You might want to list the data files that you will be using during the tutorial here as well, so that the reader can acquire all of the necessary assets ahead of time. I would also include a sentence that explains the lesson’s goals: to create a graph database of companies and directors and to export it for visualization, that sort of thing. Finally, I would put links to lessons that cover the prior knowledge required by the tutorial, on topics like CSV, Unicode, and graph theory.

Also in Paragraph 2, you describe Python as a c-style language. I would take that out; as someone who has worked with 20+ programming languages over nearly 35 years, I can tell you that Python has very little in common with C!

Paragraph 3: Excellent points!

Paragraph 4: Maybe link to the other database tutorials on ProgHist?

Paragraph 7: The term « table » only really applies to relational databases. Object-oriented and old-style hierarchical databases do not use tables per se.

P9: How about giving an example of a good/bad index? Indexing on something that the user will query often, like names, is usually more effective than on ID numbers that they won’t remember.

P17: If you keep this paragraph, please adjust your verb tenses. Otherwise, excellent point.

P20: Is Neo4J the most popular database on the market, or simply the most popular graph database? 

P27: If you are going to mention BOM, you might want to include a figure that shows what it looks like. Otherwise, you might want to cut the reference.

P37: If your file contains the directors’ names, please display them in your figure. Things are not very clear. What exactly is in director_details.csv, anyway? Only a list of the periods during which a director was shared by two companies? The database’s structure is a bit murky. Indeed, I wonder if this case study is a good example of why one would want to use a graph database.

P42: Indeed, that would be a clearer case for a graph database. If reorganizing the tutorial accordingly would be feasible, it would gain from it.

P45: This probably should be moved up to the top of the section.

P57: Not sure that changing your database structure midstream is a good idea. It introduces an extra layer of complexity that may cause more harm than good.

P62: Something is wrong with the sentence. 

P64: Please specify where to find the Options button on screen.

P67: The code snippet below is the first piece of Cypher that you show to the reader. Please explain what it does and the syntactic conventions of the language (like the role of the colon in the n:Company idiom). Also, you should probably move this to the top of the section, so that the user has a way to check that the importation process worked before moving on to the next item on the agenda.

P71: See the comment for Paragraph 9.

P83: Please rephrase. There is no db_query.py script to which to add anything yet.

P99: You might want to avoid using shellscript syntax like $NEO4J_HOME in your text, or at least supplement it with something more readable.

P104: Just a thought: not sure that « we simply… » is appropriate in a tutorial about such an involved process.

Code fragment between P117 and P118: Just for clarity’s sake, you should mention the name of this script either in the text or in a comment at the top of the code.

P130: You might want to include a screenshot or two to tell your readers where to find the commands to do all this in Gephi. Unless you specify in the introduction that you assume significant prior knowledge of this tool.


**PART 3 — TECHNICAL**

I ran the tutorial on a (relatively) clean machine that had none of the required components except for Python 3.x. Here are a few things you might want to add/take into consideration because it looks like your preexisting software environment allowed you to skip a few steps that others may find baffling.

First, at least on a Mac, running java command line scripts like neo4j-import requires the prior installation of a JDK; the standard Java runtime does not work under command line conditions and the script produces a « no run-time virtual machine found » error or something like that. 

Second, the neo4j-import script failed and the « export CLASSPATH » workaround in Paragraph 39 did not work. The error message I obtained was the following: 

export: `3.2.2.app/Contents/Resources/app/bin/neo4j-desktop-3.2.2.jar:': not a valid identifier

I resurrected my long-dormant vi editing skills to try to fix the script with quotes in critical places, to no avail. I ended up following the link in Paragraph 40 and using the sudo commands provided by one of the kind souls there, which solved the problem.

Third, neo4j-import is apparently deprecated; I received a warning message asking me to use something else instead. For longevity purposes, you might want to modify your procedure accordingly.

Fourth, you should mention that the csv files should be placed in the working directory (or that the user should provide full paths), and that the commands below Paragraph 33 should all be on a single line even though it appears to be three lines in your code snippet. Easy to catch for someone like me who started working with Unix shells in 1988 (!) but not for an inexperienced user.

Fifth, neo4j-import places the test.graphdb database in the working directory, i.e., the /Applications/Neo4j Community Edition 3.2.2.app/Contents/Resources/app/ folder. This is nowhere near the location of the default.graphdb database that Neo4J expects, and Neo4J’s file-opening dialog box is unable to locate it at all for some reason even when I point it towards the right directory. I moved test.graphdb to a more appropriate location (next to default.graphdb in the same directory) from the command line and that fixed the issue, but again a shell newbie will be completely lost.

Sixth, the index creation code snippet in Paragraph 71 is a bit misleading because Cypher will fail if you ask for two indexes at the same time. You should split it in two.

Seventh, the script below Paragraph 83 is in Python 2.x; you might want to mention that and say that 3.x users should wrap the print statements in parentheses. Just in case of an absolute Python beginner venturing into your neck of the woods! 

Eighth, you should mention that the Streaming plugin window in Gephi will not show the client and master items (or anything else, for that matter) unless the user has loaded a graph of some sort already. That looks like a bug in the plugin because it makes no sense, but there you go.

![capture d ecran 2017-07-26 a 11 01 43](https://user-images.githubusercontent.com/28898295/28634893-af9c229e-7206-11e7-90bd-69b3f4be4dab.jpg)


Ninth, the link to APOC in Paragraph 98 brings up version 3.1.3.8 on GitHub, whereas the most current version of Neo4J requires 3.2.0.4 according to APOC’s page. However…

Finally, no matter how many times I try to install and reinstall various versions of APOC, Neo4J always fails to launch with the plugin installed. Here is a screenshot of the last error message I received; this is a problem from which I can’t recover on my own, and I have therefore been unable to stream data to Gephi.

![capture d ecran 2017-07-26 a 11 26 36](https://user-images.githubusercontent.com/28898295/28634928-c28f978c-7206-11e7-9ae0-ebf7427a38f5.jpg)


I hope that you won’t find this report too disturbing. Again, thanks for doing this; I am sure that you will save a lot of people a lot of grief!

Best regards,
François Dominic Laramée

**Comment by ianmilligan1** [comment]
Thanks so much @fdlaramee! 

@jgmjgm, feel free to begin thinking about these comments. That said, we still have one more review coming in, although due to holiday season and DH 2017 it won't be in for a few more weeks.

**Comment by ianmilligan1** [comment]
Just a quick update: I've been in touch with the reviewer and it should be in relatively soon. Thanks for your patience @jgmjgm. 😄

**Comment by ianmilligan1** [comment]
Just a final check in.. our reviewer is a bit overdue 😄 but that may be related to conference organizing.  I will aim to have a firm timeline by end of the week. Really sorry about this @jgmjgm.

**Comment by ianmilligan1** [comment]
Well, I've decided to give up on our reviewer.. I'm so sorry, we kept having deadlines pushed back, and I'm just going to switch gears. our next reviewer will have the review in by the end of the week, and I'll put this on front of desk to make sure you don't have to wait on me. 😦

**Comment by greebie** [comment]
For the sake of expediency, I think I will produce my review now.   I read the paper, made notes and then saw @fdlaramee 's review and found a lot of cross-over.  That gives me the benefit of getting to write a lot less.  :)

The big picture challenge is the structure.  I agree that the tutorial is very advanced and long.  My experience with advanced users is that they already have experience using tools, so they are probably looking to skim for the main elements.  Keeping focus will be key.

I think this tutorial could use one or two introductory sentences that invite the user to read more.  Why should a historian care about big data, networks or whatnot?  The grumpiest historian character in my brain is asking "Why would I care to make a bunch of big messy spiderwebs for my research when I can hit the archives instead?"  I don't think you have to satisfy my grumpy historian, but a little bit of an intro might help.

You have assumed a good amount of knowledge about networks here as well, including words like "nodes" and "edges" without defining them.  Even someone with network experience may be using different language ("vertices" and "links" for instance).  I would include a sentence, plus a link to a PH tutorial on networks if there is one available.

Moreover, the concept of a network is key to both node4j and gephi.  You may need to flush that out more.  Remember PH has an international audience so there may be many different conventions around nomenclature etc.

Setting prerequisites for your tutorial would help as well.  

I really like the approach with the glossary early on, but with the corrections above (eg. python is a c-like language) considered.

I would like to reinforce some comments above related to keeping focus.  For example, covering all the potential pitfalls and pratfalls of csv is something of a non sequitur.  Just make sure they have data that will work, and let them learn about unicode issues as they work through their own problems.

Unfortunately, installing node4j is not quite so easy as to be taken for granted.  If you merely press the big button, you grab the Desktop version .dmg and the installation instructions are not very good.  Sure, I could have been more attentive, but it is always nicer to be able to run through a tutorial without having to do troubleshooting. 

I have not been able to start node4j myself.  I got this error.

![image](https://user-images.githubusercontent.com/111091/32241532-ca4a7154-be46-11e7-8dd0-1e2e3987d5cf.png)

You may have to provide the installation instructions directly. 

I don't think you should assume that people already have networkx installed.  I would work through every detail to guide your person through the tutorial.

Overall, I think the tutorial is quite ambitious and worthwhile.  However, the installation problems need resolving in order for it to be effective.

**Comment by ianmilligan1** [comment]
Great, thanks @greebie – really appreciate it, and good to see the overlap with @fdlaramee's comments too. So we're back on track.

If I may suggest the best way forward.. @jgmjgm do you want to try to tweak the installation instructions a bit more, and then maybe @greebie can do another quick play through to make them work. Feel free to update the lessons repo itself, or if you want, you can just e-mail me and I can upload as well.

(and don't feel too bad about installation hiccups.. the fun of DH tools. We'll find a way to lay this out nice and clearly. I think half of my research time on infrastructure goes towards smoothing out these installation problems...)

Otherwise, both sets of reviews provide quite a bit of detail. At first glance, they all seem relatively easy to incorporate, save perhaps some of the errors. 

For the suggestion:
>I recommend taking out the sections on early databases and on SQL, and tightening up the « What is a database » and « NoSQL » sections into a single one — that doesn’t mention SQL or NoSQL but simply says that you have chosen a graph database for this project. Readers who are familiar with SQL do not need this extraneous material; those who are not will be confused as to why you choose to introduce a technology that you abandon immediately afterwards and won’t get enough of a « feel » for what SQL does to understand the difference between SQL and Neo4J.
I can see arguments in either direction, so I'll just ask you to reflect on what you think is the best way forward with this - we can bounce ideas around.

So at this stage, I'd suggest trying to tackle the critical error first (I can test too), and then perhaps devoting some cycles to incorporating the other suggestions that the review has made.

Thanks! Happy to chat more here Jon or if I can test anything, do let me know.

**Comment by ianmilligan1** [comment]
A heads up that I've been in touch with the author and revisions are in progress. 😄

**Comment by jgmjgm** [comment]
First, thanks @ianmilligan1, @fdlaramee and @greebie for taking the time to look at this and review it. 
I'm working away now and hope to have something soon.

**Comment by ianmilligan1** [comment]
First lesson has been rendered here, different URL now: http://programminghistorian.github.io/ph-submissions/lessons/dealing-with-big-data-and-network-analysis-using-neo4j

@jgmjgm are you fine with me removing the original version from the repo as it has a different file name? (the history would be preserved of course)

**Comment by fdlaramee** [comment]
Hi @ianmilligan1, 

Since I am still attached to this thread, do you want/expect me to review the new versions of the lesson (or lessons?) as well?

Thanks,
FDL

**Comment by ianmilligan1** [comment]
@jgmjgm I know it's still under development, but I have been going through the "dealing-with-big-data-and-network-analysi-using-neo4j" workflow.

The index creation failed for me:

```
CREATE INDEX ON :COMPANY(id)
CREATE INDEX ON :COMPANY(name)
```

led to:

```
Invalid input 'C': expected whitespace, comment, ';' or end of input (line 2, column 1 (offset: 29))
"CREATE INDEX ON :COMPANY(name)"
 ^
```

As did: 

```
(n1:NODE)-[:relationship]->(n2:NODE)
```

But as you can see below, everything else was working well!

![screen shot 2017-12-15 at 1 32 34 pm](https://user-images.githubusercontent.com/3834704/34055373-dfec07c4-e19c-11e7-9669-de2885630ed9.png)

@fdlaramee – if you wanted to try out the newer version, to make sure it worked on your end, that would be wonderful! But no expectation if you are too busy this time of year.

**Comment by jgmjgm** [comment]
Oops. @fdlaramee <https://github.com/fdlaramee>  made this point. The create indexes should be separate commands. I have them written as one.

Jon

jon.mackay@gmail.com

**Comment by fdlaramee** [comment]
@ianmilligan1 I have my own lesson to finish this week before I (mostly) go away from the keyboard until mid-January, but I'll try to give it a whirl. Probably on the 22nd.

**Comment by ianmilligan1** [comment]
Since it the lesson is in development, maybe it's easiest if you focus on your own lesson @fdlaramee, and I can work with Jon. Thanks again for all your help with this!

@jgmjgm – why don't you revise, and when you're happy for me to look again and do a final walkthrough (I think we're almost there!) please ping me either on e-mail or here.

**Comment by fdlaramee** [comment]
@ianmilligan1 All right, signing off then!

All the best to everyone for the new year!

**Comment by jgmjgm** [comment]
Okay, will do! Thanks and happy holidays to you both!                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         From: Ian MilliganSent: Thursday, December 21, 2017 3:57 PMTo: programminghistorian/ph-submissionsReply To: programminghistorian/ph-submissionsCc: jgmjgm; MentionSubject: Re: [programminghistorian/ph-submissions] Review Ticket for "Dealing with Big Data and Network Analysis" (#87)Since it the lesson is in development, maybe it's easiest if you focus on your own lesson @fdlaramee, and I can work with Jon. Thanks again for all your help with this!
@jgmjgm – why don't you revise, and when you're happy for me to look again and do a final walkthrough (I think we're almost there!) please ping me either on e-mail or here.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/programminghistorian/ph-submissions","title":"programminghistorian/ph-submissions","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/programminghistorian/ph-submissions"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ianmilligan1 in #87: Since it the lesson is in development, maybe it's easiest if you focus on your own lesson @fdlaramee, and I can work with Jon. Thanks again for all your help with this!\r\n\r\n@jgmjgm – why don't you revise, and when you're happy for me to look again and do a final walkthrough (I think we're almost there!) please ping me either on e-mail or here."}],"action":{"name":"View Issue","url":"https://github.com/programminghistorian/ph-submissions/issues/87#issuecomment-353455864"}}}

**Comment by ianmilligan1** [comment]
Hi @jgmjgm just quickly following up: do you have a rough ETA on when we might expect the revisions? Thanks!

**Comment by jgmjgm** [comment]
Hi Ian. I'm shooting for closer to the end of the week. I had a pipe burst
during the cold snap so my schedule was a little messed up. All fixed up
now...

**Comment by ianmilligan1** [comment]
Oh no, that's awful! Glad you guys are dry and hopefully warm. Just ping me here or by e-mail if you have any questions as you pull things together. 😄

**Comment by jgmjgm** [comment]
Hi Ian,

I think I've cleaned up the outstanding issues. The last major revision
dealt with the points raised by both reviewers. At this point, I just
cleaned up some fairly minor issues. I think it is quite clear now that the
portions of the lesson that dealt with visualization have been removed
unless there is another set of changes I missed.

I moved the sections on Gephi and linking it to Neo4j to a different lesson
file. I haven't worked on reworking this text despite some detailed
comments on it because I'm not sure if PH would be interested in this.
Besides, I'm sure we'd all like to just get this lesson finished before
something new is started! 😀

BTW - Luckily the leak was rather small so just some minor water damage
cleanup after the new pipes were put in. The joy of old houses...

**Comment by ianmilligan1** [comment]
Thanks! I'll review shortly, and thanks so much.

**Comment by ianmilligan1** [comment]
OK thanks for this, @jgmjgm! I've done a read through and it works. Some minor updates to Neo4J (only notable change was database now requires password/login, which I noted).

Let's start moving towards final steps. Could you do/provide the following:

* close read just to make sure you're happy with the prose;
* short abstract - 1 to 3 sentences
* short bio statement - 1 to 2 sentences

I'll start taking a look for a possible nice image to represent the lesson.  

You can provide bio here on the ticket, abstract in the lesson file itself or here, and edits probably easiest directly on the lesson file. 

Can't wait to publish this!

**Comment by ianmilligan1** [comment]
Thanks @jgmjgm @fdlaramee @greebie for everything – we are migrating this over to the main site. Discussion will continue in the PR there. 

https://github.com/programminghistorian/jekyll/pull/710
